---
title: "Project Guidelines"
subtitle: "or, *Guidelines for the formulation of the PPG II (and onwards) classification of extant ferns and lycophytes*"
author: "PPG Coordinating Committee"
toc: true
date: "2023-05-09"
bibliography: references.yaml
---

## Overview and philosophy

The PPG I [-@ppg2016] classification has been a valuable resource for users of fern and lycophyte taxonomy, including researchers, professionals, and members of the general public.
However, we have made considerable gains in our understanding of fern and lycophyte systematics since 2016, and so an update is warranted.
This update will occur in two phases.
In **[Phase One](#phase-1)** we will aim to develop an updated fern and lycophyte classification at the rank of genus and above—this is effectively a direct update to PPG I.
In **[Phase Two](#phase-2)**, the plan for which is still being developed, we will expand our classification to include the species rank—at the end of this phase we aim to have a classification that includes a full list of extant fern and lycophyte species.

As with the original PPG, we aspire to be inclusive, community-driven, and consensus-oriented.
**Monophyly is a primary criterion for taxon acceptance**; non-monophyletic taxa may be recognized (and flagged as such) when no exclusively monophyletic treatment is available (e.g., taxa that have not been subject to phylogenetic analysis, etc.).

Based on our experiences with PPG I, and due to the greatly expanded scope of PPG II, we are opting for some changes to our process.
First and foremost, **we are moving our discussion and proposal platform away from taxon-specific committees that deliberated over email to a PPG-wide GitHub-based platform** (described [below](#github-interface-for-communication-and-coordination); see also the [GitHub Guide](https://pteridogroup.github.io/github.html)).
This platform will allow all PPG members to contribute to any discussion or proposal, and will archive those discussions in perpetuity.
Secondly, in conjunction with this new platform, we are moving away from the committee-based model (each committee made a proposal for the classification of their focal taxon, and those proposals were then voted upon by the full PPG community).
Instead, **each proposal will have a period of open discussion, and then we will have a direct vote by the PPG membership**: proposals will be adopted if at least ⅔ of the votes are in favor.

## The PPG website and PPG GitHub repo

The PPG website ([https://pteridogroup.github.io](https://pteridogroup.github.io)) provides documentation about the maintenance of PPG and will serve as a user-friendly portal to the data once PPG II is ready.
The PPG GitHub repo ([https://github.com/pteridogroup/ppg](https://github.com/pteridogroup/ppg)) houses the raw data and is used as a forum for discussing taxonomic proposals.

## Phase 1

This phase is an update of PPG I: a genus-and-above classification of ferns and lycophytes.
Similar to PPG I, we aim for a published version, with all PPG contributors included as authors.
In addition to a different decision-making process (see below), this publication will differ from PPG I in that we will explicitly discuss minority opinions (defined as those with at least ⅙ votes against).

### Intended products

The primary product of Phase One will be a peer-reviewed publication, similar to PPG (2016); this publication will also include elements of Phase Two, such as an online supplement providing the data in a standard format ([Darwin Core](https://dwc.tdwg.org/terms/#taxon)).

### GitHub interface for communication and coordination

PPG II will be constructed communally using the online hosting service GitHub, which will provide all PPG members the opportunity to make proposals and to comment on them, and will additionally archive all proposals and discussion in perpetuity.
GitHub is easy to use, the only requirement being that each participant needs to create a free account; detailed instructions are available in the [Guide for GitHub Discussions](https://pteridogroup.github.io/github.html#setup).
If any PPG members are not comfortable participating in this format, they can send proposals to any of the [PPG coordinators](#coordinating-committee), who can then post that proposal on their behalf.
There are two primary activities supported by our PPG GitHub site: 1) A [discussion forum](https://github.com/pteridogroup/ppg/discussions), for the discussion of any matter pteridophyte-related, including PPG organization, etc; 2) A [proposal forum](https://github.com/pteridogroup/ppg/issues) (known as "Issues" in GitHub parlance), where anyone can propose a modification to the PPG I classification, and where those proposals can then be discussed.
Voting on proposals will happen after the discussion period, via a Google Forms survey circulated on the PPG mailing list.

### Guidelines for effective proposals

Much of the success of our PPG II process will depend on PPG members making clear and informative proposals.
For example, we want to avoid a set of similar proposals that differ only in their argumentation while proposing the same or similar changes.
With that goal in mind, please follow these guidelines (**if a proposal does not meet at least the first two guidelines below it may be removed from consideration without a vote**):

1. **Any higher-level taxon (genus and above) proposed for recognition needs to be published** (taxa "in press", etc., are not allowed).
Similarly, all supporting studies should be published.
For example, if one is advocating for a name change based upon the non-monophyly of a taxon recognized in PPG I, the phylogeny demonstrating non-monophyly needs to be published.
2. **Each proposal should take PPG I as the starting point** (i.e., only _changes_ to PPG I should be proposed).
3. Each proposal should be cohesive and self-contained—try to avoid compound proposals where possible.
Proposing a different set of genera within a family, for example, would be appropriate because the new generic circumscriptions depend on each other.
However, proposing the recognition of two unrelated generic treatments should be done with two separate proposals.
4. Anyone is welcome to make a proposal for any taxon, but it would be collegial to allow the researchers most closely associated with the name change "first dibs", so to speak.
These people are also probably in the best position to write a comprehensive proposal.
5. Each proposal should be comprehensive: it should include all relevant details to allow other PPG members to make an informed decision about the proposal.
Those details include summaries (with citations) of the arguments supporting a particular proposal, and, ideally, a discussion of the main counter arguments.
Take the time to write a comprehensive proposal the first time, so that there is no need to mention additional information during the discussion—the proposal itself should ideally contain all the information that PPG members need to come to a conclusion.

### Guidelines for effective discussion

To promote informative and respectful discussion of the proposals, please follow these guidelines when commenting on a proposal:

* Each comment should be substantive and contain new information or new perspectives.
Simple statements of support (or resistance) should be avoided (that’s what the voting is for), as should back-and-forths between individuals.
* Each comment should be limited to statements about the merit of the specific proposal itself, and not about the people involved (individual personalities, whether those making the proposal, or other people involved in the discussions, are not appropriate subjects for discussion).
* All proposals and discussions must abide by the [Code of Conduct](https://pteridogroup.github.io/coc.html).

### Voting

After each proposal has been available for discussion for one month, a vote will be taken.
This vote will only be available to PPG members (people on the PPG mailing list), and will be administered with Google Forms (for those unable to access Google Forms a separate ballot will be sent by email).
Voting will commence on the 1st of the month following the discussion period and close on the last day of that month.
After each vote, the final results will be posted to the proposal, and the vote itself will be archived.
All proposals receiving >⅔ of the votes will be deemed accepted by the PPG community.

### Data sources

Our initial database is based on Michael Hassler's [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list) list (thank you Michael!). Joel Nitta [has written a script](https://github.com/pteridogroup/ppg-import) that converts this list into Darwin Core format. Note that this database includes various changes relative to PPG I made by Michael, but none of these will be considered official until they have been approved via the process outlined [above](#voting).

## Phase 2

### Intended products

The primary product of Phase Two will be a database of species for each of the higher taxa recognized as a result of Phase 1.
In addition, we anticipate one other paper, led by Joel Nitta, describing the bioinformatic tools that we will use in the production of PPG II.

### Process

The details of the process that we will use to achieve this ambitious goal are still being worked out, but the process will revolve heavily around a set of scripts that Joel Nitta has created and which will be available online.
These scripts provide user access to an underlying database of fern taxa.
Basically, every taxon will be an entry in a big text file (A CSV file in [Darwin Core format](https://dwc.tdwg.org/terms/#taxon)), and the data associated with that taxon (such as its parent taxon, its publication details, its rank, etc.) are stored in different fields in that entry.

As with Phase One, the initial database will be courtesy of Michael Hassler and based on his [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list) list, modified as necessary to be consistent with the Phase One higher classification.

Joel’s scripts will allow a user to download portions of the big text file (say, all the species in a given family or genus), edit them, and upon re-upload, will run a series of checks and adjust the rest of the master classification file as necessary (for example, but making sure that synonyms map to an accepted species, etc).

Our rough plan is that PPG members will adopt individual taxa with which they have expertise and vet/refine the species lists for those taxa.
They will then "push" their proposed changes back to the master list, where we’ll apply some sort of vetting (maybe by a geographically representative set of reviewers) to ensure a baseline degree of quality and consistency.

### Versioning

During Phase 2 and beyond, we anticipate frequent, ongoing updates to the taxonomic database.
Rather than release a major new PPG (e.g., PPG 3, PPG 4, etc.) only every few years, semantic versioning will be used to release updates on a more frequent and granular scale.
The details are yet to be worked out, but it will likely be a numbering scheme with three digits (like v1.0.0) where changes below genus could be increments of the last digit (v1.0.1), changes at intermediate levels (genus to order) could be the middle digit (v1.1.0), and dramatic changes (order or higher, or a completely different data format) could be the first digit (v2.0.0).
The database maintainer (currently Joel Nitta) will be in charge of issuing updates.
The PPG community would be notified before any major updates.
Only changes that have been approved by the voting system will be included in updates.

## Code of Conduct

Anybody participating in PPG must agree to abide by the [Code of Conduct](https://pteridogroup.github.io/coc.html). A committee of three volunteers plus a secretary will assess any reported violations of the Code of Conduct, and will have the ability to block violators from the PPG GitHub page.

The Code of Conduct committee for PPG II includes:

* Christopher Krieg ([christopher.p.krieg@gmail.com](mailto:christopher.p.krieg@gmail.com))
* Erin Sigel ([Erin.Sigel@unh.edu](mailto:Erin.Sigel@unh.edu))
* Agustina Yañez ([gugu@macn.gov.ar](mailto:gugu@macn.gov.ar))
* Eric Schuettpelz ([SchuettpelzE@si.edu](mailto:SchuettpelzE@si.edu)), secretary

The full Code of Conduct is available at [https://pteridogroup.github.io/coc.html](https://pteridogroup.github.io/coc.html).

## Coordinating committee

The day-to-day coordination of the PPG II process is organized by:

* Joel Nitta ([joelnitta@gmail.com](mailto:joelnitta@gmail.com))
* Carl Rothfels ([carl.rothfels@usu.edu](mailto:carl.rothfels@usu.edu))
* Harald Schneider ([harald@xtbg.ac.cn](mailto:harald@xtbg.ac.cn))
* Eric Schuettpelz ([schuettpelzE@si.edu](mailto:schuettpelzE@si.edu))

Please contact us with any administrative concerns or comments. If you’re interested in getting more involved, let us know!
