---
title: "Taxonomic treatment (IN PROGRESS)"
toc: true
toc-depth: 5
---

Please note that this is a **work in progress**. The official PPG II has not been released yet. **Please do not cite this** as PPG II until it is officially released.

To see details such as synonyms, please browse the data on [Rhakhis](https://list.worldfloraonline.org/rhakhis) (most up-to-date version) or [World Flora Online (WFO)](https://wfoplantlist.org) (biannual snapshots).
For more information about WFO, see [here](wfo.qmd).

## Class **Lycopodiopsida** Bartl.

#### Order **Isoetales** Prantl

##### Family **Isoetaceae** Dumort.

*Isoetes* L.

#### Order **Lycopodiales** DC. ex Bercht. & J.Presl

##### Family **Lycopodiaceae** P.Beauv. ex Mirb.

###### Subfamily **Huperzioideae** W.H.Wagner & Beitel ex B.Øllg.

*Huperzia* Bernh.

*Phlegmariurus* (Herter) Holub

*Phylloglossum* Kunze

###### Subfamily **Lycopodielloideae** W.H.Wagner & Beitel ex B.Øllg.

*Lateristachys* Holub

*Lycopodiella* Holub

*Palhinhaea* Franco & Vasc.

*Pseudolycopodiella* Holub

###### Subfamily **Lycopodioideae** W.H.Wagner & Beitel ex B.Øllg.

*Austrolycopodium* Holub

*Dendrolycopodium* A.Haines

*Diphasiastrum* Holub

*Diphasium* C.Presl ex Rothm.

*Lycopodiastrum* Holub ex R.D.Dixit

*Lycopodium* L.

*Pseudodiphasium* Holub

*Pseudolycopodium* Holub

*Spinulum* A.Haines

#### Order **Selaginellales** Prantl

##### Family **Selaginellaceae** Willk.

*Selaginella* P.Beauv.

## Class **Polypodiopsida** Cronquist, Takht. & W.Zimm.

### Subclass **Equisetidae** Warm.

#### Order **Equisetales** DC. ex Bercht. & J.Presl

##### Family **Equisetaceae** Michx. ex DC.

*Equisetum* L.

### Subclass **Ophioglossidae** Klinge

#### Order **Ophioglossales** Link

##### Family **Ophioglossaceae** Martinov

###### Subfamily **Botrychioideae** C.Presl

*Botrychium* Sw.

*Botrypus* Rich. ex Michx.

*Japanobotrychium* Masam.

*Sceptridium* Lyon

*Sahashia* Li Bing Zhang & Liang Zhang

###### Subfamily **Helminthostachyoideae** C.Presl

*Helminthostachys* Kaulf.

*Helmithostachys* Kaulf.

###### Subfamily **Mankyuoideae** J.R.Grant & B.Dauphin

*Mankyua* B.Y.Sun, M.H.Kim & C.H.Kim

###### Subfamily **Ophioglossoideae** C.Presl

*Cheiroglossa* C.Presl

*Ophioderma* (Blume) Endl.

*Ophioglossum* L.

#### Order **Psilotales** Prantl

##### Family **Psilotaceae** J.W.Griff. & Henfr.

*Psilotum* Sw.

*Tmesipteris* Bernh.

### Subclass **Marattiidae** Klinge

#### Order **Marattiales** Link

##### Family **Marattiaceae** Kaulf.

*Angiopteris* Hoffm.

*Christensenia* Maxon

*Danaea* Sm.

*Eupodium* J.Sm.

*Marattia* Sw.

*Ptisana* Murdock

### Subclass **Polypodiidae** Cronquist, Takht. & W.Zimm.

#### Order **Cyatheales** A.B.Frank

##### Family **Cibotiaceae** Korall

*Cibotium* Kaulf.

##### Family **Culcitaceae** Pic.Serm.

*Culcita* C.Presl

##### Family **Cyatheaceae** Kaulf.

*Alsophila* R.Br.

*Cyathea* Sm.

*Gymnosphaera* Blume

*Sphaeropteris* Bernh.

##### Family **Dicksoniaceae** M.R.Schomb.

*Calochlaena* (Maxon) M.D.Turner & R.A.White

*Dicksonia* L’Hér.

*Lophosoria* C.Presl

##### Family **Loxsomataceae** C.Presl

*Loxsoma* R.Br. ex A.Cunn.

*Loxsomopsis* Christ

##### Family **Metaxyaceae** Pic.Serm.

*Metaxya* C.Presl

##### Family **Plagiogyriaceae** Bower

*Plagiogyria* (Kunze) Mett.

##### Family **Thyrsopteridaceae** C.Presl

*Thyrsopteris* Kunze

#### Order **Gleicheniales** Link

##### Family **Dipteridaceae** Seward & E.Dale

*Cheiropleuria* C.Presl

*Dipteris* Reinw.

##### Family **Gleicheniaceae** C.Presl

*Dicranopteris* Bernh.

*Diplopterygium* (Diels) Nakai

*Gleichenella* Ching

*Gleichenia* Sm.

*Sticherus* C.Presl

*Stromatopteris* Mett.

*Rouxopteris* Hong M.Liu

##### Family **Matoniaceae** C.Presl

*Matonia* R.Br. ex Wall.

*Phanerosorus* Copel.

#### Order **Hymenophyllales** A.B.Frank

##### Family **Hymenophyllaceae** Mart.

###### Subfamily **Hymenophylloideae** Burnett

*Hymenophyllum* Sm.

###### Subfamily **Trichomanoideae** C.Presl

*Abrodictyum* C.Presl

*Callistopteris* Copel.

*Cephalomanes* C.Presl

*Crepidomanes* C.Presl

*Didymoglossum* Desv.

*Polyphlebium* Copel.

*Trichomanes* L.

*Vandenboschia* Copel.

#### Order **Osmundales** Link

##### Family **Osmundaceae** Martinov

*Leptopteris* C.Presl

*Osmunda* L.

*Osmundastrum* C.Presl

*Plenasium* C.Presl

*Todea* Willd.

*Claytosmunda* (Y.Yatabe, N.Murak. & K.Iwats.) Metzgar & Rouhan

*× Osmunasium* Hong M.Liu, Schuettp. & H.Schneid.

*× Osmunimunda* Xia Wan & Li Bing Zhang

#### Order **Polypodiales** Link

##### Family **Pteridryaceae** Li Bing Zhang, X.M.Zhou, Liang Zhang & N.T.Lu

*Polydictyum* C.Presl

*Pteridrys* Christensen & Ching

*Malaifilix* Li Bing Zhang & Schuettp.

*Draconopteris* Li Bing Zhang & Liang Zhang

##### Family **Aspleniaceae** Newman

*Asplenium* L.

*Hymenasplenium* Hayata

##### Family **Athyriaceae** Alston

*Anisocampium* C.Presl

*Athyrium* Roth

*× Cornoathyrium* Nakaike

*Cornopteris* Nakai

*Deparia* Hook. & Grev.

*Diplazium* Sw.

*Pseudathyrium* Newm.

*Ephemeropteris* R.C.Moran & Sundue

*× Apseudathyrium* Xia Wan & Li Bing Zhang

##### Family **Blechnaceae** Newman

###### Subfamily **Blechnoideae** Hook.

*Blechnidium* Moore

*Blechnopsis* C.Presl

*Blechnum* L.

*Brainea* J.Sm.

*Diploblechnum* Hayata

*Doodia* R.Br.

*Lomaria* Willd.

*Lomaridium* C.Presl

*Parablechnum* C.Presl

*Sadleria* Kaulf.

*Spicantopsis* Nakai

*Struthiopteris* Scop.

*Austroblechnum* Gasper & V.A.O.Dittrich

*Cleistoblechnum* Gasper & Salino

*Cranfillia* Gasper & V.A.O.Dittrich

*Icarus* Gasper & Salino

*Lomariocycas* (J.Sm.) Gasper & V.A.O.Dittrich

*Neoblechnum* Gasper & V.A.O.Dittrich

*Oceaniopteris* Gasper & Salino

###### Subfamily **Stenochlaenoideae** J.P.Roux

*Salpichlaena* J.Sm.

*Stenochlaena* J.Sm.

*Telmatoblechnum* Perrie, D.J.Ohlsen & Brownsey

###### Subfamily **Woodwardioideae** Gasper, V.A.O.Dittrich & Salino

*Anchistea* C.Presl

*Lorinseria* C.Presl

*Woodwardia* Sm.

##### Family **Cystodiaceae** J.R.Croft

*Cystodium* J.Sm.

##### Family **Cystopteridaceae** (Payer) Shmakov

*Acystopteris* Nakai

*× Cystocarpium* Fraser-Jenk.

*Cystopteris* Bernh.

*Gymnocarpium* Newman

##### Family **Davalliaceae** M.R.Schomb. ex A.B.Frank

*Davallia* Sm.

##### Family **Dennstaedtiaceae** Lotsy

###### Subfamily **Dennstaedtioideae** Pic.Serm.

*Dennstaedtia* T.Moore

*Microlepia* C.Presl

*Sitobolium* Desv.

*Mucura* L.A.Triana & Sundue

###### Subfamily **Hypolepidoideae** Lovis

*Blotiella* R.M.Tryon

*Histiopteris* (J.Agardh) J.Sm.

*Hypolepis* Bernh.

*Paesia* A.St.-Hil.

*Pteridium* Gleditsch; Scopoli

*Hiya* H.Shang

###### Subfamily **Monachosoroideae** Crabbe, Jermy & Mickel

*Monachosorum* Kunze

##### Family **Diplaziopsidaceae** X.C.Zhang & Christenh.

*Diplaziopsis* C.Chr.

##### Family **Dryopteridaceae** Herter

###### Subfamily **Polystichopsidoideae** Z.Y.Zuo

*Trichoneuron* Ching

*Polystichopsis* (J.Sm.) C.Chr.

###### Subfamily **Pleocnemioideae** Z.Y.Zuo

*Pleocnemia* C.Presl

###### Subfamily **Lastreopsidoideae** Z.Y.Zuo

*Lastreopsis* Ching

*Megalastrum* Holttum

*Parapolystichum* (Keyserl.) Ching

*Rumohra* Raddi

###### Subfamily **Ctenitidoideae** Z.Y.Zuo & Jin Mei Lu

*Ctenitis* (C.Chr.) C.Chr.

###### Subfamily **Dryopteridoideae** B.K.Nayar

*Arachniodes* Blume

*Cyrtomium* C.Presl

*Dryopteris* Adans.

*× Dryostichum* W.H.Wagner

*Phanerophlebia* C.Presl

*Polystichum* Roth

*Stigmatopteris* C.Chr.

*Pseudarachniodes* Z.Y.Zuo & Rouhan

###### Subfamily **Polybotryoideae** Hong M.Liu & X.C.Zhang

*Atalopteris* Maxon & C.Chr.

*Cyclodium* C.Presl

*Maxonia* C.Chr.

*Olfersia* Raddi

*Polybotrya* Humb. & Bonpl. ex Willd.

*× Cyclobotrya* Engels & Canestraro

###### Subfamily **Elaphoglossoideae** Crabbe, Jermy & Mickel

*Bolbitis* Schott

*Elaphoglossum* Schott ex J.Sm.

*Lomagramma* J.Sm.

*Mickelia* R.C.Moran, Labiak & Sundue

*Teratophyllum* Mett. ex Kuhn

##### Family **Hypodematiaceae** Ching

*Hypodematium* Kunze

*Leucostegia* C.Presl

##### Family **Lindsaeaceae** M.R.Schomb.

*Lindsaea* Dryand. ex Sm.

*× Lindsaeosoria* W.H.Wagner

*Nesolindsaea* Lehtonen & Christenh.

*Odontosoria* (C.Presl) Fée

*Osmolindsaea* (K.U.Kramer) Lehtonen & Christenh.

*Sphenomeris* Maxon

*Tapeinidium* (Presl) C.Chr.

*Xyropteris* K.U.Kramer

##### Family **Lomariopsidaceae** Alston

*Cyclopeltis* J.Sm.

*Dracoglossum* Christenh.

*Dryopolystichum* Copel.

*Lomariopsis* Fée

##### Family **Lonchitidaceae** A.R.Sm. & M.Kessler

*Lonchitis* L.

##### Family **Nephrolepidaceae** Pic.Serm.

*Nephrolepis* Schott

##### Family **Oleandraceae** Ching ex Pic.Serm.

*Oleandra* Cav.

##### Family **Onocleaceae** Pic.Serm.

*Matteuccia* Tod.

*Onoclea* L.

*Onocleopsis* F.Ballard

*Pentarhizidium* Hayata

##### Family **Polypodiaceae** J.Presl & C.Presl

###### Subfamily **Adetogrammoideae** X.C.Zhang & R.Wei

*Adetogramma* T.E.Almeida

###### Subfamily **Campyloneuroideae** X.C.Zhang & R.Wei

*Campyloneurum* C.Presl

*Microgramma* C.Presl

*Niphidium* J.Sm.

###### Subfamily **Serpocauloideae** X.C.Zhang & R.Wei

*Serpocaulon* A.R.Sm.

###### Subfamily **Grammitidoideae** Parris & Sundue

*Acrosorus* Copel.

*Adenophorus* Gaudich.

*Alansmia* M.Kessler, Moguel, Sundue & Labiak

*Ascogrammitis* Sundue

*Calymmodon* C.Presl

*Ceradenia* L.E.Bishop

*Chrysogrammitis* Parris

*Cochlidium* Kaulf.

*Ctenopterella* Parris

*Dasygrammitis* Parris

*Enterosora* Baker

*Grammitis* Sw.

*Lellingeria* A.R.Sm. & R.C.Moran

*Leucotrichum* Labiak

*Lomaphlebia* J.Sm.

*Luisma* M.T.Murillo & A.R.Sm.

*Melpomene* A.R.Sm. & R.C.Moran

*Micropolypodium* Hayata

*Moranopteris* R.Y.Hirai & J.Prado

*Oreogrammitis* Copel.

*Prosaptia* C.Presl

*Scleroglossum* Alderw.

*Stenogrammitis* Labiak

*Terpsichore* A.R.Sm.

*Tomophyllum* (E.Fourn.) Parris

*Xiphopterella* Parris

*Archigrammitis* Parris

*Galactodenia* Dundue & Labiak

*Mycopteris* Sundue

*Notogrammitis* Parris

*Parrisia* Shalisko & Sundue

*Calligrammitis* Parris, Sundue, Li Bing Zhang, X.M.Zhou & Ralf Knapp

*Devolia* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Ralf Knapp

*Glabrigrammitis* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Parris

*Aenigmatogrammitis* Parris

*Boonkerdia* Li Bing Zhang, Pollawatn, X.M.Zhou & Liang Zhang

*Grammitastrum* (E.Fourn.) Parris, Sundue, Li Bing Zhang & X.M.Zhou

*Howeogrammitis* Parris, Sundue, Li Bing Zhang & X.M.Zhou

*Nanogrammitis* Parris, Li Bing Zhang, X.M.Zhou & Liang Zhang

*Oxygrammitis* Parris & Sundue

*Rouhania* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Liang Zhang

*Thalassogrammitis* Parris, Sundue, Li Bing Zhang & X.M.Zhou

###### Subfamily **Loxogrammoideae** H.Schneid.

*Dictymia* J.Sm.

*Loxogramme* (Blume) C.Presl

###### Subfamily **Microsoroideae** B.K.Nayar

####### Tribe **Goniophlebieae** C.C.Chen & H.Schneid.

*Goniophlebium* (Blume) C.Presl

####### Tribe **Lecanoptereae** C.C.Chen & H.Schneid.

*Lecanopteris* Reinw.

*Bosmania* Testo

####### Tribe **Thylacoptereae** C.C.Chen & H.Schneid.

*Thylacopteris* Kunze ex J.Sm.

####### Tribe **Lepisoreae** Ching ex E.Hennipman, P.Veldhoen & K.U.Kramer

*Lepisorus* (J.Sm.) Ching

####### Tribe **Microsoreae** V.N.Tu

*Leptochilus* Kaulf.

*Microsorum* Link

*Podosorus* Holttum

###### Subfamily **Platycerioideae** B.K.Nayar

*Platycerium* Desv.

*Pyrrosia* Mirb.

*Hovenkampia* Li Bing Zhang & X.M.Zhou

###### Subfamily **Polypodioideae** B.K.Nayar

*Pecluma* M.G.Price

*Phlebodium* (R.Br.) J.Sm.

*Pleopeltis* Humb. & Bonpl. ex Willd.

*Pleurosoriopsis* Fomin

*Polypodium* L.

*× Phlebosia* Viane & Pompe

###### Subfamily **Crypsinoideae** B.K.Nayar

*Drynaria* (Bory) J.Sm.

*Selliguea* Bory

*Synammia* C.Presl

##### Family **Pteridaceae** E.D.M.Kirchn.

###### Subfamily **Pteridoideae** Link

*Taenitis* Willd. ex Spreng.

*Actiniopteris* Link

*Anogramma* Link

*Austrogramme* E.Fourn.

*Cerosora* (Baker) Domin

*Cosentinia* Tod.

*Jamesonia* Hook. & Grev.

*Onychium* Kaulf.

*Pityrogramma* Link

*Pteris* L.

*Pterozonium* Fée

*Syngramma* J.Sm.

*Gastoniella* Li Bing Zhang & Liang Zhang

*Tryonia* Schuettp., J.Prado & A.T.Cochran

###### Subfamily **Adiantoideae** Horvat

*Adiantum* L.

###### Subfamily **Cheilanthoideae** Horvat

*Adiantopsis* Fée

*Aleuritopteris* Fée

*Argyrochosma* (J.Sm.) Windham

*Aspidotis* (Nutt. ex Hook.) Copel.

*Astrolepis* D.M.Benham & Windham

*Bommeria* E.Fourn.

*Calciphilopteris* Yesilyurt & H.Schneid.

*Cheilanthes* Sw.

*Cheiloplecton* Fée

*Doryopteris* J.Sm.

*Hemionitis* L.

*Mildella* Trevis.

*Myriopteris* Fée

*Notholaena* R.Br.

*Oeosporangium* Vis.

*Ormopteris* J.Sm. ex J.Sm.

*Paragymnopteris* K.H.Shing

*Parahemionitis* Panigrahi

*Pellaea* Link

*Pentagramma* Yatsk., Windham & E.Wollenw.

*Trachypteris* André

*Gaga* Pryer, Fay W.Li & Windham

*Lytoneuron* (Klotzsch) Yesilyurt

*Baja* Windham & L.O.George

*Mineirella* Ponce & Scataglini

###### Subfamily **Cryptogrammoideae** S.Linds.

*Coniogramme* Fée

*Cryptogramma* R.Br.

*Llavea* Lag.

###### Subfamily **Parkerioideae** Burnett

*Acrostichum* L.

*Ceratopteris* Brongn.

###### Subfamily **Vittarioideae** Crabbe, Jermy & Mickel

*Ananthacorus* Underw. & Maxon

*Antrophyum* Kaulf.

*Haplopteris* C.Presl

*Hecistopteris* J.Sm.

*Polytaenium* Desv.

*Radiovittaria* (Benedict) E.H.Crane

*Rheopteris* Alston

*Scoliosorus* T.Moore

*Vaginularia* Fée

*Vittaria* Sm.

*Antrophyopsis* (Benedict) Schuettp.

##### Family **Rhachidosoraceae** X.C.Zhang

*Rhachidosorus* Ching

##### Family **Saccolomataceae** Doweld

*Saccoloma* Kaulf.

##### Family **Tectariaceae** Panigrahi

*Hypoderris* R.Br. ex Hook.

*Tectaria* Cav.

*Triplophyllum* Holttum

##### Family **Thelypteridaceae** Ching ex Pic.Serm.

###### Subfamily **Thelypteroideae** C.F.Reed

*Abacopteris* Fée

*Amauropelta* Kunze

*Amblovenatum* J.P.Roux

*Ampelopteris* Kunze

*Chingia* Holttum

*× Chrinephrium* Nakaike

*× Chrismatopteris* Quansah & D.S.Edwards

*Christella* H.Lév.

*Coryphopteris* Holttum

*Cyclogramma* Tagawa

*Cyclosorus* Link

*Glaphyropteridopsis* Ching

*Goniopteris* C.Presl

*Leptogramma* J.Sm.

*Meniscium* Schreb.

*Menisorus* Alston

*Mesophlebion* Holttum

*Mesopteris* Ching

*Metathelypteris* (H.Ito) Ching

*Oreopteris* Holub

*Plesioneuron* (Holttum) Holttum

*Pneumatopteris* Nakai

*Pronephrium* C.Presl

*Pseudocyclosorus* Ching

*Sphaerostephanos* J.Sm.

*Stegnogramma* Blume

*Steiropteris* (C.Chr.) Pic.Serm.

*Thelypteris* Schmidel

*Trigonospora* Holttum

*Pelazoneuron* (Holttum) A.R.Sm. & S.E.Fawc.

*Grypothrix* (Holttum) S.E.Fawc. & A.R.Sm.

*Hoiokula* S.E.Fawc. & A.R.Sm.

*Menisciopsis* (Holttum) S.E.Fawc. & A.R.Sm.

*Pakau* S.E.Fawc. & A.R.Sm.

*Reholttumia* S.E.Fawc. & A.R.Sm.

*Strophocaulon* S.E.Fawc. & A.R.Sm.

*× Glaphyrocyclosorus* Xia Wan & Li Bing Zhang

*× Abacopterella* T.E.Almeida & A.R.Field

*× Christelliopsis* Miles K.Thomas

###### Subfamily **Phegopteridoideae** Salino, A.R.Sm. & T.E.Almeida

*Macrothelypteris* (H.Ito) Ching

*Phegopteris* (C.Presl) Fée

*Pseudophegopteris* Ching

###### Subfamily **Thelypteridoideae** C.F.Reed

##### Family **Woodsiaceae** Herter

*Woodsia* R.Br.

##### Family **Desmophlebiaceae** Mynssen, A.Vasco, Sylvestre, R.C.Moran & Rouhan

*Desmophlebium* Mynssen, A.Vasco, Sylvestre, R.C.Moran & Rouhan

##### Family **Didymochlaenaceae** Ching ex Li Bing Zhang & Liang Zhang

*Didymochlaena* Desv.

##### Family **Hemidictyaceae** Christenh. & H.Schneid.

*Hemidictyum* C.Presl

##### Family **Arthropteridaceae** Hong M.Liu, Hovenkamp & H.Schneid.

*Arthropteris* J.Sm.

#### Order **Salviniales** Link

##### Family **Marsileaceae** Mirb.

*Marsilea* L.

*Pilularia* L.

*Regnellidium* Lindm.

##### Family **Salviniaceae** Martinov

*Azolla* Lam.

*Salvinia* Ség.

#### Order **Schizaeales** Schimp.

##### Family **Anemiaceae** Link

*Anemia* Sw.

##### Family **Lygodiaceae** M.Roem.

*Lygodium* Sw.

##### Family **Schizaeaceae** Kaulf.

*Microschizaea* C.F.Reed

*Schizaea* Sm.

*Actinostachys* R.Br. ex Hook. & Baker
