---
title: "World Ferns Taxonomy"
author: "PPG Coordinating Committee"
toc: true
date: "2024-09-09"
---

The [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list) v24.8 (August 2024) taxonomy at the genus level and higher is provided as a point of reference for curating PPG II (thanks to Michael Hassler).

## Notes {.appendix}

Generated by `ppg-import` commit [a9ba0db](https://github.com/pteridogroup/ppg-import/commit/a9ba0dbd5087b94dc23e4b9883db9abf0e5a101c)

## Lycopodiales DC. ex Bercht. & J. Presl -- Prir. Rostlin: 272 (1820)

= *Lycopodiobiotina* Doweld -- Tent. Syst. Pl. Vasc.: ii (2001)  
= Lycopodiidae Bek. -- Kurs Bot. 1: 115 (1862)  
= Lycopodiophyta D. H. Scott -- Stud. Foss. Pl.: 13, 500, 501 (1900)  
= Lycopodiophytina Tippo ex Reveal -- Phytologia 79: 70 (1996)  
= Lycopodiopsida Bartl. -- Ord. Nat. Pl.: 14, 19 (1830)

### Lycopodiaceae P.Beauv. ex Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 4: 293. 1802 \[21 Nov 1802\] , as ‘Lycopodia’

17 genera, ca. 470 spp. Phylogeny: Chen et al. (2021).  
= Huperziaceae Rothm. -- Feddes Repert. Spec. Nov. Regni Veg. 66: 236, nom. nov. 1962  
= Lycopodiellaceae Val.N.Tikhom. -- Novosti Sist. Vyssh. Rast. 49: 149. 2018  
= Phylloglossaceae Kunze -- Bot. Zeitung (Berlin) 1(42): 721. 1843 \[20 Oct 1843\]  
= Urostachyaceae Rothm. -- Feddes Repert. Spec. Nov. Regni Veg. 54: 58. 1944

#### Huperzioideae W.H.Wagner & Beitel ex B.Øllg. -- Nordic J. Bot. 33(2): 195. 2014 \[21 Oct 2014\] \[epublished\]

###### *Huperzia* Bernh. -- J. Bot. (Schrader) 1800(2): 126. 1801 \[Oct-Dec 1801\]

Distribution: Probably only 25 spp. temperate, alpine and arctic, tropical Asian mountains. Many remaining species still need transfer into other split genera.  
= *Plananthus* P.Beauv. ex Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 476; 4: 310. 1802 \[21 Nov 1802\]  
= *Selago* Boehm. -- Ludwig, Def. Gen. Pl., ed. Boehmer 484 (1760) (non L. 1753, nec Browne 1756, nec Hill (1757) nom. illeg.)  
= *Selago* Hill -- Brit. Herb. 533 (1757) (non L. 1753, nec Browne 1756, nom. inval.)  
= *Selago* Schur -- Enum. pl. Transsilv. 825. 1866 (non L. 1753, nec Browne 1756, nec Hill (1757))  
= *Urostachys* (Herter) Herter -- Beih. Bot. Centralbl., Abt. 2. 39: 249. 1922

###### *Phlegmariurus* (Herter) Holub -- Preslia 36(1): 17, 21. 1964 \[ante 12 Mar 1964\]

Distribution: Worldwide tropical. There is a clear distinction between a neotropical clade and an Old World clade but this is not sufficient to split two genera (Chen et al. 2021).

###### *Phylloglossum* Kunze -- Bot. Zeitung (Berlin) 1 1843 \[20 Oct 1843\]

Distribution: Australia, New Zealand

#### Lycopodiastroideae Li Bing Zhang & X.M.Zhou -- Indian Fern J. 38(1-2): 134. 2021 \[Dec 2021\]

###### *Lycopodiastrum* Holub ex R.D.Dixit -- J. Bombay Nat. Hist. Soc. 77(3): 540. 1981 \[1980 publ. 1981\]

Distribution: Trop. Asia, S-China

#### Lycopodielloideae W.H.Wagner & Beitel ex B.Øllg. -- Nordic J. Bot. 33(2): 195. 2014 \[21 Oct 2014\] \[epublished\]

###### *Brownseya* Li Bing Zhang, L.D.Sheph., D.K.Chen, X.M.Zhou & H.He -- Taxon 71(1): 41. 2022 \[2022 publ. 6 Nov 2021\] \[epublished\]

Distribution: Australia, Papuasia, New Zealand, New Caledonia

###### *Lateristachys* Holub -- Folia Geobot. Phytotax. 18(4): 440. 1983

Distribution: Philippines, Australia, New Zealand

###### *Lycopodiella* Holub -- Preslia 36: 20, (22). 1964 \[Mar 1964\]

Distribution: Holarctic and tropical America

###### *Palhinhaea* Franco & Vasc. -- Bol. Soc. Brot. Ser. 2, 41: 24. 1967

Distribution: Tropics and subtropics. Rank and status somewhat questionable, might also be treated as subgenus of Lycopodiella.  
= *Lepidotis* P.Beauv. ex Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 477; 4: 311. 1802 \[21 Nov 1802\]

###### *Pseudolycopodiella* Holub -- Folia Geobot. Phytotax. 18(4): 441. 1983 \[12 Dec 1983\]

Distribution: Widely scattered worldwide. Rank and status somewhat questionable, might also be treated as subgenus of Lycopodiella.

#### Lycopodioideae Eaton -- Man. Bot. (A. Eaton), ed. 6. 2: 81. 1833 \[22 May-3 Jun 1833\] , as ‘suborder Lycopodiaceae’

= Lycopodieae Duby -- Bot. Gall. 1: 543 (1828)

###### *Austrolycopodium* Holub -- Folia Geobot. Phytotax. 26(1): 91. 1991

Distribution: Temperate southern hemisphere, mostly circumantarctic, 1 to tropical Africa

###### *Dendrolycopodium* A.Haines -- Fam. Huperziac. Lycopodiac. New England 84. 2003 \[Feb 2003\]

Distribution: North America, E-Asia. Frequently re-included in Lycopodium s. lat. but accepted by PPG-I

###### *Diphasiastrum* Holub -- Preslia 47: 104. 1975

Distribution: Temperate northern hemisphere, 1 South Africa and Madagascar, 2 to tropical America

###### *Diphasium* C.Presl ex Rothm. -- Feddes Repert. Spec. Nov. Regni Veg. 54: 64. 1944

Distribution: Gondwanan. Frequently re-included in Diphasiastrum s. lat. but accepted by PPG-I

###### *Lycopodium* L. -- Sp. Pl. 2: 1100. 1753 \[1 May 1753\]

Distribution: Mainly temperate and subarctic regions  
= *Clopodium* Raf. -- Anal. nat. 205 (1815) (nom. inval.)  
= *Oxynemum* Raf. -- Amer. Monthly Mag. & Crit. Rev. 2: 44 (1817)

###### *Pseudodiphasium* Holub -- Folia Geobot. Phytotax. 18(4): 440. 1983

Distribution: Trop. Asia, Australia, New Zealand. Frequently re-included in Lycopodium s. lat. but accepted by PPG-I

###### *Pseudolycopodium* Holub -- Folia Geobot. Phytotax. 18(4): 441. 1983

Distribution: Australia, New Zealand, New Caledonia. Frequently re-included in Lycopodium s. lat. but accepted by PPG-I

###### *Spinulum* A.Haines -- Fam. Huperziac. Lycopodiac. New England 85. 2003 \[Feb 2003\]

Distribution: Holarctic.

## Isoetales Prantl -- Lehrb. Bot.: 116 (1874)

= Isoeteae Barlinge -- Ord. Nat. Plant. 16 (1830)  
= *Isoetariae* Koidz. -- Acta Phytotax. Geobot. 7: 11 (1938)  
= Isoetidae Reveal -- Phytologia 79: 70 (1996)  
= Isoetophyta Doweld -- Tent. Syst. Pl. Vasc.: iii (2001)  
= Isoetophytina Doweld -- Tent. Syst. Pl. Vasc.: iii (2001)  
= Isoetopsida Rolle -- Encykl. Naturwiss. 2: 264 (1885)

### Isoetaceae Dumort. -- Anal. Fam. Pl. : 67. 1829

1 genus, ca. 190 spp.  
= Bothriaceae Dulac -- Fl. Dépt. Hautes-Pyrenees 38 (1867)  
= Isoetoideae A. Gray -- Bot. Text, ed. 5: 502 (1858)  
= Isoetineae Engl. -- Syllabus, ed. 2: 65 (1898)

###### *Isoetes* Weigel -- Observ. Bot. (Weigel) 36, t. 2. f. 7. 1772

Distribution: Worldwide. Many undescribed species remain (for China see Gu et al. 2023). Latest checklist: Troia et al. (2016). Taxonomy especially in North America and in the Mediterranean is quite disputed.  
= *Calamaria* Boehm. -- Def. Gen. Pl., ed. 3. 500. 1760  
= *Cephaloceraton* Gennari -- Comment. Soc. Crittog. Ital. 1: 111. 1862  
= *Isoetella* Gennari -- Comment. Soc. Crittog. Ital. 1: 114. 1862  
= *Sivetes* Raf. -- Med. Repos. 11. 5: 358 (1808)  
= *Stylites* Amstutz -- Ann. Missouri Bot. Gard. 44: 121. 1957 \[22 Mar 1957\]  
= *Subularia* Forssk. -- Fl. Aegypt.-Arab. 117 (1775). \[1 Oct 1775\]

## Selaginellales Prantl -- Lehrb. Bot.: 116 (1874)

= Heterosporeae Prantl -- Lehrb. Bot., 116 (1874)  
= Selaginelleae Willk. -- Anleit. Stud. Bot. 2: 163 (1854)  
= *Heterosporae* Asch. -- Syn. 1: 149 (1896)  
= *Selagines* Batsch -- Syn. Univ. Anal. Gen. Plant., 381 (1794)  
= Selaginellidae Knobl. -- J. E. B. Warming, Handb. Syst. Bot. (ed. E. F. Knoblauch): 157 (1890)  
= Selaginellidae Pic. Serm. -- Pteridophyta, Vistas in Botany 456 (1961) (Subclass)  
= Selaginellineae Engl. -- Syllabus Pfl., 2. Aufl.: 64 (1898)  
= Selaginellophytina Doweld -- Tent. Syst. Pl. Vasc.: iv (2001)  
= Selaginellopsida A. B. Frank -- J. Leunis, Syn. Pflanzenk., ed. 2, 3: 1238 (1874)

### Selaginellaceae Willk. -- Anleit. Stud. Bot. 2: 163. 1854 \[Feb 1854\]

1-19 genera depending on genus concept, ca. 750 spp. The family has recently been split extensively by X.-M. Zhou & Li-Bing Zhang (2023).

#### Boreoselaginelloideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 645. 2023 \[20 Jul 2023\] \[epublished\]

###### *Boreoselaginella* (Warb.) Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 646. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Himalayas to E-Asia and Siberia

#### Gymnogynoideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 646. 2023 \[20 Jul 2023\] \[epublished\]

###### *Afroselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 648. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Tropical Africa

###### *Bryodesma* Soják -- Preslia 64(2): 154. 1993 \[1992 publ. 1993\]

Distribution: Almost cosmopolitan, mostly in temperate areas, many in USA

###### *Ericetorum* (Jermy) Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 653. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Australia, Madagascar, South Africa (1), New Guinea (1)

###### *Gymnogynum* P.Beauv. -- Mag. Encycl. 9(5): 480. 1804

Distribution: Mostly tropical America, 1 tropical Africa, 1 Asia

###### *Lepidoselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 656. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: SW-USA to Costa Rica, mostly Mexico

###### *Megaloselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 656. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Tropical America, trop. Africa

#### Lycopodioidoideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 661. 2023 \[20 Jul 2023\] \[epublished\]

###### *Didiclis* P.Beauv. ex Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 477. 1802 \[21 Nov 1802\] ; et in 4: 314

Distribution: Tropical Old World and Pacific, only 1 in Central America

###### *Hypopterygiopsis* Sakurai -- Bot. Mag. (Tokyo) 57: 255. 1943

Distribution: tropical Old World including Pacific, north to S-China

###### *Lycopodioides* Boehm. -- Def. Gen. Pl. ed. Boehmer 485 (1760)

Distribution: Europe and temperate Asia, 1 in Java, 1 tropical Africa  
= *Lycopodioides* Kuntze -- Revis. Gen. Pl. 2: 824. 1891 \[5 Nov 1891\]  
= *Trispermium* Hill -- Gener. Nat. Hist., ed. 2 2(Hist. Pl.): 112. 1773

###### *Valdespinoa* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 672. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: NW-USA

#### Pulvinielloideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 659. 2023 \[20 Jul 2023\] \[epublished\]

###### *Pulviniella* (Li Bing Zhang & X.M.Zhou) Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 659. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: scattered almost cosmopolitan, several in China

#### Selaginelloideae Milde -- Fil. Eur. & Atl.: 5, 258 (1867)

= Selaginelloideae Li Bing Zhang & X. M. Zhou -- Plant Diversity 45: 672 (2023), nom. superfl.

###### *Chuselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 673. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Tropical Asia and Pacific, few S-China, 1 tropical Africa

###### *Kungiselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 676. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Tropical Asia to S-China

###### *Selaginella* P. Beauv. -- Magasin Encycl. 9: 478 (1804) et Prodr. Aethéogam. 101 (1805), s. str.

Distribution: New World, mostly tropical America, only very few tropical Africa. The genus definition relies on a new lectotype for Selaginella by Zhou & Zhang (2023) who did this in order to avoid recombination of this big genus. Whether this will stand, remains to be seen.  
= *Selago* P. Browne -- Civ. Nat. Hist. Jamaica 82 (1756) (nom. illeg., non Selago L. (1753))  
= *Stachygynandrum* P. Beauv. -- Mag. Encycl. 9: 482 (1805)  
= *Stachygynandrum* P. Beauv. ex Mirb. -- Hist. Nat. Veg. (Lam. & Mirb.) 3: 477 (1803)

###### *Selaginella* s. l. -- NA

Species which are of unconfirmed status, do obviously not belong to Selaginella s. str. and/or have not yet been reassigned during the split of the genus by Zhou & Zhang (2023)

#### Selaginoidoideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 644. 2023 \[20 Jul 2023\] \[epublished\]

###### *Selaginoides* Ség. -- Pl. Veron. 3: 51. 1754

Distribution: Holarctic (1) and Hawaii (1). This includes the previous type of Selaginella. Whether the approach of Zhou & Zhang (2023) to newly lectotypify Selaginella to avoid mass recombinations will be accepted, is not yet decided.  
= *Polycocca* Hill -- Gener. Nat. Hist., ed. 2 2(Hist. Pl.): 116. 1773

#### Sinoselaginelloideae Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 656. 2023 \[20 Jul 2023\] \[epublished\]

###### *Austroselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 657. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Australia

###### *Korallia* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 658. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Indian Ocean (Madagascar, Mascarenes, Seychelles, Comores)

###### *Sinoselaginella* Li Bing Zhang & X.M.Zhou -- Pl. Diversity 45(6): 658. 2023 \[20 Jul 2023\] \[epublished\]

Distribution: Himalayas, China, 1 Ethiopia and Arabia

## Equisetales DC. ex Bercht. & J. Presl -- Prir. Rostlin. 1: 271 (1820)

= Equisetoideae Eaton -- Man. Bot. (A. Eaton), ed. 6. 2: 80. 1833 \[22 May-3 Jun 1833\] , as ‘suborder Equisetaceae’  
= Equisetidae Warm. -- Osnov. Bot.: 221 (1883)  
= Equisetineae Rabenh. -- Deutschl. Krypt.-Fl. 2: xvi, 327 (1849)  
= Equisetophyta D. H. Scott -- Stud. Foss. Pl.: 13, 489, 492, 493 (1900)  
= Equisetophytina Reveal -- Phytologia 79: 70 (1996)  
= Equisetopsida C. Agardh -- Classes Pl.: 7 (1825)

### Equisetaceae Rich. ex DC. -- Fl. Franç. (Lamarck) ed. 3, 2: 49. 1805 \[17 Sep 1805\]

1 genus, 16 spp.

###### *Equisetum* L. -- Sp. Pl. 2: 1061. 1753 \[1 May 1753\]

Distribution: Nearly cosmopolitan. Several hybrids are now stabilized and may also be treated as valid species.  
= *Allostelites* Börner -- Fl. Deut. Volk 59. 1912  
= *Hippochaete* Milde -- Bot. Zeitung (Berlin) 23: 297. 1865  
= *Presla* Dulac -- Fl. Hautes-Pyrénées 25. 1867 , nom. superfl.

## Psilotales Prantl -- Lehrb. Bot., ed. 5: 183 (1884) (Psilotaceae)

= Psiloteae Willk. -- Anleit. Stud. Bot. 2: 163 (1854)  
= Psilotidae Reveal -- Phytologia 79: 70 (1996)  
= Psilotineae Engl. -- Syllabus, ed. 2: 64 (1898)  
= Psilotophyta Heintze -- Cormofyt. Fylog.: 22 (1927)  
= Psilotophytina Tippo ex Reveal -- Phytologia 79: 70 (1996)  
= Psilotopsida D. H. Scott -- Stud. Foss. Pl., ed. 2: 616, 631, 632 (1909)

### Psilotaceae J.W.Griff. & Henfr. -- Microgr. Dict. 540. 1855 \[1 Nov 1855\] , as ‘Psiloteae’

2 genera, 18 spp.  
= Tmesipteridaceae Nakai -- Ord. Fam. Trib. Gen. Sect. … nov. ed. 206. 1943

###### *Psilotum* Sw. -- J. Bot. (Schrader) 1800(2): 8, 109. 1801 \[Oct-Dec 1801\]

Distribution: Pantropic to warm-temperate, north to SE-USA, extreme SW-Europe, C-Japan and S-Korea. New taxonomy fide Tejero-Díez et al. 2024.  
= *Bernhardia* Willd. ex Bernh. -- Abh. Kurfürstl.-Mainz. Akad. Nützl. Wiss. Erfurt 2: 11. 1802 ; et in J. Bot. (Schrader) 1800(2): 132 (1801)  
= *Hoffmannia* Willd. -- Bot. Mag. (Römer & Usteri) 2(6): 15, 17. 1789  
= *Tristeca* P.Beauv. ex Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 478. 1802 \[21 Nov 1802\] ; & 4: 315. 21 Nov 1802.

###### *Tmesipteris* Bernh. -- J. Bot. (Schrader) 1800(2): 131. 1801 \[Oct-Dec 1801\]

Distribution: SE-Asia, Australasia, New Zealand (7), New Caledonia, New Guinea, Philippines, east to Marquesas Isl., Tahiti

## Ophioglossales Link -- Hort. Berol. 2: 151 (1833) (Ophioglossaceae)

= Ophioglossidae Klinge -- Fl. Est-Liv-Churland 1: 94 (1882)  
= Ophioglossophyta Bek. -- Kurs Bot. 1: 89 (1863)  
= Ophioglossophytina Doweld -- Tent. Syst. Pl. Vasc.: ix (2001)  
= Ophioglossopsida Thomé -- Lehrb. Bot., ed. 4: 205 (1874)

### Ophioglossaceae Martynov -- Tekhno-Bot. Slovar: 438 (1820) (Ophioglosseae)

Phylogeny: Zhang et al. 2020, Kuo et al. 2024  
= Ophioglosseae R. Br. -- Prodr. Fl. Nov. Holland. 163 (1810)

#### Botrychioideae C. Presl -- Suppl. Tent. Pterid. 42 (1845)

1-5 genera, ca. 60 spp.  
= Botrychieae Bommer -- Bull. Soc. Roy. Bot. Belgique 5: 560 (1867)

###### *Botrychium* Sw. -- J. Bot. (Schrader) 1800(2): 8, 110. 1801 \[Oct-Dec 1801\]

Distribution: Holarctic, 2 spp. to Mexico, 1 sp. temperate South America. Several cryptic species await description, especially in the lunaria clade in Europe and Asia.  
= *Phyllotrichium* Prantl -- Ber. dt. Bot. Ges. 1: 349 (1883)

###### *Botrypus* Rich. ex Michx. -- Fl. bor. Amer. 2: 274 (1803)

Distribution: Holarctic  
= *Botrypus* Rich. -- Cat. Pl. Jard. Méd. Paris 121. 1801  
= *Osmundopteris* (Milde) Small -- Ferns S.E. States \[Small\] 377, 482. 1938 \[4 Oct 1938\]

###### *Japanobotrychum* Masam. -- J. Soc. Trop. Agric. 3(3): 246. 1931 \[31 Oct 1931\]

Distribution: Asia, trop. Africa

###### *Sahashia* Li Bing Zhang & Liang Zhang -- Cladistics 36(4): 387. 2020 \[17 Jan 2020\] \[epublished\]

Distribution: E-Asia

###### *Sceptridium* Lyon -- Bot. Gaz. 40(6): 457. 1905 \[Dec 1905\]

Distribution: Temperate worldwide.  
= *Holubiella* Škoda -- Preslia 68(4): 345. 1997 \[1996 publ. 1997\]

#### Helminthostachyoideae C. Presl -- Suppl. Tent. Pterid. 58 (1845)

1 genus, 1 sp.

###### *Helminthostachys* Kaulf. -- Flora 5(1): 103. 1822 ; & Enum. 28. 1824

Distribution: Tropical Asia, Pacific, Australia  
= *Botryopteris* C.Presl -- Reliq. Haenk. 1: 76. 1825  
= *Ophiala* Desv. -- Mém. Soc. Linn. Paris 6(2): 195. 1827 \[May 1827\] ; Prodr. Foug.

#### Mankyuoideae J.R.Grant & B.Dauphin -- J. Syst. Evol. 54(6): 594. 2016 \[14 Feb 2016\] \[epublished\]

1 genus, 1 sp.

###### *Mankyua* B.Y.Sun, M.H.Kim & C.H.Kim -- Taxon 50(4): 1020. 2002 \[dt. Dec 2001; publ. 9 Jan 2002\]

Distribution: Korea (Cheju Isl.)

#### Ophioglossoideae C. Presl -- Suppl. Tent. Pterid. 47 (1845)

4 genera, ca. 50 spp.  
= Ophioglossaceae Martinov -- Tekhno-Bot. Slovar 438. 1820 \[3 Aug 1820\] , as ‘Ophioglosseae’  
= Ophioglosseae Hook. & Lindl. ex Duby -- Bot. Gall. 1: 536 (1828)

###### *Cheiroglossa* C. Presl -- Suppl. Tent. Pterid. 56 (1845)

Distribution: Neotropics (1), Africa and Indian Ocean (1)  
= *Ophioglossum* sect. Cheiroglossum (C. Presl) T. Moore -- Index Filic. (T. Moore) 125 (1857)  
= *Ophioglossum* subgen. Cheiroglossa (C. Presl) R. T. Clausen -- Mem. Torrey Bot. Club 19(2): 112 (1938)

###### *Ophioderma* (Blume) Endl. -- Gen. Pl. \[Endlicher\] 66. 1836 \[Aug 1836\]

Distribution: Old World

###### *Ophioglossum* L. -- Sp. Pl. 2: 1062. 1753 \[1 May 1753\] ; et in Gen. Pl. ed. 5, 484. 1754

Distribution: Almost worldwide. Species delimitation is often highly disputed because of few morphological characters. The split in smaller genera appears unnecessary because the genus remains monophyletic if they are included, and those genera are morphologically almost impossible to separate.  
= *Cassiopteris* H.Karst. -- Linnaea 20(4): 437. 1847 \[Aug 1847\]  
= *Goswamia* Li Bing Zhang & Liang Zhang -- Molec. Phylogen. Evol. 173-107512: 23. 2022 \[17 May 2022\] \[epublished\]  
= *Haukia* Li Bing Zhang & Liang Zhang -- Molec. Phylogen. Evol. 173-107512: 24. 2022 \[17 May 2022\] \[epublished\]  
= *Paraneura* Prantl -- Ber. dt. Bot. Ges. 1: 350 (1833)  
= *Ptiloneura* Prantl -- Ber. dt. Bot. Ges. 1: 351 (1883)  
= *Rhizoglossum* C.Presl -- Suppl. Tent. Pterid. 48. 1845  
= *Whittieria* Li Bing Zhang & Liang Zhang -- Molec. Phylogen. Evol. 173-107512: 24. 2022 \[17 May 2022\] \[epublished\]

## Marattiales Link -- Hort. Berol. 2: 148 (1833) (Marattiaceae)

= Christenseniales Doweld -- Tent. Syst. Pl. Vasc. vii (2001) (Order)  
= Angiopterideae Engl. -- Syllabus, ed. 1: 56 (1892)  
= Danaeeae T. Moore -- Index Fil.: xiii (1857-1862)  
= Marattieae Bory -- B. C. J. Dumortier, Anal. Fam. Pl.: 67 (1829)  
= Marattiidae Klinge -- Fl. Est-Liv-Churland 1: 93 (1882)  
= Marattiophyta Heintze -- Cormofyt. Fylog.: 22 (1927)  
= Marattiopsida Doweld -- Tent. Syst. Pl. Vasc.: vii (2001)

### Marattiaceae Kaulf. -- Enum. Filic. 31. 1824 \[8 Apr - 29 May 1824\]

6 genera, ca. 150 species  
= Angiopteridaceae Fée ex J.Bommer -- Bull. Soc. Roy. Bot. Belgique 5: 345, 359. 1867  
= Christenseniaceae Ching -- Bull. Fan Mem. Inst. Biol. Bot. 10: 227. 1940  
= Danaeaceae C.Agardh -- Aphor. Bot. 8: 117. 1822 \[19 Jun 1822\]  
= Kaulfussiaceae Campb. -- Evol. Land Pl. 333 (1940), nom. illeg.  
= Angiopteridoideae C. Presl -- Suppl. Tent. Pterid.: 18 (1845)  
= Danaeoideae J. Williams -- J. H. Balfour, Man. Bot., ed. 3: 566 (1855)  
= Kaulfussioideae Campb. -- Struct. Moss. Ferns, ed. 2, 298, 300 (1905), nom. illeg.  
= Marattioideae C. Presl -- Suppl. Tent. Pterid.: 8 (1845)

###### *Angiopteris* Hoffm. -- Comm. Soc. Reg. Gött. 12: 29 (1796), nom. cons.

Distribution: E- and tropical Asia, few to Pacific and Australia, 2 Indian Ocean. Inclusion of Archangiopteris following Murdock (2005-2008). India has only 3(-4) species fide Fraser-Jenkins et al. 2017, China a maximum of 28 (Flora of China), but this is probably too many. Rolleri (2003) recognizes only 10 species in Angiopteris s. str.  
= *Archangiopteris* Christ & Giesenh. -- Flora 86: 72, 77. 1899  
= *Clementea* Cav. -- Descr. Pl. (Cavanilles) 553. 1803  
= *Macroglossum* Copel. -- Philipp. J. Sci., C 3(6): 342. 1908 \[Dec 1908\]  
= *Protangiopteris* Hayata -- Bot. Mag. (Tokyo) 42: 305, 346. 1928  
= *Protomarattia* Hayata -- Bot. Gaz. 67: 88. 1919  
= *Psilodochea* C.Presl -- Suppl. Tent. Pterid. 28. 1845 \[late 1845\]

###### *Christensenia* Maxon -- Proc. Biol. Soc. Washington 18: 239. 1905

Distribution: Tropical Asia, S-China  
= *Kaulfussia* Blume -- Enum. Pl. Javae 2: 260. 1828  
= *Macrostoma* Griff. -- Asiat. Res. 19: 110. 1836 ; & nom nud. in Icon. Pl. Asiat. 2: t. 137 (1849)

###### *Danaea* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5: 420, t.9(11). 1793

Distribution: Moist tropical forests in the Americas from sea level to about 2500 m elevation. This database revised by H. Tuomisto (2021). Key to all species and 18 new species see Keskiniva et al. (2024a/b)  
= *Arthrodanaea* C. Presl -- Suppl. Tent. Pterid. 37 (1845)  
= *Heterodanaea* C.Presl -- Suppl. Tent. Pterid. 38. 1845 \[late 1845\]

###### *Eupodium* J.Sm. -- J. Bot. (Hooker) 3: 318. 1841 ; et in Gen. Fil. \[Hooker\] t.118 (1842); et in London J. Bot. 2(7): 392 (1843)

Distribution: Trop. America

###### *Marattia* Sw. -- Prodr. \[O. P. Swartz\] 8, 128. 1788 \[20 Jun-29 Jul 1788\]

Distribution: S-Mexico to S-Brazil, Greater Antilles, Hawaii (1)  
= *Celanthera* Thouin ex Desv. -- Mém. Soc. Linn. Paris 6(2): 206. 1827  
= *Discostegia* C.Presl -- Suppl. Tent. Pterid. 11. 1845 \[late 1845\]  
= *Gymnotheca* C.Presl -- Suppl. Tent. Pterid. 12. 1845 \[late 1845\]  
= *Stibasia* C.Presl -- Suppl. Tent. Pterid. 15. 1845 \[late 1845\]

###### *Ptisana* Murdock -- Taxon 57(3): 744 (-745). 2008 \[28 Aug 2008\]

Distribution: Trop. Old World, many New Guinea

## Osmundales Link -- Hort. Berol. 2: 138 (1833) (Osmundaceae)

= Osmundopsida Doweld -- Tent. Syst. Pl. Vasc. ix (2001) (Class)

### Osmundaceae Martinov -- Tekhno-Bot. Slovar 445. 1820 \[3 Aug 1820\]

4-6 genera, 23 species  
= Osmundoideae Sweet -- Hort. Brit.: 460 (1826)  
= Osmundeae Hook. & Lindl. ex Duby -- Bot. Gall. 1: 536 (1828)

###### *Claytosmunda* (Y. Yatabe, N. Murak. & K. Iwats.) Metzgar & Rouhan -- J. Syst. Evol. 54(6): 594 (2016)

Distribution: North America, E-Asia  
= *Osmunda* subgen. Claytosmunda Y. Yatabe, N. Murak. & K. Iwats. -- Acta Phytotax. Geobot. 56(2): 127-128 (2005)

###### *Leptopteris* C. Presl -- Suppl. Tent. Pterid. 70 (1845)

Distribution: Australia, New Zealand, Samoa to New Guinea, New Caledonia  
= *Todea* sect. Leptopteris (C. Presl) T. Moore -- Index Filic. (T. Moore) 120 (1857)

###### *Osmunda* L. -- Sp. Pl. 2: 1063. 1753 \[1 May 1753\] ; et in Gen. Pl. ed 5: 484 (1754)

Distribution: Northern hemisphere and subtropics, 1 neotropical  
= *Aphyllocalpa* Cav. -- Anales Ci. Nat. 5: 164. 1802 ; & Descr. 556. 1803  
= *Struthiopteris* Bernh. -- J. Bot. (Schrader) 1800(2): 126 (1801)

###### *Osmundastrum* C.Presl -- Gefässbundel Farrn 18. 1847 , preprinted from Abh. Königl. Böhm. Ges. Wiss. 5(5): 326 (1848)

Distribution: E-Asia, North and Central America

###### *Plenasium* C.Presl -- Tent. Pterid. 109. 1836

Distribution: Temperate and trop. Asia

###### *Todea* Bernh. -- J. Bot. (Schrader) 1800(2): 126. 1801 \[Oct-Dec 1801\]

Distribution: South Africa, Australia, New Zealand, New Guinea

###### × *Osmunasium* Hong M.Liu, Schuettp. & H.Schneid. -- J. Syst. Evol. 58(6): 999. 2020 \[21 May 2020\] \[epublished\]

Distribution: China

###### × *Osmunimunda* Xia Wan & Li Bing Zhang -- Phytotaxa 575(1): 105. 2022 \[6 Dec 2022\] \[epublished\]

Distribution: Asia, North America  
= × *Osmuntonia* Hong M.Liu, Schuettp. & H.Schneid. -- J. Syst. Evol. 58(6): 999. 2020 \[21 May 2020\] \[epublished\]

## Hymenophyllales A. B. Frank -- Syn. Pflanzenkd. (Leunis) ed. 2, 3: 1452 (1877)

= Hymenophyllidae Schmakov -- Turczaninowia 12(3/4): 95 (2009)

### Hymenophyllaceae Mart. -- Consp. Regn. Veg. \[Martius\] 3. 1835 \[Sep-Oct 1835\] , as ‘Hymenophylleae’

9 genera, ca. 620 spp. Circumscription of genera see Ebihara et al. (2006)  
= Trichomanaceae G.Kunkel -- Feddes Repert. 70: 155. 1965 , as ‘Trichomanaeaceae’  
= Cardiomanioideae K.Iwats. -- Acta Phytotax. Geobot. 35(4-6): 177. 1984 \[29 Nov 1984\]

#### Hymenophylloideae Burnett -- Outlines Bot. 324 (1835)

= Cardiomanoideae K. Iwats. -- Acta Phytotax. Geobot. 35: 177 (1984)  
= Hymenophylleae Bory ex Gaudich. -- Freycinet, Voy. Uranie, Bot.: 262 (1828)  
= Hymenophyllinae Fr. -- Summa Veg. Scand.: 255 (1845)  
= Hymenophyllineae Bessey -- Bot. High Schools: 376 (1880)

###### *Hymenophyllum* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5: 418, t.9, f.8. 1793 ; also published by Smith in Smith’s Tracts (1798) 256, t. 1, fig. 8.

Distribution: Tropics / south-temperate, mostly neotropical  
= *Acanthotheca* DC. -- Prodr. \[A. P. de Candolle\] 6: 73. 1838 \[1837 publ. early Jan 1838\]  
= *Amphipterum* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Apteropteris* (Copel.) Copel. -- Philipp. J. Sci. 67: 34. 1938  
= *Buesia* (C.V.Morton) Copel. -- Philipp. J. Sci. 67: 47. 1938  
= *Cardiomanes* C.Presl -- Hymenophyllaceae \[Presl\] 12. 1843  
= *Charitophyllum* Bosch -- Pl. Jungh. 1 (18) (1856)  
= *Chilodium* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 23 (1843)  
= *Craspedoneuron* Bosch -- Hymenophyll. Javan. 12, t.10. 1861  
= *Craspedophyllum* (C.Presl) Copel. -- Philipp. J. Sci. 67: 27. 1938  
= *Cycloglossum* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 32 (1843)  
= *Dermatophlebium* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Diplophyllum* Lehm. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 8: 310. 1818  
= *Euphorophyllum* Bosch -- Pl. Jungh. 1 (19) (1856)  
= *Gonocormus* sect. Microtrichomanes Mett. ex Prantl -- NA  
= *Hemicyatheon* (Domin) Copel. -- Philipp. J. Sci. 67: 27. 1938  
= *Hymenoglossum* C.Presl -- Hymenophyllaceae \[Presl\] 35. 1843  
= *Leptocionium* C.Presl -- Hymenophyllaceae \[Presl\] 26. 1843  
= *Mecodium* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Meringium* C.Presl -- Hymenophyllaceae \[Presl\] 24. 1843 ; et in Abh. k. bohm. Ges. Wiss. ser. 5, 3: 116 (1845).  
= *Microtrichomanes* (Mett. ex Prantl) Copel. -- Philipp. J. Sci. 67: 35 (1938)  
= *Myriodon* (Copel.) Copel. -- Philipp. J. Sci. 67: 47. 1938 , Typus: Myriodon odontophyllum (Copel.) Copel.  
= *Myrmecostylum* C.Presl -- Hymenophyllaceae \[Presl\] 27. 1843  
= *Pachyloma* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 318. 1861  
= *Pleuromanes* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Pseudomecodium* (K.Iwats.) Satou -- Hikobia 12(3): 269. 1997  
= *Ptychomanes* Hedw. -- Fil. Gen. Sp. fasc. II. 1800  
= *Ptychophyllum* C.Presl -- Hymenophyllaceae \[Presl\] 28. 1843  
= *Rosenstockia* Copel. -- Gen. Fil. \[Copeland\] 36. 1947  
= *Serpyllopsis* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 318. 1861  
= *Sphaerocionium* C.Presl -- Hymenophyllaceae \[Presl\] 33. 1843 ; preprinted from Abh. k. bohm. Ges. Wiss. ser. 5, 3: 125 (1845).  
= *Tetralasma* Phil. -- Linnaea 30(2): 208. 1859 \[post Apr 1859\]

#### Trichomanoideae C. Presl -- Hymenophyllaceae 102 (1843)

= Didymoglosseae C. Presl -- Hymenophylleae: 144 (1843)  
= Trichomaneae Dumort. -- Anal. Fam. Pl.: 67 (1829)

###### *Abrodictyum* C.Presl -- Hymenophyllaceae \[Presl\] 20. 1843

Distribution: Tropics, mostly Old World, only few New World  
= *Abrodictyum* subgen. Pachychaetum (C. Presl) Ebihara & K. Iwats. -- Blumea 51(2): 242 (2006)  
= *Cephalomanes* subgen. Macroglena (C. Presl) K. Iwats. -- Acta Phytotax. Geobot. 35(4-6): 176 (1984)  
= *Habrodictyon* Bosch -- Hymenophyll. Javan. 17. 1861  
= *Macroglena* (C. Presl) Copel. -- Philipp. J. Sci. 67: 82 (1938)  
= *Pachychaetum* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 16 (1843)  
= *Selenodesmium* (Prantl) Copel. -- Philipp. J. Sci. 67: 80. 1938  
= *Trichomanes* subgen. Macroglena C. Presl -- Abh. Königl. Böhm. Ges. Wiss., Math.-Naturw. Cl. V, 5: 5: 333 (1848)  
= *Trichomanes* subgen. Selenodesmium Prantl -- Unters. Morph. Gefässkr. 1: 53 (1875)

###### *Callistopteris* Copel. -- Occas. Pap. Bernice Pauahi Bishop Mus. 14: 49. 1938 \[May 1938\] ; & Philip. Journ. Sc. 67: 64. 1938 (Oct.).

Distribution: Tropical Old World, Hawaii  
= *Cephalomanes* subgen. Callistopteris (Copel.) K. Iwats. -- Acta Phytotax. Geobot. 35(4-6): 176 (1984)

###### *Cephalomanes* C.Presl -- Hymenophyllaceae \[Presl\] 17. 1843

Distribution: Tropical Old World

###### *Crepidomanes* (C. Presl) C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 258 (1851) s. str.

Distribution: Paleotropical and Pacific, only 1 New World  
= *Cephalomanes* subgen. Nesopteris (Copel.) K. Iwats. -- Acta Phytotax. Geobot. 35(4-6): 176 (1984)  
= *Crepidium* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 23 (1843)  
= *Crepidomanes* sect. Crepidium (C. Presl) Ebihara & K. Iwats. -- Blumea 51(2): 239 (2006)  
= *Crepidomanes* subgen. Nesopteris (Copel.) Ebihara & K. Iwats. -- Blumea 51(2): 239 (2006)  
= *Crepidophyllum* C.F.Reed -- Amer. Fern J. 38(3): 88. 1948 \[11 Oct 1948\]  
= *Crepidopteris* Copel. -- Philipp. J. Sci. 67: 57. 1938  
= *Gonocormus* Bosch -- Hymenophyll. Javan. 7. 1861  
= *Nesopteris* Copel. -- Philipp. J. Sci. 67: 65. 1938  
= *Reediella* Pic.Serm. -- Webbia 24: 718. 1970 , nom. nov  
= *Taschneria* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Trichomanes* subgen. Crepidomanes C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 17 (1851)

###### *Didymoglossum* Desv. -- Mém. Soc. Linn. Paris 6(3): 330. 1827 \[Jul 1827\]

Distribution: Tropics  
= *Didymoglossum* subgen. Microgonium (C. Presl) Ebihara & K. Iwats. -- Blumea 51(2): 236 (2006)  
= *Lecanolepis* Pic.Serm. -- Webbia 28: 449. 1973  
= *Microgonium* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 19 (1843)

###### *Polyphlebium* Copel. -- Philipp. J. Sci. 67: 55. 1938

Distribution: Southern temperate and mountain forests of low altitudes  
= *Phlebiophyllum* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 321. 1861

###### *Trichomanes* L. -- Sp. Pl. 2: 1097 (1753) s. str.

Distribution: Mostly neotropics, but 5 trop. Africa, Madagascar and Indian Ocean (see Dubuisson et al. 2023), 1 in Malesia (Boucheron-Dubuisson et al. 2023)  
= *Achomanes* Neck. -- Elem. Bot. (Necker) 3: 313. 1790  
= *Allittia* P.S.Short -- Muelleria 20: 54. 2004  
= *Bergera* W.Schaffn. -- Mém. Foug., 9. Cat. Foug. Mex. 38. 1857  
= *Davalliopsis* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 323. 1861  
= *Feea* Bory -- Dict. Class. Hist. Nat. \[Bory\] 6: 446. 1824  
= *Hemiphlebium* C.Presl -- Hymenophyllaceae \[Presl\] 25. 1843  
= *Holophlebium* Christ -- Farnkr. Erde 27 (1897)  
= *Homoeotes* C.Presl -- Gefässbundel Farrn 23. 1847 ; et in Abh. Königl. Böhm. Ges. Wiss. ser. 5, 5: 331 (1848)  
= *Hymenostachys* Bory -- Dict. Class. Hist. Nat. \[Bory\] 6: 588. 1825 ; & 8: 462. 1825  
= *Lacostea* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 320. 1861  
= *Lecanium* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(3): 11 (1843)  
= *Leptomanes* Prantl -- Unters. Morph. Gefäßkrypt. 1: 52 (1875)  
= *Leucomanes* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]  
= *Maschalosorus* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 320. 1861 , Trichomanes  
= *Mortoniopteris* Pic.Serm. -- Webbia 31: 243. 1977  
= *Neuromanes* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 163. 1851  
= *Neurophyllum* C.Presl -- Hymenophyllaceae \[Presl\] 18. 1843  
= *Odontomanes* C.Presl -- Epimel. Bot. 20. 1851 \[Oct 1851\]  
= *Pteromanes* Pic.Serm. -- Webbia 31: 244. 1977  
= *Ptilophyllum* Bosch -- Verslagen Meded. Afd. Natuurk. Kon. Akad. Wetensch. 11: 321. 1861  
= *Pyxidaria* Gled. -- Syst. Pl. \[Gleditsch\] 291. 1764 \[ante 13 Sep 1764\]  
= *Ragatelus* C.Presl -- Hymenophyllaceae \[Presl\] 16. 1843  
= *Trichomanes* subgen. Davalliopsis (Bosch) Ebihara & K. Iwats. -- Blumea 51(2): 247 (2006)  
= *Trichomanes* subgen. Lacostea (Bosch) C. Chr. -- Index Filic. 634 (1906)  
= *Trigonophyllum* (Prantl) Pic.Serm. -- Webbia 31(1): 242. 1977

###### *Vandenboschia* Copel. -- Philipp. J. Sci. 67: 51. 1938 \[26 Oct 1938\]

Distribution: Worldwide tropics and subtropics  
= *Lacosteopsis* (Prantl) Nakaike -- Enum. Pterid. Jap.: Filic. 21. 1975  
= *Trichomanes* subgen. Vandenboschia (Copel.) Allan -- Fl. New Zeal. 34 (1961)  
= *Vandenboschia* subgen. Lacosteopsis (Prantl) Ebihara & K. Iwats. -- Blumea 51(2): 242 (2006)

## Gleicheniales Schimp. -- Traité Paléont. Vég. 1: 669 (1869)

= Dipteridales Doweld -- Tent. Syst. Pl. Vasc. x (2001) (Order)  
= Matoniales Pic. Serm. ex Reveal -- Phytologia 74: 175 (1993) (Order)  
= Stromatopteridales Pic. Serm. ex Reveal -- Phytologia 74: 176 (1993) (Order)  
= Gleicheniopsida Doweld -- Tent. Syst. Pl. Vasc. ix (2001) (Class)  
= Matoniopsida Doweld -- Tent. Syst. Pl. Vasc. vii (2001) (Class)

### Dipteridaceae Seward & E.Dale -- Philos. Trans., Ser. B 194: 487, 499, 502. 1901

2 genera, 10 spp.  
= Cheiropleuriaceae Nakai -- Bot. Mag. (Tokyo) 42(496): 210. 1928  
= Dipteridoideae Nathorst -- Kongl. Svenska Vetenskapsakad. Handl., n. s., 41(5): 19 (1906)  
= Dipteridinae Diels -- Engler & Prantl, Nat. Pflanzenfam. 1(4): 167 (1899)

###### *Cheiropleuria* C.Presl -- Epimel. Bot. 189. 1851 \[Oct 1851\]

Distribution: Tropical and E-Asia

###### *Dipteris* Reinw. -- Syll. Pl. Nov. 2: 3. 1825 \[dt. 1828; issued 1825\]

Distribution: NE-India, S-China, S-Ryukyu Isl. to NE-Queensland and Fiji

### Gleicheniaceae C.Presl -- Reliq. Haenk. 1: 70. 1825 \[Jun-Nov 1825\] , as ‘Gleicheniae’

7 genera, ca. 145 spp.  
= Dicranopteridaceae Ching -- Acta Phytotax. Sin. 3: 94 (1954), nom. inval.  
= Dicranopteridaceae Ching ex Doweld -- Prosyllabus Tracheophytorum X (2001).  
= Stromatopteridaceae (Nakai) Bierh. -- Phytomorphology 18: 263. 1968  
= Gleichenioideae R. Br. -- R. Sweet, Hort. Brit.: 460 (1826)  
= Stromatopteridoideae Nakai -- Bull. Natl. Sci. Mus. (Tokyo) 29: 32 (1950)  
= Gleicheneae R. Br. -- Prodr. Fl. Nov. Holland. 160 (1810)  
= Gleichenieae Gaudich. -- H. L. C. de Saulces de Freycinet, Voy. Uranie, Bot.: 257 (1828)  
= Gleicheniineae Bessey -- Bot. High Schools: 376 (1880)

###### *Dicranopteris* Bernh. -- Neues J. Bot. 1(2): 38. 1805 \[dt. 1806; issued in Nov 1805\]

Distribution: Pantropical / austral, mostly Malesia  
= *Heteropterygium* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 355 (1900)  
= *Hicriopteris* C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 26 (1851) (non Ching, nec Copel.)  
= *Holopterygium* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 353 (1900)  
= *Mesosorus* Hassk. -- Fil. Jav. 1: 2. 1856

###### *Diplopterygium* Diels -- Nat. Pflanzenfam. \[Engler & Prantl\] 1(4): 353. 1900 \[Apr 1900\] , Gleichenia se

Distribution: SE-Asia, S-China, S-Japan to Queensland and Hawaii, 1 sp. tropical America  
= *Hicriopteris* Ching -- Sunyatsenia 5: 277 (1940) (non C. Presl)

###### *Gleichenella* Ching -- Sunyatsenia 5: 276. 1940

Distribution: Trop. America. Valid genus fide Mickel (2004)  
= *Acropterygium* Diels -- Nat. Pflanzenfam. \[Engler & Prantl\] 1(4): 353. 1900 \[Apr 1900\] , Gleichenia se

###### *Gleichenia* Sm. -- Mém. Acad. Turin 5: 419 (1793) s. str.

Distribution: Paleotropical / austral, not in the New World  
= *Calymella* C.Presl -- Tent. Pterid. 48. 1836  
= *Gleicheniastrum* C.Presl -- Gefässbundel Farrn 30. 1847 , preprinted from Abh. Königl. Böhm. Ges. Wiss. 5(5): 338 (1848)

###### *Rouxopteris* Hong M.Liu -- Pl. Syst. Evol. 306(2, 30): 9. 2020 \[26 Feb 2020\] \[epublished\]

Distribution: E-tropical Africa, Madagascar, Mascarenes

###### *Sticheropsis* L.V.Lima, Salino & T.E.Almeida -- Bot. J. Linn. Soc. \[8 of 21\]. 2024 \[20 Jul 2024\] \[epublished\]

Distribution: tropical Asia to W-Pacific and Australia

###### *Sticherus* C.Presl -- Tent. Pterid. 51. 1836 \[ante 2 Dec 1836\]

Distribution: Pantropical / austral, mostly in the Neotropics (55), few in tropical Old World. Revision for Neotropics: Gonzales & Kessler (2011)  
= *Dicranopteris* Underw. -- Bull. Torrey Bot. Club 34: 249 (1907) (p. p., non Bernh.)

###### *Stromatopteris* Mett. -- Ann. Sci. Nat., Bot. sér. 4, 15: 84. 1861

Distribution: New Caledonia

### Matoniaceae C.Presl -- Gefässbundel Farrn 32. 1847

2 genera, 4 spp.  
= Matonieae T. Moore -- Index Fil.: xii (1857-1862)

###### *Matonia* R.Br. ex Wall. -- Pl. Asiat. Rar. (Wallich). 1: 16; t.16. 1829

Distribution: Malesia  
= *Prionopteris* Wall. -- Numer. List \[Wallich\] n. 184. 1829

###### *Phanerosorus* Copel. -- Philipp. J. Sci., C 3(6): 344. 1909

Distribution: E-Malesia

## Schizaeales Schimp. -- Traité Paléont. Vég. 1: 674 (1869)

= Schizaeopsida Doweld -- Tent. Syst. Pl. Vasc.: x (2001)

### Anemiaceae Link -- Handbuch \[Link\] 3: 8. 1833

1 genus, 118 spp.  
= Mohriaceae C.F.Reed -- Bol. Soc. Brot. ser. 2, 21: 168. 1948  
= Anemioideae C. Presl -- Suppl. Tent. Pterid.: 77 (1845)  
= Mohrioideae C. Presl -- Suppl. Tent. Pterid.: 95 (1845)  
= Anemieae Bommer -- Bull. Soc. Roy. Bot. Belgique 5: 558 (1867)  
= Mohrieae Bommer -- Bull. Soc. Roy. Bot. Belgique 5: 558 (1867)

###### *Anemia* Sw. -- Syn. Fil. (Swartz) 155. 1806 \[Mar-Apr 1806\]

Distribution: Mostly neotropical (61 spp. Brazil, ca. 20 Mexico), 17 Africa/Madagascar, 1 extending to peninsular India. Revision: Mickel (2016)  
= *Aneimiaebotrys* Fée -- Crypt. Vasc. Bresil 1: 267. 1869  
= *Anemidictyon* J.Sm. ex Hook. -- Gen. Fil. \[Hooker\] t. 103. 1842  
= *Anemirhiza* J.Sm. -- Bot. Voy. Herald \[Seemann\] 6: 243. 1854 \[late 1854 or v. early 1855?\]  
= *Colina* Greene -- Erythea 1: 247. 1893  
= *Coptophyllum* Gardner -- London J. Bot. 1: 133. 1842  
= *Hemianemia* (Prantl) C.F.Reed -- Bol. Soc. Brot. sér. 2, 21: 154. 1947  
= *Mohria* Sw. -- Syn. Fil. (Swartz) 6, 159. 1806  
= *Ornithopteris* Bernh. -- Schrad., Neu. J. Bot. 1(2): 40 (1806)  
= *Spathopteris* C. Presl -- Suppl. Tent. Pterid. 95 (1845)  
= *Trochopteris* Gardner -- London J. Bot. 1: 74. 1842

### Lygodiaceae C.Presl -- Suppl. Tent. Pterid. 98. 1845

1 genus, 29 spp.  
= Lygodieae Le Maout & Decne. -- Traité Général Bot.: 657 (1868)

###### *Lygodium* Sw. -- J. Bot. (Schrader) 1800(2): 7, 106. 1801 \[Oct-Dec 1801\]

Distribution: Tropics and south-temperate worldwide, mostly Malesia, trop. America (7), temperate America (1)  
= *Arthrolygodes* C. Presl -- Suppl. Tent. Pterid. 101 (1845)  
= *Cteisium* Michx. -- Fl. Bor.-Amer. (Michaux) 2: 275. 1803 \[19 Mar 1803\]  
= *Gisopteris* Bernh. -- J. Bot. (Schrader) 1800(2): 129.  
= *Hugona* Cav. ex Roem. -- Arch. Bot. \[Leipzig\] 2(3): 486. 1801  
= *Hydroglossum* Willd. -- Abh. Kurfürstl.-Mainz. Akad. Nützl. Wiss. Erfurt 2(5): 13, 20. 1802 ; alt. title: Bemerk. Selt. Farrenkr. 13, 20. 1802  
= *Lygodictyon* J.Sm. -- Gen. Fil. \[Hooker\] t. 111 B. 1842  
= *Odontopteris* Bernh. -- J. Bot. (Schrader) 1800(2): 127.  
= *Ramondia* Rich. -- Syn. Pl. \[Persoon\] i. 216 (Ramonda) (1805); Jaume St. Hil. Expos. i. 280 (1805).  
= *Ugena* Cav. -- Icon. \[Cavanilles\] 6: 73. 1801 ; & Anal. Cienc. 4. 249. 1801  
= *Vallifilix* Thouars -- Gen. Nov. Madagasc. 1. 1806 \[17 Nov 1806\] ; & Romer, Collect. Bot. 195. 1809

### Schizaeaceae Kaulf. -- Wesen Farrenk. \[119\]. 1827 \[Jul-Sep 1827\]

3(-4) genera, 35 - 40 spp. Phylogeny: Ke et al. (2022)  
= Schizaeoideae Lindl. -- Veg. Kingd.: 80 (1846)  
= Schizaeeae Kaulf. -- F. von Paula von Schrank & Mart., Hort. Reg. Monac.: 4 (1829)  
= Schizaeineae Bessey -- Bot. High Schools: 377 (1880)

###### *Actinostachys* R. Br. ex Hook. & Baker -- Gen. Fil., t. 111 (1842)

Distribution: Tropics, many endemics in New Caledonia  
= *Actinostachys* R. Br. ex Wall. -- Numer. List no. 1 (1829), nomen  
= *Schizaea* subgen. Actinostachys (Wall.) J. W. Sturm -- Mart., Fl. Bras. 1(2): 179 (1859)

###### *Microschizaea* C.F.Reed -- Bol. Soc. Brot. sér. 2, 21: 133. 1947

Distribution: Malesia, Australia, New Zealand, Pacific, 1 trop. and South Africa, 1 subantarctic and S-South America. The genus should be recognized fide Ke et al. 2022.

###### *Schizaea* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5: 419, t.9(9). 1793 ; Tracts Relating to Natural History: 257, t. 1, f. 9 (1798).

Distribution: Tropical America, E-USA, Chile/Falkland Isl., tropical Old World, Pacific (several New Caledonia), Australia, New Zealand (3). Schizaea pusilla probably belongs in a separate genus (Ke et al. 2022)  
= *Lophidium* Rich. -- Actes Soc. Hist. Nat. Paris 1: 114. 1792 \[Oct 1792\]  
= *Ripidium* Bernh. -- J. Bot. (Schrader) 1800(2): 127.

## Salviniales Bartl. -- Mart., Consp. Regn. Veg.: 4 (1835)

= Marsileales Bartl. -- Martius, Consp. Regni Veg. 4 (1835) (Marsileaceae) (Order)  
= Pilulariales Bercht. & J. Presl -- Prir. Rostlin. 1: 272 (1820) (Pilulariae) (Order)  
= Marsileidae Doweld -- Tent. Syst. Pl. Vasc.: x (2001)  
= Marsileineae Wettst. -- Handb. Syst. Bot., ed. 2: 346 (1911)  
= Marsileopsida Trevis. -- Bull. Soc. Roy. Bot. Belg. 16: 5 (1877) (Marsigliales) (Class)  
= Salviniidae Pic. Serm. ex Reveal -- Phytologia 79: 70 (1996)  
= Salvinineae Wettst. -- Handb. Syst. Bot., ed. 2: 350 (1911)  
= Salviniopsida Kamelin & Shmakov -- Kamelin, Fl. Altaia: 253 (2005) (Class)

### Marsileaceae Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 5: 126. 1802 \[1 Nov 1802\] , as ‘Marsileae’

3 genera, ca. 55 spp.  
= Pilulariaceae Bercht. & J. Presl -- Prir. Rostlin 1: 272 (1820)  
= Pilulariaceae Mirb. ex DC. -- Essai Propr. Méd. Pl. 48 (1804) (Pilulariae)  
= Marsileoideae Eaton -- Man. Bot. (A. Eaton), ed. 6. 2: 81. 1833 \[22 May-3 Jun 1833\] , as ‘suborder marsileaceae’  
= Marsileeae Duby -- Bot. Gall. 1: 542 (1828)

###### *Marsilea* L. -- Sp. Pl. 2: 1099. 1753 \[1 May 1753\]

Distribution: Worldwide, mostly tropics and subtropics, many in Africa  
= *Lemma* B.Juss. -- Gen. Pl. \[Jussieu\] lxiii. 1789 ; & Adanson, Fam. D. pl. 2. 21. 1763; Aublet, Hist. Guian. 2. 960. 1775  
= *Spheroidia* Dulac -- Fl. Hautes-Pyrénées 39. 1867  
= *Zalusianskya* Kuntze -- Revis. Gen. Pl. 2: 822 (1891), nom. illeg., non Zaluzianskya F. W. Schmidt 1793 (Scrophulariaceae)  
= *Zaluzianskia* Benth. & Hook.f. -- Gen. Pl. \[Bentham & Hooker f.\] 2(2): 944, sphalm. 1876 \[May 1876\]

###### *Pilularia* L. -- Sp. Pl. 2: 1100. 1753 \[1 May 1753\]

Distribution: North-temperate, western and southern South America, New Zealand, Australia, South Africa (2)  
= *Calamistrum* (L.) Kuntze -- Revis. Gen. Pl. 2: 822. 1891 \[5 Nov 1891\]

###### *Regnellidium* Lindm. -- Ark. Bot. 3(6): 2. 1904

Distribution: Temperate South America

### Salviniaceae Martinov -- Tekhno-Bot. Slovar 559. 1820 \[3 Aug 1820\] , as ‘Salviniae’

2 genera, 16-17 spp.  
= Azollaceae Wettst. -- Handb. Syst. Bot. 2(1): 77. 1903 \[Nov 1903\]  
= Azolloideae Griff. -- Calcutta J. Nat. Hist. 5: 255 (1844)  
= Salvinioideae Mirb. ex Meisn. -- Pl. Vasc. Gen.: Tab. Diagn. 436, Comm. 338 (1843)  
= Azolleae Schenk -- Flora 29: 506 (1846)  
= Salvinieae Brongn. ex Duby -- Bot. Gall. 1: 542 (1828)

###### *Azolla* Lam. -- Encycl. \[J. Lamarck & al.\] 1(1): 343. 1783 \[2 Dec 1783\]

Distribution: Worldwide, mostly tropical  
= *Carpanthus* Raf. -- Med. Repos. 2(5): 356. 1808 ; Journ. de Bot. 1. 221. 1808  
= *Rhizosperma* Meyen -- Reise Erde 1: 337. 1834 \[25-31 May 1834\] ; Nova Acta 18 \[1\]. 523. 1836

###### *Salvinia* P.Micheli ex Adans. -- Fam. Pl. (Adanson) 2: 15. 1763 \[Jul-Aug 1763\]

Distribution: Old World (3, except SE-Asia/Australia), New World (7-9) north to USA

## Cyatheales A. B. Frank -- Syn. Pflanzenkd. (Leunis) ed. 2, 3: 1452, 1456 (1877)

= Dicksoniales Pic. Serm. ex Reveal -- Phytologia 74: 175 (1993) (Order)  
= Hymenophyllopsidales Pic. Serm. ex Reveal -- Phytologia 74: 175 (1993) (Order)  
= Loxsomatales Pic. Serm. ex Reveal -- Phytologia 74: 175 (1993) (Order)  
= Metaxyales Doweld -- Tent. Syst. Pl. Vasc. xii (2001) (Order)  
= Plagiogyriales Pic. Serm. ex Reveal -- Phytologia 74: 176 (1993) (Order)  
= Cyatheidae Doweld -- Tent. Syst. Pl. Vasc.: xii (2001)  
= Cyatheopsida Doweld -- Tent. Syst. Pl. Vasc. xii (2001) (Class)  
= Plagiogyriidae Doweld -- Tent. Syst. Pl. Vasc.: xii (2001)

### Cibotiaceae Korall -- Taxon 55(3): 712 (708, 713; f.2). 2006 \[Aug 2006\]

1 genus, 10 spp.  
= Cibotioideae B. K. Nayar -- Taxon 19: 234 (1970)  
= Cibotieae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1873)

###### *Cibotium* Kaulf. -- Berlin. Jahrb. Pharm. Verbundenen Wiss. 21: 53. 1820 ; et in Enum. Filic. 299 (1824).

Distribution: 5 spp. SE-Asia, 2 Mexico and Central America, 4 Hawaii  
= *Hiatea* Menzies -- Sp. Fil. \[W. J. Hooker\] 1: 82. 1844  
= *Microcibotium* Hayata -- Bot. Mag. (Tokyo) 43: 316 (1929)  
= *Pinonia* Gaudich. -- Ann. Sci. Nat. (Paris) 3: 507. 1824

### Culcitaceae Pic.Serm. -- Webbia 24(2): 702. 1970 \[28 Apr 1970\]

1 genus, 2 spp.  
= Balantieae Pfeiff. -- Nomencl. Bot. 1(1): 354 (1872)

###### *Culcita* C.Presl -- Tent. Pterid. 135. 1836 ; & Maxon, Journ. Wash. Acad. Sci. 12. 454. 1922.

Distribution: Neotropics, W-Mediterranean  
= *Dicksonia* subgen. Balantium Hook. -- NA

### Cyatheaceae Kaulf. -- Wesen Farrenk. \[119\]. 1827 \[Jul-Sep 1827\]

4 genera, ca. 700 spp. Recent monographs tended to lump everything in Cyathea s. lat., but PPG-I separates again the 3 genera, and Dong et al. (2018) additionally reinstate Gymnosphaera, followed by Loiseau et al. 2019.  
= Alsophilaceae C.Presl -- Gefässbundel Farrn 32. 1847  
= Hymenophyllopsidaceae Pic.Serm. -- Webbia 24(2): 712. 1970 \[28 Apr 1970\]  
= Cyatheoideae B.K.Nayar -- Taxon 19: 234. 1970  
= Alsophileae Engl. -- Syllabus, ed. 2: 60 (1898)  
= Cyatheeae Gaudich. -- Freycinet, Voy. Uranie, Bot.: 365 (1829)  
= Alsophilinae Pfeiff. -- Nomencl. Bot. 1(1): 123 (1872)  
= Cyatheinae Dumort. -- Anal. Fam. Pl.: 67 (1829)  
= Cyatheineae Bessey -- Bot. High Schools: 376 (1880)  
= Hemiteliinae Pfeiff. -- Nomencl. Bot. 1(2): 1606 (1874)

###### *Alsophila* R.Br. -- Prodr. Fl. Nov. Holland. 158. 1810 \[27 Mar 1810\]

Distribution: Pantropics, mostly Old World (many Madagascar). Some species listed here might belong in Cyathea s. str. pending molecular results.

###### *Cyathea* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5\[2\]: 416. 1793

Distribution: Mostly tropical America, very few Old World (Pacific, Papuasia)  
= *Acanthea* Lindig -- Contr. Colomb. Cienc. 2: 34. 1861  
= *Actinophlebia* C.Presl -- Gefässbundel Farrn 47. 1847 alt. publ.: Abh. Königl. Böhm. Ges. Wiss. ser. 5. 5(2): 355. 1848.  
= *Chnoophora* Kaulf. -- Enum. Filic. 250. 1824 \[8 Apr-28 May 1824\]  
= *Cnemidaria* C.Presl -- Tent. Pterid. 56. 1836  
= *Cnemidopteris* Rchb. -- Deut. Bot. Herb.-Buch (Index gen et subgen): 148, 235. 1841 , as correction to entry 1046.2 ‘Cnemidaria’  
= *Cormophyllum* Newman -- Phytologist 5: 237. 1856 \[1854 publ 1856\]  
= *Cyathea* subgen. Hymenophyllopsis (K. I. Goebel) Christenh. -- Phytotaxa 1: 38 (2009)  
= *Disphenia* C.Presl -- Tent. Pterid. 55, t.1(13). 1836 \[ante 2 Dec 1836\] alt. publ.: Abh. Königl. Böhm. Ges. Wiss. ser. 4. 5: 55. t. 1(13). 1837  
= *Gymnopremnon* Lindig -- Contr. Colomb. Cienc. 2: 34. 1861  
= *Hemistegia* C.Presl -- Gefässbundel Farrn 46. 1847 ; et in Abh. Bohm. Ges. Wiss. ser. 5. 5(2): 354. 1848.  
= *Hemitelia* R.Br. -- Prodr. Fl. Nov. Holland. 158. 1810 \[27 Mar 1810\] , in obs.  
= *Hemiteliella* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 16: 132 (1899)  
= *Hymenophyllopsis* Goebel -- Flora 124: 3, 21 (1929)  
= *Microstegnus* C.Presl -- Abh. Bohm. Ges. Wiss. 5(5): 353. 1848  
= *Trachypremnon* Lindig -- Contr. Colomb. Cienc. 2: 34. 1861  
= *Trichipteris* C.Presl -- Delic. Prag. 1: 172. 1822 , Trichipteris; Schott, Gen. Fil. tab. 5. 1834  
= × *Cyathidaria* Caluff & Shelton -- Willdenowia 32(2): 282. 2002 \[13 Dec 2002\]

###### *Gymnosphaera* Blume -- Enum. Pl. Javae 2: 242. 1828

Distribution: Pantropics, mostly Old World (many Madagascar), only 2 neotropical. The genus has been demonstrated to be separate from Alsophila by Loiseau et al. 2019

###### *Sphaeropteris* Bernh. -- J. Bot. (Schrader) 1800(2): 122 (1801)

Distribution: Mostly tropical Old World, very few tropical America. The genus is frequently included in Cyathea s. lat., but PPG-I separates it again. See also Korall et al. (2007 and 2013).  
= *Cyathea* subgen. Sphaeropteris (Bernh.) Holttum -- Fl. Males. Ser. 2, 1: 124 (1963)

### Dicksoniaceae M.R.Schomb. -- Reis. Br.-Guiana \[Ri. Schomburgk\] 3: 1047. 1849 \[7-10 Mar 1849\]

3 genera, ca. 35 spp.  
= Lophosoriaceae Pic.Serm. -- Webbia 24(2): 700. 1970 \[28 Apr 1970\]  
= Dicksonioideae B.K.Nayar -- Taxon 19: 235. 1970  
= Dicksonieae Gaudich. -- Voy. Uranie \[Freycinet\] 367 (1829)

###### *Calochlaena* (Maxon) R. A. White & M. D. Turner -- Amer. Fern J. 78: 91 (1988)

Distribution: Philippines and Java to Australia and Samoa  
= *Culcita* subgen. Calochlaena Maxon -- J. Washington Acad. Sci. 12: 459 (1922)

###### *Dicksonia* L’Hér. -- Sert. Angl. 30. 1789 \[dt. 1788; issued Jan 1789\]

Distribution: Neotropics, St. Helena, Java, Philippines, Australia (2), New Zealand (3), New Caledonia (4), Pacific. Revision for Neotropis: Noben et al. (2018)  
= *Balantium* Kaulf. -- Enum. Filic. 288. 1824 \[8 Apr-28 May 1824\]

###### *Lophosoria* C.Presl -- Gefässbundel Farrn 36. 1847 ; reprinted in Abh. Königl. Böhm. Ges. Wiss. 5(5): 344 (1848).

1-4 spp. neotropical  
= *Trichosorus* Liebm. -- Kongel. Danske Vidensk. Selsk. Skr., Naturvidensk. Math. Afd. 5(1): 281 (seors. 129). 1849

### Loxsomataceae C.Presl -- Gefässbundel Farrn 31. 1847

2 genera, 2 spp.

###### *Loxsoma* R.Br. ex A.Cunn. -- Compan. Bot. Mag. 2: 366. 1837 \[1 Jul 1837\] , as ‘Loxoma’

Distribution: New Zealand

###### *Loxsomopsis* Christ -- Bull. Herb. Boissier ser. 2, 4(5): 399. 1904 \[30 Apr 1904\]

Distribution: South America

### Metaxyaceae Pic.Serm. -- Webbia 24(2): 701. 1970 \[28 Apr 1970\]

1 genus, 6 spp.  
= Metaxyoideae B.K.Nayar -- Taxon 19: 235. 1970

###### *Metaxya* C.Presl -- Tent. Pterid. 59. 1836 \[ante 2 Dec 1836\]

Distribution: trop. America. Revision: Cárdenas et al. (2016). Checklist revised by H. Tuomisto (2021)  
= *Amphidesmium* Schott -- Gen. Fil. \[Schott\] ad t.5. 1834

### Plagiogyriaceae Bower -- Ann. Bot. (Oxford) 40: 484. 1926

1 genus, 12 spp.

###### *Plagiogyria* (Kunze) Mett. -- Abh. Senckenberg. Naturf. Ges. 2(2): 265. 1858 \[Aug 1858\] ; reprinted as Farngatt. 2(Plagiogyria): 1. Sep 1859; cf. Copeland, Philipp. J. Sci. 38: 377 f (1929).

Distribution: Mostly Japan, China, Malesia, India, 1 neotropical  
= *Lomaria* sect. Plagiogyria Kunze -- Farrnkr. 2: 61, 63 (1850)  
= *Polygramma* C.Presl -- Epimel. Bot. 156. 1851 \[Oct 1851\]

### Thyrsopteridaceae C.Presl -- Gefässbundel Farrn 38. 1847

1 genus, 1 sp.  
= Thyrsopteridoideae B.K.Nayar -- Taxon 19(2): 230. 1970  
= Thyrsopterideae Pfeiff. -- Nomencl. Bot. 2(2): 1411 (1874)

###### *Thyrsopteris* Kunze -- Linnaea 9(4): 507. 1835 \[1835 prim.\]

Distribution: Juan Fdz. Isl.  
= *Chonta* Molina -- Saggio storia nat. Chile 156 (1782)  
= *Panicularia* Colla -- Herb. Pedem. 6: 235. 1836 ; et in Mem. Reale Accad. Sci. Torino 39: 33 (Apr 1837)

## Polypodiales Link -- Hort. Berol. 2: 5 (1833) (Polypodiaceae)

= Aspleniales Pic. Serm. ex Reveal -- Phytologia 79: 72 (1996) (Order)  
= Athyriales Shmakov -- Turczaninowia 4: 55 (2001) (Order)  
= Blechnales Pic. Serm. ex Reveal -- Phytologia 74: 175 (1993) (Order)  
= Davalliales Schmakov -- Turczaninowia 12(3/4): 141 (2009)  
= Dennstaedtiales Doweld -- Tent. Syst. Pl. Vasc. x (2001) (Order)  
= Dryopteridales Shmakov -- Turczaninowia 4: 66, 67 (2001) (Order)  
= Filicales Dumort. -- Anal. Fam. Pl. 67 (1829), nom. illeg.  
= Lindsaeales Doweld -- New Syllabus: 353 (2006) (Order)  
= Lonchitidales Doweld -- New Syllabus: 353 (2006) (Order)  
= Monachosorales Doweld -- New Syllabus: 356 (2006) (Order)  
= Negripteridales Pic. Serm. ex Reveal -- Phytologia 74: 176 (1993) (Order)  
= Parkeriales A. B. Frank -- Syn. Pflanzenkd. (Leunis) ed. 2, 3: 1452, 1458 (1887) (Order)  
= Platyzomatales Pic. Serm. ex Reveal -- Phytologia 74: 176 (1993) (Order)  
= Pteridales Doweld -- Tent. Syst. Pl. Vasc. xi (2001) (Order)  
= Saccolomatales Doweld -- New Syllabus: 354 (2006) (Order)  
= Thelypteridales Doweld -- Tent. Syst. Pl. Vasc. xi (2001) (Order)  
= Davalliinae Payer -- Bot. Crypt.: 199 (1850)  
= Dennstaedtiidae Doweld -- Tent. Syst. Pl. Vasc. x (2001)  
= Polypodiinae Dumort. -- Anal. Fam. Pl.: 67 (1829)  
= Polypodiophyta Cronquist, Takht. & Zimmerm. -- Taxon 15: 133 (1966)  
= Polypodiophytina Reveal -- Phytologia 79: 70 (1996)  
= Polypodiopsida Cronquist, Takht. & Zimmerm. -- Taxon 15: 133 (1966)  
= Pteridopsida Ritgen -- Aufeinanderfolge Org. Gest.: 63 (1828) (Class)

### Arthropteridaceae Hong M.Liu, Hovenkamp & H.Schneid. -- Taxon 62(4): 697. 2013 \[21 Aug 2013\]

1 genus, 13 spp. The family was accepted as separate from Tectariaceae by PPG-II.

###### *Arthropteris* J.Sm. -- Bot. Antarct. Voy. II. (Fl. Nov.-Zel.). 43. 1854 \[27 Apr 1854\]

Distribution: Paleotropical to south-temperate, mostly trop. Africa and Madagascar, 2 Malesia, 4 Australia, not in America, but 1 sp. Juan Fernandez Islands  
= *Psammiosorus* C.Chr. -- Cat. Pl. Madag., Pterid. 33. 1932 \[Jul 1931, publ Feb 1932\] ; & Dansk Bot. Ark. 7. 73 t. 24. 1932

### Aspleniaceae Newman -- Hist. Brit. Ferns 6. 1840 \[1-5 Feb 1840\]

2(-6) genera, ca. 750 spp.  
= Asplenioideae Link -- Fil. Sp.: 73 (1841)  
= Asplenieae Gaudich. -- Freycinet, Voy. Uranie, Bot.: 311 (1828)  
= Aspleniinae Dumort. -- Anal. Fam. Pl.: 67 (1829)

###### *Asplenium* L. -- Sp. Pl. 2: 1078. 1753 \[1 May 1753\] ; & Gen. Pl. ed. 5, 485, 1754

Distribution: Worldwide. Inclusion of all formerly separate satellite genera fide Smith et al. (2006) and other recent authors. The separation of Hymenasplenium remains controversial.  
= *Acropteris* Link -- Hort. Berol. \[Link\] 2: 55. 1833 \[Jul-Dec 1833\]  
= *Amesium* Newman -- Hist. Brit. Ferns, ed. 2 10. 1844  
= *Antigramma* C.Presl -- Tent. Pterid. 120. 1836  
= *Asplenidictyum* J.Sm. in Hook. -- Icon. Pl. 10: t.937. 1854 \[25 Jan 1854\] , syn.; & Hist. Fil. 333. 1875  
= *Biropteris* Kümmerle -- Magyar Bot. Lapok 19: 2. 1922  
= *Boniniella* Hayata -- Bot. Mag. (Tokyo) 41: 709. 1927 ; & 42. 337. 1928; Flora 124. 50  
= *Caenopteris* P.J.Bergius -- Acta Acad. Sci. Imp. Petrop. 1782(2): 249. 1786 \[1782 publ 1786\]  
= *Camptosorus* Link -- Hort. Berol. \[Link\] 2: 69. 1833 \[Jul-Dec 1833\]  
= *Ceterach* Lam. & DC. -- Fl. Franc. \[de Candolle & Lamarck\], ed. 3. 2: 566. 1805 ; Willdenow, Enum. 1068. 1809; sp. pl. 5. 136. 1810  
= *Ceterachopsis* (J.Sm.) Ching -- Bull. Fan Mem. Inst. Biol. Bot. 10: 8. 1940  
= *Chamaefilix* Hill ex Farw. -- Amer. Midl. Naturalist 12: 239, 268. 1931  
= *Cheilosorum* J. Sm. -- Hist. Fil. 317 (1875)  
= *Cryptostigma* A.Braun -- Fil. Hort. Bot. Lips. 80. 1856 \[May-Jun 1856\]  
= *Darea* Juss. -- Gen. Pl. \[Jussieu\] 15. 1789 \[4 Aug 1789\] ; & Smith, Mem. Acad. Turin 5. 409 (1793)  
= *Dareastrum* Fée -- Mém. Foug. 5 (Gen. Filic.): 190 (1852)  
= *Diellia* Brack. -- U.S. Expl. Exped., Filic. 16: 217. 1854 ; C. Wilkes Expl. Exped.  
= *Diplora* Baker -- J. Bot. 11: 235. 1873  
= *Eremopodium* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 5(3): 589. 1877  
= *Glossopteris* Raf. -- J. Phys. Chim. Hist. Nat. Arts 89: 262. 1819  
= *Hemionites* J. Sm. -- Hist. Fil. 318 (1875)  
= *Hemionitidastrum* Fée -- Mém. Foug. 5 (Gen. Filic.): 190 (1852)  
= *Holodictyum* Maxon -- Contr. U.S. Natl. Herb. 10: 481. 1908  
= *Homatoneuron* Klotzsch -- Linnaea 20: 354 (1847)  
= *Lobium* Keyserl. -- Polyp. Herb. Bunge 15 (1873)  
= *Loxoscaphe* T.Moore -- Hooker’s J. Bot. Kew Gard. Misc. 5: 227. 1853  
= *Macrophyllidium* Rosenst. -- Repert. Spec. Nov. Regni Veg. 13: 216 (1914)  
= *Micrasplenium* Keyserl. -- Polyp. Herb. Bunge 15 (1873)  
= *Micropodium* Rchb. -- Consp. Regn. Veg. \[H.G.L.Reichenbach\] 185. 1828  
= *Myriotheca* Comm. ex Juss. -- Gen. Pl. \[Jussieu\] 15, 447. 1789 \[4 Aug 1789\]  
= *Neottopteridastrum* Fée -- Mém. Foug. 5 (Gen. Filic.): 190 (1852)  
= *Neottopteris* J.Sm. -- J. Bot. (Hooker) 3: 409. 1841 ; & 4: 175. 1841  
= *Notolepeum* Newman -- Hist. Brit. Ferns, ed. 2 9. 1844  
= *Onopteris* Neck. -- Elem. Bot. (Necker) 3: 316. 1790  
= *Parasplenium* Keyserl. -- Polyp. Herb. Bunge 15 (1873)  
= *Phyllitis* Hill -- Brit. Herb. 525, t. 74 (1756)  
= *Phyllitopsis* Reichst. -- Bot. Helv. 91: 107. 1981  
= *Pleurosorus* Fée -- Mém. Foug., 5. Gen. Filic. 179. 1852  
= *Schaffneria* Fée ex T.Moore -- Index Fil. (T.Moore) 1: liii. 1857  
= *Scolopendrium* Adans. -- Fam. Pl. (Adanson) 2: 20, 602. 1763 \[Jul-Aug 1763\] ; & Smith, Mem. Acad. Turin 5. 410. 1793  
= *Sinephropteris* Mickel -- Brittonia 28(3): 326. 1976  
= *Stormesia* J.Kickx f. -- Fl. Crypt. Louvain 8. 1835  
= *Tarachia* C.Presl -- Epimel. Bot. 74. 1851 \[Oct 1851\]  
= *Thamnopteris* C.Presl -- Epimel. Bot. 68. 1851 \[Oct 1851\]  
= *Trichomanes* Bubani -- Fl. Pyren. (Bubani) 4: 424. \[Dec 1901-Feb 1902\]  
= *Triphlebia* Baker -- Malesia 3: 41. 1886  
= Asplenium nothosubgen. Asplenoceterach (D.E.Mey.) Rosselló, Mus, Salvo & N.Torres -- Candollea 45(1): 80. 1990  
= Asplenium subgen. Phyllitopsis (Reichstein) Jermy & Viane -- Bot. J. Linn. Soc. 109(3): 322. 1992  
= xAsplenosorus Wherry -- Amer. Fern J. 27: 56 (1937), nomen  
= × *Asplenophyllitis* Alston -- Proc. Linn. Soc. London 152: 139. 1940  
= × *Ceterophyllitis* Pic.Serm. -- Webbia 34(1): 208. 1979

###### *Hymenasplenium* Hayata -- Bot. Mag. (Tokyo) 41: 712. 1927

Distribution: Mainly tropical Asia and China, few tropical America, 1 tropical Africa, few Pacific. Separation from Asplenium supported by Ohlsen et al. (2014).

### Athyriaceae Alston -- Taxon 5: 25. 1956 \[25 Mar 1956\]

6-7 genera, ca. 760 spp. Circumscription following Rothfels et al. (2012). According to Fraser-Jenkins et al. (2018) it should be included in Woodsiaceae s. lat.  
= Athyrioideae B.K.Nayar -- Taxon 19: 235. 1970  
= Deparioideae M.L.Wang & Y.T.Hsieh -- Acta Phytotax. Sin. 42(6): 526. 2004 \[Nov 2004\]  
= Diplazioideae Ching & Z. R. Wang -- Acta Phytotax. Sin. 35: 35 (1997)  
= Diplazioideae Shmakov -- Turczaninowia 4(1-2): 59 (2001), nom. superfl.  
= Diplazieae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1873)  
= Physematieae J. Sm. -- (1875)  
= Athyriinae Milde -- Bot. Zeitung (Berlin) 28: 332 (1870)  
= Diplaziinae Payer -- Bot. Crypt.: 198 (1850)

###### *Anisocampium* C.Presl -- Epimel. Bot. 58. 1851 \[Oct 1851\]

Distribution: E-Asia, S-Himalaya and Indochina, 1 to Sri Lanka and Malesia. Revision see Liu et al. (2011), systematics Wei et al. (2018). Fraser-Jenkins (2018) includes the genus in Athyrium s. lat.  
= *Kuniwatsukia* Pic.Serm. -- Webbia 28: 455. 1973 \[30 Dec 1973\]  
= *Microchlaena* Wight & Arn. -- Cat. Ind. Pl. 16 (1833).

###### *Athyrium* Roth -- Tent. Fl. Germ. 3(1.1): 31, 58. 1799 \[Jun-Sep 1799\] ; et in Arch. Bot. \[Leipzig\] 2(1): 106 (1799 publ May-Jul 1800)

Distribution: Worldwide, mostly northern hemisphere, many in China (over 100), several in trop. Africa and Madagascar, few in the New World.  
= *Hypochlamys* Fée -- Mém. Foug., 5. Gen. Filic. 200. 1852 \[1850-1852\]  
= *Neoathyrium* Ching & Z.R.Wang -- Acta Phytotax. Sin. 20(1): 76. 1982 \[18 Feb 1982\]  
= *Pseudocystopteris* Ching -- Acta Phytotax. Sin. 9(1): 76. 1964 \[18 Jan 1964\]  
= *Solenopteris* Zenker ms. ex Kunze -- Linnaea 24: 267 (1851)

###### *Cornopteris* Nakai -- Bot. Mag. (Tokyo) 44: 7. 1930

Distribution: China, E-Asia, N-trop. Asia. Fraser-Jenkins et al. (2018) make a strong argument to keep the genus separate from Athyrium s. lat., supported by molecular results (Wei et al. 2017)  
= *Athyrium* subgen. Cornopteris (Nakai) Seriz. -- J. Jap. Bot. 56(7): 194 (1981)

###### *Deparia* Hook. & Grev. -- Icon. Filic. 2(8): t.154. 1829 \[1829 or 1830\]

Distribution: Mostly China, some trop. Asia, Pacific, few Madagascar, 1 in North America  
= *Athyriopsis* Ching -- Acta Phytotax. Sin. 9(1): 63. 1964 \[18 Jan 1964\]  
= *Deparia* sect. Athyriopsis (Ching) M. Kato -- (1984)  
= *Deparia* sect. Dryoathyrium (Ching) M. Kato -- (1977)  
= *Deparia* sect. Lunathyrium (Koidz.) M. Kato -- (1977)  
= *Dictyodroma* Ching -- Acta Phytotax. Sin. 9(1): 57. 1964 \[18 Jan 1964\]  
= *Dryoathyrium* Ching -- Bull. Fan Mem. Inst. Biol. Bot. 11: 79. 1941  
= *Lunathyrium* Koidz. -- Acta Phytotax. Geobot. 1(1): 30. 1932 \[20 Apr 1932\]  
= *Lunathyrium* sect. Athyriopsis (Ching) Ohba -- (1965)  
= *Lunathyrium* sect. Dryoathyrium (Ching) Ohba -- (1965)  
= *Neotriblemma* Nakaike -- J. Nippon Fernist Club 3(Suppl. 2): 128. 2004 \[Feb. 2004\] , =Index to Scientific Names of Japanese Pteridophytes  
= *Parathyrium* Holttum -- Kew Bull. 13(3): 448, f.1(b). 1959 \[1958 publ. 11 May 1959\]  
= × *Depazium* Nakaike -- New Fl. Jap. Pterid. 840. 1992  
= × *Neotribleparia* Nakaike -- J. Nippon Fernist Club 3(Suppl. 2): 128. 2004 \[Feb. 2004\] \[Index to Scientific Names of Japanese Pteridophytes\]

###### *Diplazium* Sw. -- J. Bot. (Schrader) 1800(2): 4, 61. 1801 \[Oct-Dec 1801\]

Distribution: Cosmopolitan, 100 spp. in tropical America, ca. 80 in China. Phylogeny and inclusion of Allantodia, Callipteris and Monomelangium see Wei et al. (2013). Several new species await description in Taiwan (Knapp, in litt. 2016)  
= *Allantodia* R. Br. -- Prodr. Fl. Nov. Holland. 149 (1810)  
= *Allantodia* Wall. -- Pl. asiat. rar. 1: 44, t. 22 (1830) (non R. Br. (1810))  
= *Anisogonium* C.Presl -- Tent. Pterid. 115. 1836  
= *Arcasplenium* T.Moore -- Bull. Misc. Inform. Kew 1901(175-177): 145. \[Jul-Sep 1901\]  
= *Brachysorus* C.Presl -- Epimel. Bot. 70. 1851 \[Oct 1851\]  
= *Callipteridastrum* Fée -- Mém. Foug. 5 (Gen. Filic.): 213 (1852)  
= *Callipteris* Bory -- Voy. Iles Afrique 1: 282. 1804 \[Sep 1804\]  
= *Didymochlamys* Hook.f. -- Hooker’s Icon. Pl. 14: t. 1122. 1872 \[Aug 1872\]  
= *Digrammaria* C.Presl -- Tent. Pterid. 116. 1836  
= *Lotzea* Klotzsch & H.Karst. -- Linnaea 20(3): 358. 1847 \[Jun 1847\]  
= *Microstegia* C.Presl -- Epimel. Bot. 90. 1851 \[Oct 1851\]  
= *Monomelangium* Hayata -- Bot. Mag. (Tokyo) 42: 343. 1928  
= *Ochlogramma* C.Presl -- Epimel. Bot. 93. 1851 \[Oct 1851\]  
= *Oxygonium* C.Presl -- Tent. Pterid. 117. 1836  
= *Pteriglyphis* Fée -- Congr. Sci. France 10(1): 178. 1843 ; & Gen. Fil. 219. 1850-52

###### *Ephemeropteris* R.C.Moran & Sundue -- Taxon 68(3): 432. 2019 \[19 Aug 2019\] \[epublished\]

Distribution: Mexico to Venezuela

###### *Pseudathyrium* Newman -- Phytologist 4: 370. 1851

Distribution: Europa, W-Asia. Separation from Athyrium supported by molecular results (Wei et al. 2017), sister to Cornopteris.

###### × *Apseudathyrium* Xia Wan & Li Bing Zhang -- Phytotaxa 575(1): 104. 2022 \[6 Dec 2022\] \[epublished\]

Distribution: Europe  
= × *Schnellerathyrium* Hong M.Liu, Schuettp. & H.Schneid. -- J. Syst. Evol. 58(6): 999. 2020 \[21 May 2020\] \[epublished\]

###### × *Cornoathyrium* Nakaike -- New Fl. Jap. Pterid. 840. 1992

Distribution: mostly E-Asia. If Cornopteris is kept separate on phylogenetic grounds, this hybrid genus also has to be kept.

### Blechnaceae Newman -- Hist. Brit. Ferns, ed. 2 8. 1844

7-24 genera, ca. 260 spp. Systematics following revision of Gasper et al. (2016)

#### Blechnoideae Hook. -- Sp. Fil. 3: 1 (1859)

= Blechnoideae Gasper, V. A. O. Dittrich & Salino -- Phytotaxa 275(3): 201 (2016), nom. superfl.  
= Lomarioideae Hook. -- Sp. Fil. 3: 1 (1859)  
= Blechneae C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 463 (1851)  
= Doodieae Gaudich. -- Freycinet, Voy. Uranie, Bot.: 400 (1829)  
= Lomarieae Hance -- J. Bot. 3: 342 (1865)  
= Blechninae Coss. & Germ. -- Syn. Anal. Fl. Environ. Paris, ed. 3: 574 (1876)

###### *Austroblechnum* Gasper & V.A.O.Dittrich -- Phytotaxa 275(3): 202. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: Tropical to south-tropical, many in temperate South America, Pacific and New Zealand, few trop. America (north to Mexico and Caribbean), Madagascar, Malesia

###### *Blechnidium* T.Moore -- Brit. Ferns \[T. Moore\] 2: 210. 1860

Distribution: China and Taiwan to NE-India

###### *Blechnopsis* C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 115 (1851)

Distribution: Asia, Pacific

###### *Blechnum* L. -- Sp. Pl. \[Linnaeus\] 2: 1077. 1753 \[1 May 1753\] ; et in Genera Plantarum ed. 5: 485 (1754).

Distribution: Mostly neotropical, few southern Africa  
= *Blechnopteris* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 166. 1851  
= *Distaxia* C.Presl -- Epimel. Bot. 110. 1851 \[Oct 1851\]  
= *Mesothema* C.Presl -- Epimel. Bot. 111. 1851 \[Oct 1851\]

###### *Brainea* J.Sm. -- Cat. Ferns Kew 5. 1856

Distribution: Trop. Asia  
= *Bowringia* Hook. -- Hooker’s J. Bot. Kew Gard. Misc. 5: 237. 1853

###### *Cleistoblechnum* Gasper & Salino -- Phytotaxa 275(3): 207. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: China, Taiwan

###### *Cranfillia* Gasper & V.A.O.Dittrich -- Phytotaxa 275(3): 207. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: Malesia (4), many Pacific, neotropical (4)

###### *Diploblechnum* Hayata -- Bot. Mag. (Tokyo) 41: 702. 1927 \[1928?\]

Distribution: Malesia, Australia, Pacific  
= *Pteridoblechnum* Hennipman -- Blumea 13(2): 397. 1966 \[16 Feb 1966\]  
= *Steenisioblechnum* Hennipman -- Blumea 30(1): 17. 1984

###### *Doodia* R.Br. -- Prodr. Fl. Nov. Holland. 151. 1810 \[27 Mar 1810\]

Distribution: Australia, New Zealand, Pacific to Hawaii

###### *Icarus* Gasper & Salino -- Phytotaxa 275(3): 209. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: New Zealand

###### *Lomaria* Willd. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 3: 160. 1809

Distribution: South America, South Africa, Australia, New Caledonia  
= *Stegania* R.Br. -- Prodr. Fl. Nov. Holland. 152. 1810 \[27 Mar 1810\]

###### *Lomaridium* C.Presl -- Epimel. Bot. 154. 1851 \[Oct 1851\]

Distribution: Neotropics, trop. E-Africa, Madagascar, 1 Australasia

###### *Lomariocycas* (J.Sm.) Gasper & A.R.Sm. -- Phytotaxa 275(3): 212. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: Neotropics, Africa, Madagascar

###### *Neoblechnum* Gasper & V.A.O.Dittrich -- Phytotaxa 275(3): 214. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: Neotropics

###### *Oceaniopteris* Gasper & Salino -- Phytotaxa 275(3): 214. 2016 \[21 Sep 2016\] \[epublished\]

Distribution: Malesia, W-Pacific, Australia

###### *Parablechnum* C.Presl -- Epimel. Bot. 109. 1851 \[Oct 1851\]

Distribution: Pantropical  
= *Lomaria* subgen. Paralomaria Fée -- Mém. Foug. 5 (Gen. Filic.): 68 (1852)  
= *Orthogramma* C.Presl -- Epimel. Bot. 121. 1851 \[Oct 1851\] ; =Abh. Kongl. Bohm. Wiss. ser. 2, 6 (Oct. 1851) 481

###### *Sadleria* Kaulf. -- Enum. Filic. 161. 1824 \[8 Apr-28 May 1824\]

Distribution: Hawaii

###### *Spicantopsis* Nakai -- Bot. Mag. (Tokyo) 47(555): 180. 1933 \[20 Mar 1933\]

Distribution: E-Asia. Circumscription: Molino et al. (201)

###### *Struthiopteris* Scop. -- Meth. Pl. 25 (1754), et Fl. Carn. 168 (1760)

Distribution: E-Asia (1), holarctic (2)  
= *Homophyllum* Merino -- Contr. Fl. Galicia Suppl. 1: 7-8. 1898  
= *Spicanta* C.Presl -- Epimel. Bot. 114. 1851 \[Oct 1851\] ; later publ.: Abh. Königl. Böhm. Ges. Wiss. ser. 5, 6: 474. Oct 1851; O. Ktze. Rev. Gen. Pl. 2. 820. 1891

#### Stenochlaenoideae J.P.Roux -- Conspect. South. Afr. Pteridophyta 156. 2001

= Stenochlaenaceae Ching -- Acta Phytotax. Sin. 16(4): 18. 1978  
= Stenochlaeneae Small -- Fern Trop. Florida: 12 (1918)

###### *Salpichlaena* J.Sm. -- J. Bot. (Hooker) 4: 168. 1841 \[Aug 1841\]

Distribution: Tropical America. Revision: Cárdenas et al. (2019). Genus listing revised by H. Tuomisto (2021)

###### *Stenochlaena* J.Sm. -- J. Bot. (Hooker) 3: 401. 1841 ; 4: 149. 1841

Distribution: India to NE-Australia, east to W-Pacific, 1 trop. Africa  
= *Cafraria* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(6) (Epim. Bot.): 166 (1851)  
= *Lomariobotrys* Fée -- Mém. Foug., 5. Gen. Filic. 45. 1852 \[1850-1852\]

###### *Telmatoblechnum* Perrie, D.J.Ohlsen & Brownsey -- Taxon 63(4): 755. 2014 \[28 Aug 2014\]

Distribution: Trop. Asia, Australia (1), trop. America to Florida (1)  
= *Blechnopsis* Sect. Diafnia C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(6) (Epim. Bot.): 119 (1851)

#### Woodwardioideae Gasper, V.A.O.Dittrich & Salino -- Phytotaxa 275(3): 197. 2016 \[21 Sep 2016\] \[epublished\]

###### *Anchistea* C.Presl -- Abh. Königl. Böhm. Ges. Wiss. ser. 5, 6: 431. 1851 \[Oct 1851\] ; alt. publ.: Epimel. Bot. 71. Oct 1851.

Distribution: North America

###### *Lorinseria* C.Presl -- Epimel. Bot. 72. 1851 \[Oct 1851\]

Distribution: North America

###### *Woodwardia* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5: 411. 1793 ; Cf. Nakai, Bot. Mag. Tokyo 39. 101. 1925 et Ching,Bull. Fan Mem. Inst. 2. 1. 1931.

Distribution: Widespread in northern hemisphere, south to Costa Rica, W-Indonesia, mainly E-Asia, America (3)  
= *Chieniopteris* Ching -- Acta Phytotax. Sin. 9(1): 37. 1964 \[18 Jan 1964\]  
= *Woodwardia* sect. Chieniopteris (Ching) Cranfill -- Pteridol. New Millennium 45 (2003)

### Cystodiaceae J.R.Croft -- Kew Bull. 41(4): 797. 1986 \[20 Oct 1986\]

1 genus, 1 sp.

###### *Cystodium* J.Sm. -- Gen. Fil. \[Hooker\] ad t. 96. 1841

Distribution: Malesia  
= *Cystodiopteris* Rauschert -- Taxon 31(3): 555. 1982 , nom. nov.

### Cystopteridaceae (Payer) Shmakov -- Turczaninowia 4(1-2): 60 (2001).

3-4 genera, ca. 35 spp. Family status confirmed by Rothfels et al. (2012)  
= Cystopterioideae Ching & Z.R.Wang -- Acta Phytotax. Sin. 35(1): 34. 1997  
= Cystopteridinae Payer -- Bot. Crypt.: 198 (1850) (Cystopterideae)

###### *Acystopteris* Nakai -- Bot. Mag. (Tokyo) 47: 180. 1933

Distribution: Himalaya to Japan and Malesia. Valid genus separate from Cystopteris fide Fraser-Jenkins et al. (2018)  
= *Cystopteris* subgen. Acystopteris (Nakai) Blasdell -- Mem. Torrey Bot. Club 21(4): 49 (1963)

###### *Cystopteris* Bernh. -- Neues J. Bot. 1(2): 5, 26. 1805 \[Oct-Nov 1805\]

Distribution: Worldwide, mountains in tropics. There are probably many more cryptic species to be described, based on phylogenetics.  
= *Cyclopteris* Gray -- Nat. Arr. Brit. Pl. 2: 9. 1821  
= *Cyste* Dulac -- Fl. Hautes-Pyrénées 33. 1867  
= *Cystea* Sm. -- Engl. Fl. 4: 260, 284. 1828  
= *Cystoathyrium* Ching -- Acta Phytotax. Sin. 11(1): 22. 1966 \[17 Jan 1966\]  
= *Filicula* Ség. -- Pl. Veron. 3: 55. 1754 \[Jul-Aug 1754\]  
= *Filix* Adans. -- Fam. Pl. 2: 20, 558 (1763) (non Ludwig, Instit. Hist. Phys. Regni Veg. ed. II: 142 (1757))  
= *Filix*-fragilis Gilib. -- Exerc. Phyt. 2: 558 (1792)  
= *Rhizomatopteris* A.P.Khokhr. -- Fl. Magadan. Obl. 347. 1985

###### *Gymnocarpium* Newman -- Phytologist 4: 371. 1851

Distribution: 5 spp. north-temperate, 1 sp. Taiwan, 1 Himalaya to New Guinea  
= *Carpogymnia* D.Löve & Á.Löve -- Univ. Colorado Stud. Ser. Biol. 24: 8. 1966  
= *Currania* Copel. -- Philipp. J. Sci., C 4: 112. 1909

###### × *Cystocarpium* Fraser-Jenk. -- Taxon. Revis. Indian Subcontinental Pteridophytes 207. 2008 \[27 Nov 2008\]

Cystopteris x Gymnocarpium

### Davalliaceae M.R.Schomb. -- Reis. Br.-Guiana \[Ri. Schomburgk\] 2: 883. 1848 \[12-15 Jul 1848\]

1-4 genera, ca. 60 spp. In the newest revision by Tsutsumi et al. (2016) all genera are merged into one Davallia sensu lato. Gymnogrammitis and Leucosoria have been moved to other families. As with other genera, we prefer not to merge everything into one monster genus and keep Davallodes separate.  
= Davallioideae Hook. -- Sp. Fil. 1: 150 (1845)  
= Davallieae Gaudich. -- Voy. Uranie \[Freycinet\] 370 (1829)

###### *Davallia* Sm. -- Mém. Acad. Roy. Sci. Turin 5: 414, t.9(6). 1793

Distribution: Mostly trop. and subtrop. Asia, some Pacific and Australia, few in Canary Isl. (1) and trop. Africa (1). Systematics in Malesia following for better alternatives mostly Nooteboom (1994), who sank too much into synonymy fide Fraser-Jenkins (2008).  
= *Araiostegiella* M. Kato & Tsutsumi -- Acta Phytotax. Geobot. 59(1): 6 (2008)  
= *Colposoria* C. Presl -- Tent. Pterid. 128 (1836)  
= *Davallia* sect. Araiostegiella (M. Kato & Tsutsumi) Tsutsumi & M. Kato -- Taxon 65(6): 1245 (2016)  
= *Humata* Cav. -- Descr. Pl. (Cavanilles) 272. 1802  
= *Pachypleuria* C.Presl -- Epimel. Bot. 98. 1851 \[Oct 1851\]  
= *Paradavallodes* Ching -- Acta Phytotax. Sin. 11(1): 18. 1966 \[17 Jan 1966\]  
= *Parasorus* Alderw. -- Bull. Jard. Bot. Buitenzorg sér. 3, 4: 317. 1922  
= *Parestia* C.Presl -- Epimel. Bot. 99. 1851 \[Oct 1851\]  
= *Pteroneuron* DC. ex Meisn. -- Pl. Vasc. Gen. \[Meisner\] 10. 1837 : orth. var. of Pteroneurum DC.  
= *Scyphularia* Fée -- Mém. Foug., 5. Gen. Filic. 324. 1852 ; & Copeland, Phil. Journ. Sci. 34. 254. 1927.  
= *Stenochlamys* Griff. -- Not. Pl. Asiat. 2: 610. 1849  
= *Stenolobus* C.Presl -- Tent. Pterid. 130. 1836  
= *Trogostolon* Copel. -- Philipp. J. Sci. 34: 251. 1927  
= *Wibelia* Bernh. -- J. Bot. (Schrader) 1800(2): 122 (1801), nom. illeg. (non Fée 1852)

###### *Davallodes* (Copel.) Copel. -- Philipp. J. Sci., C 3: 33 (1908)

Distribution: trop. and subtrop. Asia  
= *Araiostegia* Copel. -- Philipp. J. Sci. 34: 240. 1927 ; & Univ. Calif. Publ. Bot. 16. 97, 12. 399. 1931 (clavis sp.)  
= *Davallia* sect. Davallodes (Copel.) Tsutsumi & M. Kato -- Taxon 65(6): 1246 (2016)  
= *Katoella* Fraser-Jenk. -- Ferns Fern-Allies Nepal 1: 33. 2015 \[12 Apr 2015\]  
= *Microlepia* sect. Davallodes Copel. -- Polyp. Philipp. 55 (1905)

### Dennstaedtiaceae Pic.Serm. -- Webbia 24(2): 704. 1970 \[28 Apr 1970\]

11 genera, ca. 230 spp. Phylogeny: Triana-Moreno et al. (2023)  
= Hypolepidaceae Pic.Serm. -- Webbia 24(2): 705. 1970 \[28 Apr 1970\]  
= Monachosoraceae Ching -- Acta Phytotax. Sin. 14: 17 (1978)  
= Pteridiaceae Ching -- Acta Phytotax. Sin. 13(1): 96. 1975

#### Dennstaedtioideae -- NA

= Microlepieae Kuhn -- Chaetopterides: 4 (1882)  
= Dennstaedtiinae Prantl -- Arbeiten Königl. Bot. Gart. Breslau 1: 8 (1892)

###### *Dennstaedtia* T. Moore -- Index Filic. (T. Moore) 97 (1859), nom. cons.

Distribution: Mostly tropical/subtropical, 12 neotropical  
= *Costaricia* Christ -- Bull. Soc. Bot. Genève ser. 2, 1: 229. 1909  
= *Leptolepia* Mett. ex Kuhn -- Chaetopterides 348. 1882  
= *Litolobium* Newman -- Phytologist 5: 236. 1854  
= *Oenotrichia* Copel. -- Univ. Calif. Publ. Bot. 16: 82. 1929  
= *Paradennstaedtia* Tagawa -- J. Jap. Bot. 27: 213. 1952  
= *Patania* C.Presl -- Tent. Pterid. 137. 1836

###### *Microlepia* C.Presl -- Tent. Pterid. 124, t.4(21-23). 1836 \[ante-2 Dec 1836\]

Distribution: Pantropical, mostly tropical Asia, China (24), 1 adventive to tropical America  
= *Dennstaedtia* Bernh. -- J. Bot. (Schrader) 3(2): 124. 1801 \[Apr 1801\]  
= *Scyphofilix* Thouars -- Gen. Nov. Madagasc. 1. 1806 \[17 Nov 1806\] ; & Romer, Collect. Bot.: 195 (1809).  
= *Scypholepia* J.Sm. -- Hist. Fil. 261. 1875  
= *Scyphopteris* Raf. -- Princ. Fond. Somiol. 26. 1814 \[Sep-Dec 1814\]

###### *Mucura* L.A.Triana & Sundue -- Taxon 72(1): 40. 2022 \[14 Dec 2022\] \[epublished\]

Distribution: South and Central America north to S-USA

###### *Sitobolium* Desv. -- Mém. Soc. Linn. Paris 6(3): 262. 1827 \[Jul 1827\] ; & Prodr. Foug.

Distribution: trop. Asia, E-Asia, 1 temperate North America  
= *Adectum* Link -- Fil. Spec. 41, 42. 1841  
= *Coptidipteris* Nakai & Momose -- Cytologia (Fujii Jub. vol. 1): 365. 1937  
= *Emodiopteris* Ching & S.K.Wu -- Acta Phytotax. Sin. 16(4): 21. 1978 \[18 Nov 1978\]  
= *Fuziifilix* Nakai & Momose -- Cytologia (Fujii Jub. Vol.): 365. 1937

#### Hypolepidoideae Lovis -- NA

= Hypolepidinae Pfeiff. -- Nomencl. Bot. 1(1): 704 (1873)

###### *Blotiella* R.M.Tryon -- Contr. Gray Herb. 191: 96. 1962

Distribution: Africa and Madagascar (19 spp.), 1 sp. Neotropics

###### *Histiopteris* (J. Agardh) J. Sm. -- Hist. Fil. 294 (1875)

Distribution: Mostly Malesia, 1 sp. pantropical  
= *Lepidocaulon* Copel. -- Univ. Calif. Publ. Bot. 18: 218. 1942  
= *Pteris* subgen. Histiopteris J. Agardh -- Recens. Spec. Pter. 76 (1839)

###### *Hiya* H.Shang -- Molec. Phylogen. Evol. 126: 457. 2018 \[1 May 2018\] \[epublished\]

Distribution: Malesia (2 spp.), SW-Pacific (1 sp.), trop. America (1 sp.)

###### *Hypolepis* Bernh. -- Neues J. Bot. 1(2): 34. 1805

Distribution: Worldwide tropical/subtropical

###### *Paesia* A.St.-Hil. -- Voy. Distr. Diam. 1: 381. 1833

Distribution: Taiwan and Sumatra to New Caledonia and New Zealand, 3 tropical America

###### *Pteridium* Gled. ex Scop. -- Fl. Carniol. 169. 1760 \[15 Jun-21 Jul 1760\]

Distribution: Worldwide. Fraser-Jenkins et al. (2015) treat most of the taxa as separate species. Zhou et al. (2014) argue for keeping only two diploid species and two tetraploids, treating the rest of the taxa as geographically isolated subspecies.  
= *Aquilina* C.Presl -- Farnkr. Jetztw. 91. 1864  
= *Cincinalis* Gled. -- Syst. Pl. Stamin. Situ: 290 (1764)  
= *Eupteris* Newman -- Phytologist 2: 278. 1845  
= *Filix* Ludw. -- Inst. Reg. Veg., ed. 2: 142 (1757), nom. illeg.  
= *Filix*-Foemina Hill -- Family Herbal (1755)  
= *Filix*-foemina Hill ex Farw. -- Amer. Midl. Naturalist 12: 290 (1931)  
= *Nymphopteris* Webb & Berthel. -- Hist. nat. Canar. 82 (1763)  
= *Ornithopteris* (J. Agardh) J. Sm. -- Hist. Fil. 297 (1875) (non Bernh. 1806)

#### Monachosoroideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 155. 1975

= Monachosoreae R. M. Tryon & A. F. Tryon -- Rhodora 84: 126 (1982)

###### *Monachosorum* Kunze -- Bot. Zeitung (Berlin) 6: 119. 1848

Distribution: C-Himalaya and Yunnan to Honshu, Taiwan to Philippines and Borneo, New Guinea  
= *Monachosorella* Hayata -- Bot. Mag. (Tokyo) 41: 573, 642, f. 1927 ; & Flora 124. 44  
= *Ptilopteris* Hance -- J. Bot. 22: 138. 1884

### Desmophlebiaceae Mynssen, A.Vasco, Sylvestre, R.C.Moran & Rouhan -- Taxon 65(1): 26. 2016 \[8 Mar 2016\]

1 genus, 2 spp.

###### *Desmophlebium* Mynssen, A.Vasco, Sylvestre, R.C.Moran & Rouhan -- Taxon 65(1): 27. 2016 \[8 Mar 2016\]

Distribution: Trop. America

### Didymochlaenaceae Ching ex Li Bing Zhang & Liang Zhang -- Taxon 64(1): 34. 2015 \[2 Mar 2015\]

1 genus, 22 spp. Frequently included in Hypodematiaceae

###### *Didymochlaena* Desv. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 5: 303. 1811

Distribution: Tropics of the Old World, 1 pantropics. Revision: Shang & Zhang (2023).  
= *Hippodium* Gaudich. -- Voy. Uranie \[Freycinet\] 340. 1828  
= *Hysterocarpus* Langsd. -- Mém. Foug., 5. Gen. Filic. 216. 1852 1850-1852  
= *Monochlaena* Cass. -- Dict. Sci. Nat., ed. 2. \[F. Cuvier\] 50: 496. 1827 \[Nov 1827\]  
= *Tegularia* Reinw. -- Syll. Pl. Nov. 2: 3. 1825

### Diplaziopsidaceae X.C.Zhang & Christenh. -- Phytotaxa 19: 15. 2011 \[18 Feb 2011\]

2 genera, 3-4 spp. Family status confirmed by Rothfels et al. (2012)

###### *Diplaziopsis* C.Chr. -- Index Filic. 227. 1905

Distribution: E- and tropical Asia (2-3), North America (1)  
= *Homalosorus* Pic.Serm. -- Webbia 31(1): 246. 1977

### Dryopteridaceae Ching -- Acta Phytotax. Sin. 10: 2. 1965

26 genera, ca. 2100 spp.  
= Aspidiaceae Burnett -- Outl. Bot.: 324, 1156 (1835), nom. illeg.  
= Aspidiaceae Mett. ex A. B. Frank -- Leunis, Syn. Pflanzenk. ed. 2. 3: 1469 (1877), nom. illeg.  
= Bolbitidaceae (Pic.Serm.) Ching -- Acta Phytotax. Sin. 16(3): 15. 1978  
= Elaphoglossaceae Pic.Serm. -- Webbia 23: 209. 1968. 1968  
= Filicaceae Juss. -- Gen. Pl. 14. (1789), as ‘Filices’, nom. illeg., rej.  
= Peranemataceae (C. Presl) Ching -- Sunyatsenia 5: 246 (1940), nom. rej.

#### Dryopteridoideae B.K.Nayar -- Taxon 19: 235. 1970

= Peranematoideae Fraser-Jenk. -- New Sp. Syndr. Indian Pteridol. 297. 1997  
= Polystichoideae Fraser-Jenk. -- New Sp. Syndr. Indian Pteridol. 297. 1997  
= Dryopterideae Ching -- Acta Phytotax. Sin. 10: 2 (1965)  
= Peranemateae C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 4, 5: 64 (1836)  
= Polysticheae Tod. -- Syn. Pl. Acot. Vasc.: 33 (1866)  
= Peranematinae Trevis. -- Nuovo Giorn. Bot. Ital. 7: 159 (1875)

###### *Arachniodes* Blume -- Enum. Pl. Javae 2: 241. 1828

Distribution: Mostly China and E-Asia, 4-5 New World. Revision: Lu et al. (2018)  
= *Byrsopteris* C.V.Morton -- Amer. Fern J. 50(1): 149. 1960 \[25 Apr 1960\]  
= *Leptorumohra* (H. Itô) H. Itô -- Nakai & Honda, Nov. Fl. Jap. 4: 101 (1939)  
= *Lithostegia* Ching -- Sinensia 4: 2. 1933  
= *Phanerophlebiopsis* Ching -- Acta Phytotax. Sin. 10(2): 115, t.21. 1965 \[17 Apr 1965\]  
= *Rumohra* sect. Leptorumohra H. Itô -- Nakai & Honda, Nov. Fl. Jap. 11: 579 (1935)  
= × *Leptoarachniodes* Nakaike -- New Fl. Jap. Pterid. 841. 1992

###### *Atalopteris* Maxon & C.Chr. -- Contr. U.S. Natl. Herb. 24: 55. 1922

Distribution: Greater Antilles, all species very rare and insufficiently known. Taxonomic placement uncertain, possibly a synonym of Ctenitis.

###### *Ctenitis* C. Chr. ex C. Chr. -- Verd., Man. Pterid. 543 (1938)

Distribution: Tropical America (over 60), trop. Africa (1), Indian Ocean (39), trop. Asia, but not in Australia. Revision for South America: Viveros et al. (2017)  
= *Ataxipteris* Holttum -- Blumea 30(1): 10. 1984  
= *Dryopteris* subgen. Ctenitis C. Chr. -- Biol. Arb. tilegn. Eug. Warming 77 (1911)  
= *Pseudotectaria* Tardieu -- Notul. Syst. (Paris) 15: 87, t.6. 1955

###### *Cyrtomium* C.Presl -- Tent. Pterid. 86, t.2(26). 1836

Distribution: Mostly China, E-Asia, 2 spp. trop. and South Africa

###### *Dryopteris* Adans. -- Fam. Pl. (Adanson) 2: 20, 551. 1763 \[Jul-Aug 1763\] , as ‘Druopteris’

Distribution: Northern temperate zone (over 150 spp. in China and Taiwan), tropical mountains, only 22 New World. Inclusion of all the satellite genera like Acrorumohra, Adenoderris, Peranema, Diacalpe, Dryopsis, Nothoperanema etc. fide Zhang (2012) and others, based on molecular results. Fraser-Jenkins et al. (2018) argue for keeping some genera distinct, like Dryopsis, Stenolepia and Nothoperanema.  
= *Acrophorus* C.Presl -- Tent. Pterid. 93. 1836  
= *Acrorumohra* (H. Itô) H. Itô -- Nakai & Honda, Nov. Fl. Jap. 4: 101 (1939) (fide Zhang (2012))  
= *Anopodium* J. Sm. -- Cat. Cult. Ferns 16 (1857)  
= *Arsenopteris* Webb & Berthel. -- Hist. nat. Canar. 82, pars 3: 437 (1847)  
= *Arthrobotrys* Wall. -- Numer. List \[Wallich\] n. 395. 1829 1828  
= *Catapodium* Link -- Hort. Berol. \[Link\] 1: 380, 44. 1827 \[1 Oct-27 Nov 1827\]  
= *Ctenitis* subgen. Dryopsis Ching -- Bull. Fan Mem. Inst. Biol. Bot. 8: 280 (1938)  
= *Desmopodium* J.Sm. -- Index Fil. (T.Moore) 14-15: 308. 1861  
= *Diacalpe* Blume -- Enum. Pl. Javae 2: 241. 1828  
= *Dichasium* (A.Braun) Fée -- Mém. Foug., 5. Gen. Filic. 302. 1852 \[1850-1852\]  
= *Diclisodon* T.Moore -- Index Fil. (T.Moore) 2: xcv. 1857  
= *Dryopsis* Holttum & Edwards -- Kew Bull. 41: 179 (1986) (fide Zhang (2012))  
= *Dryopteris* sect. Dryopsis (Holttum & P. J. Edwards) Li Bing Zhang -- Phytotaxa 71: 18 (2012)  
= *Dryopteris* sect. Stenolepia (Alderw.) L. Y. Kuo & Y. H. Chang -- Syst. Bot. 41(3): 603 (2016)  
= *Dryopteris* subgen. Lophodium (Newman) Tzvelev -- Novosti Sist. Vyssh. Rast. 35: 10 (2003)  
= *Filix* Ség. -- Pl. Veron. 3: 53 (1754), nom. rej.  
= *Filix*-mas Hill ex Farw. -- Amer. Midl. Naturalist 12: 235, 253 (1931)  
= *Gleichenia* Neck. -- Elem. Bot. (Necker) 3: 314. 1790  
= *Gymnothalamium* Zenker -- Linnaea 24(3): 287. 1851 \[Sep 1851\]  
= *Lophodium* Newman -- Phytologist 4: 371, app. XVI. 1851  
= *Megalastrum* J. Sm. -- Hist. Fil. 216 (1875)  
= *Microdictyon* Fée -- Mém. Foug. 11 (Hist. Foug. Antil.): 66 (1866)  
= *Monophlebia* T. Moore -- Index Filic. (T. Moore) 89 (1857)  
= *Nematopera* Kunze -- Bot. Zeitung (Berlin) 797. 1845 , corr. nom.  
= *Nephrodium* Rich. -- Cat. Pl. Jard. Méd. Paris 120. 1801 ; & Michaux. Fl. bor. Am. 2. 266. 1803  
= *Nothoperanema* (Tagawa) Ching -- Acta Phytotax. Sin. 11(1): 25. 1966 \[17 Jan 1966\]  
= *Oligocampia* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 165. 1851  
= *Pachyderris* J.Sm. -- Index Fil. (T.Moore) 6: cxlvi. 1859  
= *Peranema* D.Don -- Prodr. Fl. Nepal. 12. 1825 \[26 Jan-1 Feb 1825\]  
= *Podeilema* R.Br. -- Pl. Asiat. Rar. (Wallich). 1: 42. 1830  
= *Psidopodium* Neck. -- Elem. Bot. (Necker) 3: 315. 1790  
= *Pteris* Gled. -- Syst. Pl. \[Gleditsch\] 289. 1764 \[ante 13 Sep 1764\] ; & Verm. Abh. 1: 24. 1765  
= *Pycnopteris* T.Moore -- Gard. Chron. 1855: 468.  
= *Revwattsia* D.L.Jones -- Fl. Australia 48: 711. 1998 \[27 Oct 1998\]  
= *Rumohra* sect. Acrorumohra H. Itô -- J. Jap. Bot. 11: 583 (1935)  
= *Sphaeropteris* R. Br. ex Wall. -- Pl. asiat. rar. 1: 41 (1830) (nom. illeg.)  
= *Stenolepia* Alderw. -- Bull. Dépt. Agric. Indes Néerl. 27: 45. 1909  
= *Syneuron* J. Sm. ms. ex Hook. -- Hooker’s Icon. Pl. 6: t.950 (1854)

###### *Phanerophlebia* C.Presl -- Tent. Pterid. 84. 1836

Distribution: Mexico, Central America, West Indies

###### *Polystichum* Roth -- Tent. Fl. Germ. 3(1.1): 31, 69. 1799 \[Jun-Sep 1799\]

Distribution: Nearly worldwide, 55 in trop. America, more than half (224) in China. Many undescribed species remain (Le Pechon et al. 2016), but several species in China will probably still turn out to be synonyms.  
= *Acropelta* Nakai -- Bull. Natl. Sci. Mus. Tokyo 33: 5. 1953  
= *Adenoderris* J.Sm. -- Hist. Fil. 222. 1875  
= *Aetopteron* Ehrh. ex House -- Amer. Fern J. 10(3): 88. 1920 \[21 Sep 1920\] ; et in Ehrh., Beitr. 4: 148 (1789), as a nom. nud.,  
= *Amblia* C.Presl -- Tent. Pterid. 184. 1836 ; & Amblya Fee, Gen. 283. 1850-52  
= *Cyrtogonellum* Ching -- Bull. Fan Mem. Inst. Biol. Bot. 8: 327. 1938  
= *Cyrtomidictyum* Ching -- Bull. Fan Mem. Inst. Biol. Bot. 10: 182. 1940  
= *Hemesteum* H.Lév. -- Fl. Kouy-Tcheou 496. 1915 , non Hemestheum Newman 1851  
= *Hemigonum* J. Sm. -- Hist. Fil. 204 (1875)  
= *Hypopeltis* Michx. -- Fl. Bor.-Amer. (Michaux) 2: 226. 1803 , in obs.; & Bory, Bel. Voy. Bot. 2. 63. 1833  
= *Papuapteris* C.Chr. -- Brittonia 2: 300, f.2. 1937  
= *Plecosorus* Fée -- Mém. Foug., 5. Gen. Filic. 150. 1852 \[1850-1852\]  
= *Polystichum* sect. Sorolepidium (Christ) Tagawa -- Acta Phytotax. Geobot. 9: 122 (1940)  
= *Porpaea* C.Presl -- Farnkr. Jetztw. 174. 1864  
= *Sorolepidium* Christ -- Bot. Gaz. 51: 350. 1911

###### × *Dryostichum* W.H.Wagner -- Canad. J. Bot. 70(2): 247. 1992

Dryopteris x Polystichum  
= × *Polysticalpe* Fraser-Jenk. -- New Sp. Syndr. Indian Pteridol. 300. 1997

#### Elaphoglossoideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 154. 1975

= Bolbitideae Pic. Serm. -- Webbia 23: 381 (1969)

###### *Arthrobotrya* J.Sm. -- Hist. Fil. 141. 1875

Distribution: Australia, New Zealand

###### *Bolbitis* Schott -- Gen. Fil. \[Schott\] 3: t.14. 1835 \[Jan-May 1835\]

Distribution: Tropics / subtropics, mostly SE-Asia  
= *Anapausia* C.Presl -- Epimel. Bot. 185 (-186). 1851 \[Oct 1851\]  
= *Campium* C.Presl -- Tent. Pterid. 238. 1836  
= *Cyrtogonium* J.Sm. -- J. Bot. (Hooker) 3: 402. 1841 ; & 4: 154. 1842  
= *Danaeopsis* C.Presl -- Suppl. Tent. Pterid. 39. 1845 \[late 1845\]  
= *Edanyoa* Copel. -- Philipp. J. Sci. 81: 22, t.17. 1952  
= *Egenolfia* Schott -- Gen. Fil. \[Schott\] t.16. 1834  
= *Heteroneuron* Hook.f. -- Gen. Pl. \[Bentham & Hooker f.\] 1(3): 768. 1867 \[Sep 1867\]  
= *Heteroneurum* C.Presl -- Epimel. Bot. 168. 1851 \[Oct 1851\]  
= *Jenkinsia* Hook. -- Gen. Fil. \[Hooker\] t.75B. 1840  
= *Lacaussadea* Gaudich. -- Voy. Bonite, Bot. 3(Atlas): t.118-120. \[1841-?1852\]  
= *Poecilopteris* C.Presl -- Tent. Pterid. 241. 1836  
= *Poikilopteris* Eschw. -- Linnaea 2(1): 117. 1827 \[Jan 1827\]

###### *Elaphoglossum* Schott ex J. Sm. -- J. Bot. (Hook.) 4: 148 (1841)

Distribution: Pantropical and south-temperate, mostly tropical America (over 500), 1 in Australia, very few north-temperate (Azores, Japan)  
= *Aconiopteris* C.Presl -- Tent. Pterid. 236. 1836  
= *Acrostichum* Fée -- Mém. Foug. 2 (Hist. Acrostich.) 8, 27 (1845) (non L.)  
= *Acrostichum* sect. Elaphoglossum Hook. -- Sp. Fil. 5: 195-241 (1864)  
= *Condyloneura* Christ -- Neue Denkschr. Allg. Schweiz. Ges. Gesammten Naturwiss. 36 \[Monogr. Elaphoglossum\]: 22 (1899)  
= *Craspedoglossa* Christ -- Neue Denkschr. Allg. Schweiz. Ges. Gesammten Naturwiss. 36 \[Monogr. Elaphoglossum\]: 20 (1899)  
= *Dictyoglossum* J.Sm. -- Bot. Mag. 72(Companion): 18. 1846  
= *Elaphoglossum* Schott -- Gen. Fil. \[Schott\] ad t.14. 1834  
= *Gymnoglossa* Christ -- Neue Denkschr. Allg. Schweiz. Ges. Gesammten Naturwiss. 36 \[Monogr. Elaphoglossum\]: 22 (1899)  
= *Hymenodium* Fée -- Mém. Foug., 2. Hist. Acrostich. 20, 90. 1845  
= *Microstaphyla* C.Presl -- Epimel. Bot. 160. 1851 \[Oct 1851\]  
= *Nebroglossa* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(6) (Epim. Bot.): 166 (1851)  
= *Olfersia* C. Presl -- Tent. Pterid. 232 (1836) (p. p. max., non Raddi)  
= *Oligolepidum* T. Moore -- Index Filic. (T. Moore) 16 (1857)  
= *Pachyglossa* Christ -- Neue Denkschr. Allg. Schweiz. Ges. Gesammten Naturwiss. 36 \[Monogr. Elaphoglossum\]: 20 (1899)  
= *Peltapteris* Link -- Fil. Spec. 147. 1841 \[3-10 Sep 1841\]  
= *Platyglossa* Christ -- Neue Denkschr. Allg. Schweiz. Ges. Gesammten Naturwiss. 36 \[Monogr. Elaphoglossum\]: 20 (1899)  
= *Rhipidopteris* Fée -- Mém. Foug. 2 (Hist. Acrostich.): 14, 78 (1845)  
= *Rhipidopteris* Schott -- Gen. Fil. \[Schott\] ad t.14. 1834

###### *Lastreopsis* Ching -- Bull. Fan Mem. Inst. Biol. Bot. 8: 157. 1938

Distribution: SE-Asia, Pacific. Division between this and Parapolystichum still partially unclear. The 3 remaining New World members need transfer in other genera.  
= *Coveniella* Tindale -- Gard. Bull. Singapore 39(2): 169. 1987 \[1986 publ. 1987\]

###### *Lomagramma* J.Sm. -- J. Bot. (Hooker) 3: 402. 1841 ; & 4: 152 (1841); Ind. Suppl.: 118

Distribution: S-China to E-Polynesia. The genus should be included in Bolbitis fide Fraser-Jenkins (2018) but not all combinations are available  
= *Cheilolepton* Fée -- Mém. Foug., 2. Hist. Acrostich. 19. 1845  
= *Chorizopteris* T.Moore -- Gard. Chron. 1855: 854.

###### *Megalastrum* Holttum -- Gard. Bull. Singapore 39(2): 161. 1987 \[1986 publ. 24 Jan 1987\]

Distribution: Mainly tropical America, few tropical Africa, Madagascar, Mascarenes, subantarctic islands  
= *Ctenitis* sect. Subincisae (C. Chr.) Tindale -- NA  
= *Dryopteris* sect. Subincisae C. Chr. -- NA

###### *Mickelia* R.C.Moran, Labiak & Sundue -- Brittonia 62(4): 338 (-339). 2010 \[15 Dec 2010\]

Distribution: Neotropics  
= *Anapausia* subgen. Euryostichum C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(6) (Epim. Bot.): 188 (1851)

###### *Parapolystichum* (Keyserl.) Ching -- Sunyatsenia 5: 239. 1940

Distribution: Pantropic and south-temperate. Separation from Lastreopsis see Labiak et al. 2014

###### *Pleocnemia* C.Presl -- Tent. Pterid. 183. 1836

Distribution: NE-India, SE-China, Taiwan through Malesia to Samoa  
= *Arcypteris* Underw. -- Bull. Torrey Bot. Club 30: 678. 1903

###### *Rumohra* Raddi -- Opusc. Sci. 3: 290, t.12(1). 1819

Distribution: 1 sp. pantropical, 1 Juan Fdz. Isl., 3 spp. Brazil, 5 Madagascar

###### *Teratophyllum* Mett. ex Kuhn -- Ann. Mus. Bot. Lugduno-Batavi 4: 296. 1870 \[Mar 1870\]

Distribution: Malesia

#### Polybotryoideae Hong M.Liu & X.C.Zhang -- Pl. Syst. Evol. 302(3): 330. 2015 \[24 Dec 2015\] \[epublished\]

###### *Cyclodium* C.Presl -- Tent. Pterid. 84. 1836 \[ante 2 Dec 1836\]

Distribution: Panama and Trinidad to Bolivia, Argentina, SE-Brazil, mostly Guianas. Newest monograph: Bohn et al. (2020), superseding A. R. Smith (1986)  
= *Peltochlaena* Fée -- Mém. Foug., 5. Gen. Filic. 289. \[1850-1852\]

###### *Maxonia* C.Chr. -- Smithsonian Misc. Collect. 66(9): 3. 1916 \[30 Sep 1916\]

Distribution: North America, Greater Antilles  
= *Dryopteris* subgen. Peisomopodium Maxon -- Contr. U.S. Nat. Herb. 13: 39 (1909)

###### *Olfersia* Raddi -- Opusc. Sci. 3: 283. 1819

Distribution: Tropical America  
= *Dorcapteris* C.Presl -- Epimel. Bot. 166. 1851 \[Oct 1851\]

###### *Polybotrya* Humb. & Bonpl. ex Willd. -- Sp. Pl., ed. 4 \[Willdenow\] 5: 99. 1810 \[25-27 Jan 1810\]

Distribution: Neotropics, mostly Andes and SE-Brazil  
= *Amphisoria* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 168. 1851  
= *Botryothallus* Klotzsch -- Bot. Zeitung (Berlin) 4: 104. 1846  
= *Eotoneura* Fée -- Hist. Acrost. 75 (1846)  
= *Granulina* Bory ex Fée -- Mém. Foug. 5 (Gen. Filic.): 48 (1852)  
= *Soromanes* Fée -- Mém. Foug., 2. Hist. Acrostich. 16. 1845

###### *Polystichopsis* (J.Sm.) Holttum -- J. Linn. Soc., Bot. 53: 149, 152. 1947

Distribution: Caribbean. Revision: Prado & Moran (2016)

###### *Stigmatopteris* C. Chr. -- Bot. Tidsskr. 29: 292 (1919)

Distribution: Neotropics. See Moran & Labiak (2016)  
= *Dryopteris* subgen. Stigmatopteris (C. Chr.) C. Chr. -- Kongel. Danske Vidensk. Selsk. Skr., Naturvidensk. Math. Afh., ser. 7, 10: 73 (1913)

###### *Trichoneuron* Ching -- Acta Phytotax. Sin. 10(2): 118, t.22. 1965 \[17 Apr 1965\]

Distribution: China. Taxonomic placement as sister to Polystichopsis see Liu et al. (2016)

###### × *Cyclobotrya* Engels & Canestraro -- Brittonia 69(3): 308. 2017 \[10 Mar 2017\] \[epublished\]

Cyclodium x Polybotrya

### Hemidictyaceae Christenh. & H.Schneid. -- Phytotaxa 28: 51. 2011 \[14 Sep 2011\]

1 genus, 1 sp. Family status confirmed by Rothfels et al. (2012)

###### *Hemidictyum* C.Presl -- Tent. Pterid. 110. 1836

Distribution: Trop. America

### Hypodematiaceae Ching -- Acta Phytotax. Sin. 13(1): 96. 1975

2 genera, ca. 20 spp. Circumscription following Schuettpelz & Pryer (2007)  
= Hypodematioideae (Ching) Fraser-Jenk. -- Annot. Checkl. Ind. Pterid. 2: 192. 2018 \[25 Jun 2018\]

###### *Hypodematium* Kunze -- Flora 16(2): 690. 1833 \[28 Nov 1833\]

Distribution: 1 widespread sp. in Africa and Asia, the rest in E-Asia, 2 in Malesia

###### *Leucostegia* C.Presl -- Tent. Pterid. 94. 1836 \[ante 2 Dec 1836\]

Distribution: Trop. Asia, W-Pacific. Revision: Chen et al. 2021

### Lindsaeaceae Pic.Serm. -- Webbia 24: 707. 1970

6-8 genera, ca. 250 spp. Systematics fide Lehtonen et al. (2010)  
= Lindsaeoideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 155. 1975  
= Lindsaeeae Hook. -- Sp. Fil. 1: 202 (1846)  
= Lindsaeinae Payer -- Bot. Crypt.: 198 (1850)

###### *Lindsaea* Dryand. ex Sm. -- Mém. Acad. Roy. Sci. Turin 5: 413. 1793 ; & Dry. Tr. Linn. Soc. 3. 39. 1797 (Lindsaea); Klf. Enum. 218. 1824

Distribution: Few spp. in Africa, America (45 spp.). Assignment of African species to Lindsaea or Odontosoria still unclear.  
= *Guerinia* J.Sm. -- Hist. Fil. 272. 1875  
= *Humblotiella* Tardieu -- Mém. Inst. Sci. Madagascar, Sér. B, Biol. Vég. 7: 38. 1956  
= *Isoloma* J.Sm. -- J. Bot. (Hooker) 3: 414. 1841 ; & Hk. Gen. Fil. t. 102. 1842  
= *Lindsaenium* Fée -- Mem. Soc. Mus. Hist. Nat. Strasbourg 4(1): 201. 1850  
= *Odontoloma* J.Sm. -- J. Bot. (Hooker) 3: 415. 1841 ; & Lond. JoB. 1. 424. 1842  
= *Ormoloma* Maxon -- Proc. Biol. Soc. Washington 46: 143. 1933  
= *Sambirania* Tardieu -- Mém. Inst. Sci. Madagascar, Sér. B, Biol. Vég. 7: 34. 1956  
= *Schizolegnia* Alston -- Bol. Soc. Brot. sér. 2, 30: 23. 1956  
= *Schizoloma* Gaudich. -- Ann. Sci. Nat. (Paris) 3: 507. 1824  
= *Synaphlebium* J.Sm. -- J. Bot. (Hooker) 3: 415. 1841 ; & Hook. Gen. Fil. t. 101. 1842

###### *Nesolindsaea* Lehtonen & Christenh. -- Bot. J. Linn. Soc. 163(3): 336 (-337). 2010 \[29 Jul 2010\]

Distribution: Trop. Asia, Mascarenes, Seychelles. Very similar and probably only a subgenus of Lindsaea s. lat.

###### *Odontosoria* (C. Presl) Fée -- Mém. Foug. 5 (Gen. Filic.): 325 (1852)

Distribution: Pantropical.  
= *Davallia* subgen. Odontosoria C. Presl -- Tent. Pterid. 129 (1836)  
= *Lindsayopsis* Kuhn -- Chaetopterides 347. 1882  
= *Lourdesia* Barcelona & Hickey -- ined.  
= *Odontosoria* (C. Presl) J. Sm. -- Hist. Fil. 263 (1875), isonym

###### *Osmolindsaea* (K. U. Kramer) Lehtonen & Christenh. -- Bot. J. Linn. Soc. 163(3): 335 (2010)

Distribution: Trop. Asia, E-Asia, Madagascar (2). Revision: Lehtonen et al. 2013  
= *Lindsaea* sect. Osmolindsaea K. U. Kramer -- Blumea 15: 560 (1968)

###### *Sphenomeris* Maxon -- J. Wash. Acad. Sci. 3: 144. 1913

Distribution: New World. Valid genus fide Lehtonen et al. 2010.  
= *Stenoloma* Fée -- Mém. Foug., 5. Gen. Filic. 330. 1852

###### *Tapeinidium* (C. Presl) C. Chr. -- Index Filic. 631 (1906)

Distribution: Asia and W-Pacific: S-India and Ryukyus to Samoa, most in New Guinea  
= *Microlepia* subgen. Tapeinidium C. Presl -- Epim. bot. 96 (1849)  
= *Protolindsaya* Copel. -- Philipp. J. Sci., C 5: 283. 1910  
= *Wibelia* Fée -- Mém. Foug. 5 (Gen. Filic.): 331 (1852)

###### *Xyropteris* K.U.Kramer -- Acta Bot. Neerl. 6: 599, f.1. 1957

Distribution: Malesia

###### × *Lindsaeosoria* W.H.Wagner -- Contr. Univ. Michigan Herb. 19: 72. 1993

Lindsaea x Odontosoria (Sphenomeris)

### Lomariopsidaceae Alston -- Taxon 5: 25. 1956 \[25 Mar 1956\]

4 genera, ca. 60 spp. New family circumscription fide Zhang et al. (2016)  
= Lomariopsidoideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 154. 1975  
= Lomariopsideae Pic. Serm. -- Webbia 23: 381 (1969)

###### *Cyclopeltis* J.Sm. -- Bot. Mag. 72(Companion): 36. 1846

Distribution: SE-Asia, S-China and Myanmar to W-Pacific, not in Australia, 1 sp. tropical America  
= *Hemicardion* Fée -- Mém. Foug., 5. Gen. Filic. 282. 1852 \[1850-1852\]

###### *Dracoglossum* Christenh. -- Thaiszia 17(1-2): 3 (-5). 2007 \[5 Dec 2007\]

Distribution: Trop. America. A former member of Tectariaceae, now placed here by molecular results.

###### *Dryopolystichum* Copel. -- Gen. Fil. \[Copeland\] 125, t.4. 1947

Distribution: New Guinea to Solomon Isl. Taxonomic placement fide Chen et al. (2017)

###### *Lomariopsis* Fée -- Mém. Foug., 2. Hist. Acrostich. 10. 1845 \[1844 publ late 1845\]

Distribution: Pantropical (trop. America (15), trop. Africa, Madagascar, Indian Ocean, E-Himalayas, S-China, peninsular Malaysia, Philippines, Bonin Isl., Australia (1), New Guinea, Pacific to Tahiti)  
= *Thysanosoria* A.Gepp -- Fl. Arfak Mts. \[Gibbs\] 193. 1917 \[Jul 1917\]

### Lonchitidaceae A.R.Sm. & M.Kessler -- Phytotaxa 332(3): 295. 2017 \[epublished\]

1 genus, 2 spp.  
= Lonchitideae Kuhn -- Chaetopterides: 4 (1882)  
= Lonchitidinae Pfeiff. -- Nomencl. Bot. 2(1): 150 (1872)

###### *Lonchitis* L. -- Sp. Pl. 2: 1078. 1753 \[1 May 1753\]

Distribution: Tropical Africa, tropical America  
= *Anisosorus* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 166. 1851  
= *Antiosorus* Roem. -- Chaetopterides 347. 1882  
= *Lonchitidium* Fée -- Mém. Foug. 5 (Gen. Filic.): 126 (1852)

### Nephrolepidaceae Pic.Serm. -- Webbia 29(1): 8. 1974

1 genus, ca. 30 spp. Frequently included in Lomariopsidaceae.  
= Nephrolepideae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1872 publ. 1873)  
= Nephrodiinae Payer -- Bot. Crypt.: 198 (1850)

###### *Nephrolepis* Schott -- Gen. Fil. \[Schott\] 1: t.3. 1834

Distribution: Tropical / subtropical, mostly SE-Asia, trop. America (6). The species circumscription of some of the widespread and variable species in this genus is fluctuating.  
= *Cardiostegia* C.Presl -- Epimel. Bot. 249. 1851 \[Oct 1851\]  
= *Lepidoneuron* Fée -- Mém. Foug. 5 (Gen. Filic.): 301 (1852) (Lepidonevron)  
= *Leptopleuria* C.Presl -- Tent. Pterid. 136. 1836  
= *Lindsayoides* Nakai -- Ord. Fam. Trib. Nov. 202 (1943)

### Oleandraceae Ching ex Pic.Serm. -- Webbia 20: 745. 1965

1 genus, ca. 25 spp.  
= Oleandroideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 154. 1975  
= Oleandreae J. Sm. -- Ferns Brit. For.: 71, 73 (1866)

###### *Oleandra* Cav. -- Anales Hist. Nat. 1: 115. 1799 ; & Descr. plant. 252. 1802; Conf. Maxon, Contr. U. S. Nat. Herb. 17: 392 ff (1913).

Distribution: Tropical America, Africa, Madagascar, east to Sri Lanka, from the Himalayas and S-China south to Malaysia, east to Philippines, New Guinea and Queensland, through the Pacific. There are very conflicting species concepts (4-11 for the Americas) and also in Asia (revised by Hovenkamp et al. 2012, who probably lump too much)  
= *Haplophlebia* Griseb. -- Abh. Ges. Wiss. Gött. 7. 286 (1857)  
= *Neuronia* D.Don -- Prodr. Fl. Nepal. 6. 1825 \[26 Jan-1 Feb 1825\]  
= *Ophiopteris* Reinw. -- Syll. Pl. Nov. 2: 3. 1825 \[1828 publ. 1825\]

### Onocleaceae Pic.Serm. -- Webbia 24(2): 708. 1970 \[28 Apr 1970\]

1-4 genera, 5-6 spp.  
= Onocleeae Tod. -- Syn. Pl. Acot. Vasc.: 29 (1866)  
= Onocleinae Diels -- Engl. & Prantl, Nat. Pflanzenfam. I, 4: 159 (1899)

###### *Matteuccia* Tod. -- Giorn. Sci. Nat. Econ. Palermo 1: 235 (seors. 30). 1866

Distribution: Holarctic. Probably to be included in Onoclea s. lat.  
= *Struthiopteris* Willd. -- Berl. Mag. 3: 160 (1809) (non Scop. (1760))

###### *Onoclea* L. -- Sp. Pl. \[Linnaeus\] 2: 1062. 1753 \[1 May 1753\] ; et in Gen. Pl., ed. 5 : 484 (1754)

Distribution: E-Asia, North and Central America  
= *Angiopteris* Mitch. ex Adans. -- Fam. Pl. 2: 21 (1763) (non Hoffm.)  
= *Calypterium* Bernh. -- J. Bot. (Schrader) 1801(1): 22. 1802 1801 ; & neu. Journ. 1 \[2\]. 25. 1806  
= *Pteridinodes* Kuntze -- Revis. Gen. Pl. 2: 819 (1891) (nom. superfl.)  
= *Ragiopteris* C.Presl -- Tent. Pterid. 96. 1836  
= *Riedlea* Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 5: 71. 1803 ; & Hist. Nat. Pl. 4: 65. 1803

###### *Onocleopsis* F.Ballard -- Amer. Fern J. 35(1): 1. 1945

Distribution: Mexico, Guatemala

###### *Pentarhizidium* Hayata -- Bot. Mag. (Tokyo) 41(492): 715, fig. 1927 \[Dec 1927\]

Distribution: E-Asia

### Polypodiaceae J. & C. Presl -- J. & C. Presl, Delic. Prag. 159 (1822)

67 genera, ca. 1700 spp. Phylogeny: Wei & Zhang 2022  
= Drynariaceae Ching -- Acta Phytotax. Sin. 16(4): 19. 1978  
= Grammitidaceae Newman -- Hist. Brit. Ferns 7. 1840 \[1-5 Feb 1840\] , as ‘Grammitideae’  
= Gymnogrammitidaceae Ching -- Acta Phytotax. Sin. 11: 12. 1966. 1966  
= Pleurosoriopsidaceae Kurata & Ikebe ex Ching -- Acta Phytotax. Sin. 16(4): 17. 1978

#### Adetogrammoideae X.C.Zhang & R.Wei -- Taxon 71(2): 301. 2022 \[19 Jan 2022\] \[epublished\]

###### *Adetogramma* T.E.Almeida -- PhytoKeys 78: 118. 2017 \[13 Apr 2017\] \[epublished\]

Distribution: South America

#### Campyloneuroideae X.C.Zhang & R.Wei -- Taxon 71(2): 301. 2022 \[19 Jan 2022\] \[epublished\]

= Mecosoreae Klotzsch -- Linnaea 20: 404 (1847)

###### *Campyloneurum* C.Presl -- Tent. Pterid. 189. 1836

Distribution: Tropical America  
= *Cyrtophlebium* (R.Br.) J.Sm. -- J. Bot. (Hooker) 4: 58. 1841  
= *Hyalotricha* Copel. -- Amer. Fern J. 43(1): 12. 1953 \[13 Apr 1953\]  
= *Hyalotrichopteris* L. D. Gómez -- Phytologia 51(7): 476 (1982) (nom. nov., isonym)  
= *Hyalotrichopteris* W. H. Wagner -- Taxon 27(5-6): 548 (1978 Publ. 1979), nom. nov.

###### *Microgramma* C.Presl -- Tent. Pterid. 213. 1836 \[ante 2 Dec 1836\]

Distribution: Trop. America, 1 sp. Africa to Mascarenes and India  
= *Anapeltis* J.Sm. -- Cult. Ferns 5. 1857  
= *Craspedaria* Link -- Fil. Spec. 117. 1841  
= *Epidryopteris* Rojas Acosta -- Bull. Géogr. Bot. 28: 156. 1918  
= *Goniophlebium* sect. Lopholepis J. Sm. -- J. Bot. (Hook.) 4: 56 (1841)  
= *Lopholepis* (J. Sm.) J. Sm. -- Lond. J. Bot. 1: 195 (1842) (non Decne. 1839)  
= *Mecosorus* Klotzsch -- Linnaea 20(4): 404. 1847 \[Aug 1847\]  
= *Microgramma* subgen. Solanopteris (Copel.) Lellinger -- Amer. Fern J. 67(2): 59 (1977)  
= *Solanopteris* Copel. -- Amer. Fern J. 41(3): 75, 128. 1951 \[3 Oct 1951\] , err. Typogr. Solenopteris

###### *Niphidium* J. Sm. -- Hist. Fil. 99 (1875)

Distribution: Tropical America. Sometimes included in Campyloneurum.  
= *Anaxetum* Schott -- Gen. Fil. \[Schott\] t.1. 1834  
= *Pessopteris* Underw. & Maxon -- Contr. U.S. Natl. Herb. 10: 485. 1908  
= *Pleuridium* (C.Presl) Fée -- Mém. Foug., 5. Gen. Filic. 273. 1852

#### Crypsinoideae B.K.Nayar -- Taxon 19: 234. 1970

= Drynarioideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 156. 1975  
= Aglaomorpheae Subh. Chandra -- Fern Gaz. (U. K.) 12: 226 (1982)  
= Drynarieae Subh. Chandra -- Fern Gaz. (U. K.) 12: 226 (1982)

###### *Drynaria* (Bory) J. Sm. -- J. Bot. (Hook.) 3: 397 (1841), nom. cons.

Distribution: Africa, trop. Asia to NE-Australia  
= *Aglaomorpha* Schott -- Gen. Fil. \[Schott\] 4: t.19. 1836 \[ante 27 Oct 1836\] ; Cf. Ind. Suppl. piel; & Copeland, Phil. Journ. Sci. Bot. 6: 140(1911); 9: 8 (1914); & Copeland, Univ. Calif. Publ. Bot. 16: 117 (1929)  
= *Christopteris* Copel. -- Fragm. Fl. Philipp. 188. 1905 \[20 Feb 1905\]  
= *Drynariopsis* Copel. -- Polypod. Phil. Isl. 116, 133. 1905 , Polypodium se  
= *Hemistachyum* Copel. -- Philipp. J. Sci., C 6: 141. 1911 , Aglaomorpha se  
= *Holostachyum* Copel. -- Philipp. J. Sci., C 9: 8. 1914 , Aglaomorpha se  
= *Merinthosorus* Copel. -- Philipp. J. Sci., C 6: 92. 1911  
= *Photinopteris* J.Sm. -- J. Bot. (Hooker) 3: 403. 1841 ; & 4: 155. 1841  
= *Polypodium* subgen. Drynaria Bory -- Ann. Sci. Nat., Bot., sér. V, 464, t. 12-14 (1825)  
= *Pseudodrynaria* C.Chr. -- Index Filic., Suppl. Tert. 165. 1934 , Aglaomorpha se  
= *Psygmium* C.Presl -- Tent. Pterid. 199. 1836  
= *Saccopteris* Alderw. -- Malayan Ferns Fern Allies, Suppl. 415 (1917)  
= *Thayeria* Copel. -- Philipp. J. Sci. 1(Suppl. 2): 165. 1906  
= × *Aglaonaria* Hoshiz. -- Amer. Fern J. 81(2): 38. 1991 \[Jul 1991\]

###### *Selliguea* Bory -- Dict. Class. Hist. Nat. \[Bory\] 6: 587. 1824 ; & 15: 344. 1829

Distribution: China (over 50 spp.), trop. Asia, 1 sp. South Africa, 1 Madagascar, many New Guinea. The genus is taken here in a broad sense fide PPG-I, including Crypsinus, Arthromeris, Paraselliguea, Pichisermollodes, Polypodiopteris and Phymatopteris. Fraser-Jenkins et al. (2018) argue strongly to keep at least Arthromeris and Pichisermollodes separate.  
= *Arthromeris* (T.Moore) J.Sm. -- Hist. Fil. 110. 1875  
= *Crypsinopsis* Pic.Serm. -- Webbia 31(1): 240. 1977  
= *Crypsinus* C.Presl -- Epimel. Bot. 123. 1851 \[Oct 1851\]  
= *Dryostachyum* J.Sm. -- J. Bot. (Hooker) 3: 399. 1841 ; & Hk. Gen. Fil. t. 95. 1841  
= *Grammatopteridium* Alderw. -- Nova Guinea 14: 24. 1924 ; & C. Chr. Dansk Bot. Ark. 6. no. 3. 80. 1929  
= *Grammatopteris* Alderw. -- Bull. Jard. Bot. Buitenzorg 3(4): 318. 1922 \[Apr 1922\]  
= *Gymnogrammitis* Griff. -- Icon. Pl. Asiat. 2: t.129, f.1. 1849 ; & Notul. Pl. As. 2: 608. 1849  
= *Himalayopteris* W.Shao & S.G.Lu -- Novon 21(1): 91 (90-93). 2011 \[7 Apr 2011\]  
= *Holcosorus* T.Moore -- Index Fil. (T.Moore) 2: lxxix. 1857  
= *Microterus* C.Presl -- Epimel. Bot. 124. 1851 \[Oct 1851\]  
= *Oleandropsis* Copel. -- Univ. Calif. Publ. Bot. 18: 226. 1942  
= *Paraselliguea* Hovenkamp -- Blumea 45(2): 376. 2000  
= *Phymatopsis* J.Sm. -- Hist. Fil. 104. 1875  
= *Phymatopteris* Pic.Serm. -- Webbia 28: 460. 1973  
= *Pichisermollia* H.C.Monteiro -- Rodriguésia 28(41): 195, nom. 1976  
= *Pichisermollodes* Fraser-Jenk. -- Indian Fern J. 26(1-2): 122. 2010 \[2009 publ. Mar 2010\]  
= *Pleuripteris* C. Chr. -- Dansk Bot. Ark. 6, 3: 76 (1929)  
= *Polypodiopsis* Copel. -- Gen. Fil. \[Copeland\] 210, t.10. 1947  
= *Polypodiopteris* C.F.Reed -- Amer. Fern J. 38(3): 87. 1948 \[11 Oct 1948\]  
= *Pycnoloma* C.Chr. -- Dansk Bot. Ark. 6(3): 75. 1929  
= × *Sellimeris* Fraser-Jenk., Sushil K.Singh & J.Fraser-Jenk. -- Annot. Checkl. Ind. Pterid. 2: 448. 2018 \[25 Jun 2018\]

###### *Synammia* C.Presl -- Tent. Pterid. 212. 1836

Distribution: Temperate southern South America. Circumscription see Schneider et al. 2006

#### Grammitidoideae Parris & Sundue -- J. Syst. Evol. 54(6): 594. 2016 \[14 Feb 2016\] \[epublished\]

41 genera, ca. 800 spp. Systematics see Zhou et al. 2023. Checklist revised for this database by Parris (2020).  
= Grammitideae C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 4, 5: 205 (1836)  
= Pleurogrammeae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1872 publ. 1873)  
= Grammitidinae Payer -- Bot. Crypt.: 197 (1850)

###### *Acrosorus* Copel. -- Philipp. J. Sci. 1(Suppl. 2): 158. 1906

Distribution: SE-Asia to Polynesia. Checklist revised for this database by Parris (2020)

###### *Adenophorus* Gaudich. -- Ann. Sci. Nat. (Paris) 3: 508. 1824

Distribution: Hawaii. Checklist revised for this database by Parris (2020)  
= *Adenophorus* subgen. Oligadenus L. E. Bishop -- Brittonia 26: 231 (1974)  
= *Amphoradenium* Desv. -- Mém. Soc. Linn. Paris 6(3): 335. 1827

###### *Aenigmatogrammitis* Parris -- Taxon 72(5): 985. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: Moluccas, Australia

###### *Alansmia* M.Kessler, Moguel, Sundue & Labiak -- Brittonia 63(2): 238. 2011 \[1 Jun 2011\]

Distribution: Mostly Neotropics, 2 trop. Africa. Revision: Velazquez & Kessler 2013.. Checklist revised for this database by Parris (2020)

###### *Archigrammitis* Parris -- Fern Gaz. 19(4): 135. 2013 \[Apr 2013\]

Distribution: Pacific (4 spp.), Malesia (2 spp.). Checklist revised for this database by Parris (2020)

###### *Ascogrammitis* Sundue -- Brittonia 62(4): 361 (-362). 2010 \[15 Dec 2010\]

Distribution: Neotropics. Checklist revised for this database by Parris (2020)

###### *Boonkerdia* Li Bing Zhang, Pollawatn, X.M.Zhou & Liang Zhang -- Taxon 72(5): 986. 2023 \[17 Jul 2023\] \[epublished\]

Distribution:

###### *Calligrammitis* Parris, Sundue, Li Bing Zhang, X.M.Zhou & Ralf Knapp -- Phytotaxa 597(1): 30. 2023 \[10 May 2023\] \[epublished\]

Distribution: Taiwan, Sri Lanka, Malesia

###### *Calymmodon* C. Presl -- Tent. Pterid. 203 (1836) s. str.

Distribution: Mostly Borneo and New Guinea, also Sri Lanka, SE-Asia to Australia and Polynesia, 3 Taiwan. Checklist revised for this database by Parris (2020)  
= *Calymmodon* C. Presl ex Copel. -- Philipp. J. Sci. 34: 259-269, t. 1-6 (1927)  
= *Plectopteris* Fée -- Mém. Foug., 5. Gen. Filic. 230. 1852 \[1850-52\]

###### *Ceradenia* L.E.Bishop -- Amer. Fern J. 78(1): 2. 1988 \[2 Sep 1988\]

Distribution: Trop. America, few Indian Ocean, 2 very local trop. Africa. Checklist revised for this database by Parris (2020)

###### *Chrysogrammitis* Parris -- Kew Bull. 53(4): 909. 1998 \[23 Dec 1998\]

Distribution: Trop. Asia. Checklist revised for this database by Parris (2020)

###### *Cochlidium* Kaulf. -- Berlin. Jahrb. Pharm. Verbundenen Wiss. 21: 36. 1820 ; & Enum. 86. 1824. C. Chr. Dansk Bot. Ark. 6 \[3\]. 17-25. 1929.

Distribution: Neotropics, 1 to Africa and Indian Ocean. Checklist revised for this database by Parris (2020)  
= *Antrophyum* sect. Pleurogramme Blume -- Fl. Javae, Fil. 69 (1828)  
= *Grammitis* sect. Xiphopteris (Kaulf.) C. Presl -- Tent. Pterid. 208 (1836)  
= *Micropteris* Desv. -- Mém. Soc. Linn. Paris 6: 217. 1827  
= *Pleurogramme* (Blume) C. Presl -- Tent. Pterid. 223 (1836)  
= *Stenofilix* Nakai -- Ord. Fam. Trib. Gen. Sect. … nov. ed. 202. 1943  
= *Xiphopteris* Kaulf. -- Berlin. Jahrb. Pharm. Verbundenen Wiss. 21: 35. 1820

###### *Ctenopterella* Parris -- Gard. Bull. Singapore 58(2): 234. 2007 \[20 Jun 2007\]

Distribution: Trop. Old World. Checklist revised for this database by Parris (2020).

###### *Dasygrammitis* Parris -- Gard. Bull. Singapore 58(2): 238. 2007 \[20 Jun 2007\]

Distribution: Trop. Asia, Pacific. Checklist revised for this database by Parris (2020)

###### *Devolia* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Ralf Knapp -- Phytotaxa 597(1): 32. 2023 \[10 May 2023\] \[epublished\]

Distribution: E-Asia

###### *Enterosora* Baker -- Trans. Linn. Soc. London, Bot. 2(13): 294. 1887 \[1881-87 publ. Jul 1887\]

Distribution: Neotropics, trop. Africa, Madagascar / Mascarenes. Expansion of genus to include Zygophlebia fide Shalisko et al. (2019). Checklist revised for this database by Parris (2020)  
= *Glyphotaenium* J.Sm. -- Hist. Fil. 187. 1875  
= *Zygophlebia* L.E.Bishop -- Amer. Fern J. 79(3): 107. 1989 \[29 Aug 1989\]

###### *Galactodenia* Sundue & Labiak -- Syst. Bot. 37(2): 340. 2012 \[26 Apr 2012\]

Distribution: Trop. America. Checklist revised for this database by Parris (2020)

###### *Glabrigrammitis* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Parris -- Phytotaxa 597(1): 34. 2023 \[10 May 2023\] \[epublished\]

Distribution: Taiwan, Sri Lanka, Malesia

###### *Grammitastrum* (E.Fourn.) Parris, Sundue, Li Bing Zhang & X.M.Zhou -- Taxon 72(5): 989. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: New Caledonia

###### *Grammitis* Sw. -- J. Bot. (Schrader) 1800(2): 17. 1801 \[Oct-Dec 1801\]

Distribution: Probably \< 20 spp. tropics. Several remaining species will need recombination in other genera. Checklist revised for this database by Parris (2020)  
= *Nanopteris* Vareschi -- Fl. Venezuel. 1: 881 (1969)

###### *Grammitis* p. p. -- NA

Distribution: Lord Howe Isl. Phylogenetic position unconfirmed, probably not belonging in Howeogrammitis.

###### *Howeogrammitis* Parris, Sundue, Li Bing Zhang & X.M.Zhou -- Taxon 72(5): 990. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: Lord Howe Isl.

###### *Lellingeria* A.R.Sm. & R.C.Moran -- Amer. Fern J. 81(3): 76. 1991 \[Oct 1991\]

Distribution: Neotropics. Revision see Labiak (2013). Checklist revised for this database by Parris (2020)

###### *Leucotrichum* Labiak -- Taxon 59(3): 915 (-916). 2010 \[4 Jun 2010\]

Distribution: Neotropics (5), 1 Madagascar. Checklist revised for this database by Parris (2020)

###### *Lomaphlebia* J.Sm. -- Hist. Fil. 182. 1875

Distribution: Caribbean. Checklist revised for this database by Parris (2020)

###### *Luisma* M.T.Murillo & A.R.Sm. -- Novon 13(3): 313. 2003 \[10 Sep 2003\]

Distribution: Colombia. Taxonomic position uncertain

###### *Melpomene* A.R.Sm. & R.C.Moran -- Novon 2(4): 426. 1992 \[22 Dec 1992\]

Distribution: Neotropics, 1 extending to trop. Africa. Revision: Lehnert 2013. Checklist revised for this database by Parris (2020)  
= *Cryptosorus* Fée -- Congr. Sci. France 10(1): 178. 1843 ; Gen. 231. 1850-52; et in Mém. Foug., 5. Gen. Filic. 231 (1852)  
= *Grammitis* sect. Cryptosorus (Fée) R. M. Tryon & A. F. Tryon -- Rhodora 84(837): 128 (1982)  
= *Polypodium* sect. Cryptosorus (Fée) E. Fourn. -- Ann. Sci. Nat., Bot., sér. V, 18: 282 (1873)

###### *Micropolypodium* Hayata -- Bot. Mag. (Tokyo) 42: 302, 341. 1928

Distribution: China, Indochina, S-Himalaya to Philippines. Checklist revised for this database by Parris (2020)

###### *Moranopteris* R.Y.Hirai & J.Prado -- Taxon 60(4): 1127 (-1128). 2011 \[17 Aug 2011\]

Distribution: Trop. America, 1 sp. Madagascar. Checklist revised for this database by Parris (2020)  
= *Micropolypodium* auct. -- nec Hayata

###### *Mycopteris* Sundue -- Brittonia 66(2): 175. 2013 \[17 Sep 2013\] \[epublished\]

Distribution: Neotropics. Checklist revised for this database by Parris (2020)

###### *Nanogrammitis* Parris, Li Bing Zhang, X.M.Zhou & Liang Zhang -- Taxon 72(5): 991. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: E-Africa, Madagascar, Seychelles, Mascarenes

###### *Notogrammitis* Parris -- New Zealand J. Bot. 50(4): 465. 2012 \[Dec 2012\]

Distribution: Australia, New Zealand, Patagonia (1). Checklist revised for this database by Parris (2020)

###### *Oreogrammitis* Copel. -- Philipp. J. Sci., C 12: 64. 1917

Distribution: Trop. Asia, Pacific, Australia. Checklist revised for this database by Parris (2020)  
= *Radiogrammitis* Parris -- Gard. Bull. Singapore 58(2): 240 (-241). 2007 \[20 Jun 2007\]  
= *Themelium* (T.Moore) Parris -- Kew Bull. 52(3): 737. 1997 \[7 Nov 1997\]

###### *Oxygrammitis* Parris & Sundue -- Taxon 72(5): 992. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: Malesia

###### *Parrisia* Shalisko & Sundue -- Phytotaxa 394(3): 187. 2019 \[1 Mar 2019\] \[epublished\]

Distribution: Neotropics (1), Indian Ocean (1). Checklist revised for this database by Parris (2020)

###### *Prosaptia* C. Presl -- Tent. Pterid. 65 (1836)

Distribution: Tropical Asia, E-Asia. Checklist revised for this database by Parris (2020)  
= *Ctenopteris* Blume ex Kunze -- Fl. Javae 1(Filic.): 132. 1830 \[14 Apr 1830\] ; & Kunze, Bot. Zeit. 1846. 425  
= *Ctenopteris* sect. Prosaptia (C. Presl) K. Iwats. -- Fl. Jap. 1: 255 (1995)

###### *Rouhania* Li Bing Zhang, X.M.Zhou, Jian Jun Yang & Liang Zhang -- Taxon 72(5): 995. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: trop. Africa, Madagascar

###### *Scleroglossum* Alderw. -- Bull. Jard. Bot. Buitenzorg Ser. 2, 7: 37, t.5. 1912 ; & C. Chr. Dansk Bot. Ark. 6 \[3\]. 25-30. 1929.

Distribution: Trop. Asia, trop. Australia. Checklist revised for this database by Parris (2020)  
= *Nematopteris* Alderw. -- Bull. Jard. Bot. Buitenzorg Ser. 2, 28: 65. 1918

###### *Stenogrammitis* Labiak -- Brittonia 63(1): 141. 2011 \[1 Mar 2011\]

Distribution: Neotropics, Africa, Hawaii, Pacific. Checklist revised for this database by Parris (2020)

###### *Terpsichore* A.R.Sm. -- Novon 3(4): 479. 1993 \[29 Dec 1993\]

Distribution: Neotropics, 1 to trop. Africa. Checklist revised for this database by Parris (2020)

###### *Thalassogrammitis* Parris, Sundue, Li Bing Zhang & X.M.Zhou -- Taxon 72(5): 996. 2023 \[17 Jul 2023\] \[epublished\]

Distribution: New Caledonia

###### *Tomophyllum* (E.Fourn.) Parris -- Gard. Bull. Singapore 58(2): 245. 2007 \[20 Jun 2007\]

Distribution: Trop. Asia to China, Australia, W-Pacific. Checklist revised for this database by Parris (2020)

###### *Xiphopterella* Parris -- Gard. Bull. Singapore 58(2): 249 (-250). 2007 \[20 Jun 2007\]

Distribution: Trop. Asia. Checklist revised for this database by Parris (2020)

#### Loxogrammoideae H.Schneid. -- Phytotaxa 19: 18. 2011 \[18 Feb 2011\]

= Loxogrammeae R. M. Tryon & A. F. Tryon -- Rhodora 84: 129 (1982)

###### *Dictymia* J.Sm. -- Bot. Mag. 72(Companion): 16. 1846 ; see Copeland, Univ. Calif. Publ. Bot. 16: 114 (1929).

Distribution: E-Australia to Fiji and New Caledonia

###### *Loxogramme* (Blume) C. Presl -- Tent. Pterid. 214 (1836)

Distribution: Mostly tropical / subtropical Asia, 1 Central America, 2 trop. Africa, 1 Madagascar, 1 Fiji to Samoa, 1 New Zealand. Inclusion of Anarthropteris fide Flora of New Zealand.  
= *Anarthropteris* Copel. -- Gen. Fil. \[Copeland\] 217. 1947  
= *Antrophyum* sect. Loxogramme Blume -- Fl. Javae, Fil. 73 (1829)

#### Microsoroideae B. K. Nayar -- Taxon 19: 233 (1970)

phylogeny: Wei et al. 2017, Testo et al. 2019, Chen et al. 2019, 2020, Perrie et al. 2021  
= Lepisoroideae Ching -- Acta Phytotax. Sin. 16: 17 (1978)

##### Goniophlebieae C. C. Chen & H. Schneider -- Molec. Phylogen. Evol. 143-106665: 8 (2019)

###### *Goniophlebium* (Blume) C. Presl -- Tent. Pterid. 185 (1836) s. str.

Distribution: Asia. Systematics following Rödl-Linder (1990). All New World species have to be excluded and are listed under Polypodium. Fraser-Jenkins et al. (2020) argue for keeping Polypodioides as distinct genus.  
= *Metapolypodium* Ching -- Acta Phytotax. Sin. 16(4): 28. 1978  
= *Polypodiastrum* Ching -- Acta Phytotax. Sin. 16(4): 27. 1978  
= *Polypodiodes* Ching -- Acta Phytotax. Sin. 16(4): 26. 1978  
= *Polypodium* sect. Goniophlebium Blume -- Fl. Javae, Fil. 132 (1828)  
= *Schellolepis* J.Sm. -- Ferns Brit. Foreign (ed. 1) 82. 1866 \[Oct 1866\]

##### Lecanoptereae C. C. Chen & H. Schneider -- Molec. Phylogen. Evol. 143-106665: 8 (2019)

###### *Bosmania* Testo -- Syst. Bot. 44(4): 744. 2019 \[22 Aug 2019\] \[epublished\]

Distribution: Madagascar (2), China, India, Indochina, Philippines

###### *Lecanopteris* Reinw. -- Flora 8(2, Beil.): 48. 1825 ; & Blume, Enum. 120. 1828

Distribution: Malesia, Australia, Pacific. Inclusion of Zealandia and Dendroconche fide Perrie et al. (2021).  
= *Dendroconche* Copel. -- Philipp. J. Sci., C 6: 91. 1911  
= *Lecanium* Reinw. -- Flora 8(2, Beil.): 48. 1825  
= *Myrmecophila* Christ ex Nakai -- Bot. Mag. (Tokyo) 43: 6. 1929  
= *Myrmecopteris* Pic.Serm. -- Webbia 31(1): 239. 1977 , nom. nov.  
= *Onychium* Reinwardt -- Syll. pl. 2: 2 (1824) (nec Kaulf. (1820))  
= *Zealandia* Testo & A.R.Field -- Syst. Bot. 44(4): 749. 2019 \[22 Aug 2019\] \[epublished\]

##### Lepisoreae Ching ex E. Hennipman, P. Veldhoen & K. U. Kramer -- Fam. Gen. Vasc. Pl. 1: 207 (1990)

= Lemmaphylleae V. N. Tu -- Novosti Sist. Vyssh. Rast. 18: 44 (1981)

###### *Lepisorus* (J. Sm.) Ching -- Bull. Fan Mem. Inst. Biol. Bot. 4: 47 (1933), nom. cons. prop.

Distribution: China (many), E- and tropical Asia, 1 Hawaii, few Africa, Madagascar and W-Pacific. Phylogeny and broad circumscription see Zhao et al. (2019), confirmed by PPG II. There is considerable taxonomic confusion in China because of previous oversplitting.  
= *Belvisia* Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 473; 5: 111. 1802 \[dt. 1803; publ. 21 Nov 1802\]  
= *Caobangia* A.R.Sm. & X.C.Zhang -- Novon 12(4): 546. 2002 \[26 Dec 2002\]  
= *Cheiropteris* Christ -- Bull. Herb. Boissier 6: 876. 1898  
= *Drymotaenium* Makino -- Bot. Mag. (Tokyo) 15(174): 102. 1901 \[20 Aug 1901\]  
= *Ellipinema* Li Bing Zhang & Liang Zhang -- Molec. Phylogen. Evol. 148: 6. 2020 \[23 Mar 2020\] \[epublished\]  
= *Hyalolepis* Kunze -- Linnaea 23(3): 258. 1850 \[Jul 1850\]  
= *Hymenolepis* Kaulf. -- Enum. Filic. 146. 1824 \[8 Apr-28 May 1824\] ; cf.C.Chr., Dansk Bot. Ark. 6: 54-70 (1929).  
= *Lemmaphyllum* C.Presl -- Epimel. Bot. 157. 1851 \[Oct 1851\] ; & C. Chr. Dansk Bot. Arkiv 6. no. 3. 44 t. 5. 1929 (excl. se Pseudovittaria); =Abh. Konigl. Bohm. Ges. Wiss. ser. 5 (Oct. 1851) 517  
= *Lepidogrammitis* Ching -- Sunyatsenia 5: 258. 1940  
= *Lepidomicrosorium* Ching & K.H.Shing -- Bot. Res. Academia Sinica 1(1): 1. 1983 \[Dec 1983\]  
= *Macroplethus* C.Presl -- Epimel. Bot. 141. 1851 \[Oct 1851\]  
= *Neocheiropteris* Christ -- Bull. Soc. Bot. France 52(Mém. 1): 21. 1905  
= *Neolepisorus* Ching -- Bull. Fan Mem. Inst. Biol. Bot. 10: 11. 1940  
= *Paragramma* (Blume) T.Moore -- Index Fil. (T.Moore) 1: xxxii. 1857 \[Mar 1857\]  
= *Platygyria* Ching & S.K.Wu -- Acta Bot. Yunnan. 2(1): 67. 1980  
= *Pleopeltis* sect. Lepisorus J. Sm. -- Bot. Mag. 72. Comp. 13 (1846)  
= *Tricholepidium* Ching -- Acta Phytotax. Geobot. 29(1-5): 41. 1978 \[30 May 1978\]  
= *Weatherbya* Copel. -- Gen. Fil. \[Copeland\] 191, t.6. 1947  
= Lepinema Raf. -- Fl. Tellur. 3: 26. 1837 \[1836 publ. Nov-Dec 1837\]  
= × *Ellipisorus* Li Bing Zhang & Liang Zhang -- Phytotaxa 464(4): 299. 2020 \[21 Oct 2020\] \[epublished\]

##### Microsoreae V. N. Tu -- Novosti Sist. Vyssh. Rast. 18: 18 (1981)

= Colysideae V. N. Tu -- Novosti Sist. Vyssh. Rast. 18: 29 (1981)

###### *Leptochilus* Kaulf. -- Enum. Filic. 147. 1824 \[8 Apr-28 May 1824\] ; Conf.E.Schumann, Flora 108: 250-252 (1915).

Distribution: E- and tropical Asia, 3 to Queensland. Species circumscription quite controversial and fluctuating.  
= *Colysis* C.Presl -- Epimel. Bot. 146. 1851 \[Oct 1851\]  
= *Dendroglossa* C.Presl -- Epimel. Bot. 149. 1851 \[Oct 1851\]  
= *Gymnopteris* C. Presl -- Tent. Pterid. 244 (1836)  
= *Kontumia* S.K.Wu & L.K.Phan -- Novon 15(1): 245. 2005 \[29 Apr 2005\]  
= *Nistarika* B.K.Nayar, Madhus. & Molly -- Fern Gaz. 13(1): 33. 1985  
= *Paraleptochilus* Copel. -- Gen. Fil. \[Copeland\] 198, t.7. 1947  
= *Selliguea* Blume -- (1826) (nec Bory (1824))

###### *Microsorum* Link -- Hort. Berol. \[Link\] 2: 110. 1833 \[Jul-Dec 1833\]

Distribution: Paleotropical, extending to E-Australia and New Zealand, eastward to Pacific, west to trop. Africa (1). Inclusion of Phymatosorus is demonstrated by Testo et al. (2019) and (finally) accepted by Fraser-Jenkins & Kandel (2020).  
= *Campylogramma* Alderw. -- Bull. Jard. Bot. Buitenzorg sér. 2, 23: 7. 1916 \[Dec 1916\] ; Cf. Copeland, Phil. Journ. Sci. 38. 149. 1929  
= *Diblemma* J.Sm. -- J. Bot. (Hooker) 3: 399. 1841 ; & 4: 65. 1841  
= *Kaulinia* B.K.Nayar -- Taxon 13: 67. 1964  
= *Myuropteris* C.Chr. -- Dansk Bot. Ark. 6(3): 73. 1929  
= *Phymatosorus* Pic.Serm. -- Webbia 28: 457. 1973

###### *Podosorus* Holttum -- Kew Bull. 20(3): 455, f.1. 1967 \[1966 publ. 3 Jan 1967\]

Distribution: Philippines. Phylogenetic position unknown.

##### Thylacoptereae C. C. Chen & H. Schneider -- Molec. Phylogen. Evol. 143-106665: 8 (2019)

###### *Thylacopteris* Kunze ex J.Sm. -- Hist. Fil. 87. 1875

Distribution: Tropical Asia

#### Platycerioideae B.K.Nayar -- Taxon 19: 233. 1970

= Platyceriinae Diels -- Engl. & Prantl, Nat. Pflanzenfam. I, 4: 330, 336 (1899)

###### *Hovenkampia* Li Bing Zhang & X.M.Zhou -- Molec. Phylogen. Evol. 114: 288. 2017 \[1 Jul 2017\] \[epublished\]

Distribution: Africa. The genus is only treated as subgenus of Pyrrosia by Vasques et al. (2017).

###### *Platycerium* Desv. -- Mém. Soc. Linn. Paris 6(3): 213. 1827 \[Jul 1827\] ; = Prodr. Fam. Foug. (1827)

Distribution: 6 spp. Africa/Madagascar, 7 Asia, 1 South America  
= *Alcicornium* Gaudich. -- Voy. Uranie \[Freycinet\] 48. 1826 \[27 Dec 1826\]  
= *Neuroplatyceros* (Endl.) Fée -- Mém. Foug., 2. Hist. Acrostich. 25. 1845  
= *Stemaria* Schott -- Wiener Z. Kunst 4 (26 Dec. 1829)

###### *Pyrrosia* Mirb. -- Hist. Nat. Vég. \[Lam. & Mirbel\] 3: 471. 1802 \[dt. 1803; publ. 21 Nov 1802\] ; & Hist. Nat. Pl. 4: 70. 1803; & Hist. Nat. Vég. \[Lam. & Mirbel\] 5: 91(1803).

Distribution: Tropical Asia including Pacific. Cyclophorus, Drymoglossum and Saxiglossum are frequently treated as separate genera. Subgenera according to Vasques et al. (2017)  
= *Achuaria* Gereau -- Candollea 45(1): 365 (1990).  
= *Apalophlebia* C.Presl -- Epimel. Bot. 137. 1851 \[Oct 1851\]  
= *Asteroglossum* J.Sm. -- Index Fil. (T.Moore) 7: 179. 1860  
= *Cyclophorus* Desv. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 5: 298. 1811  
= *Digramma* Kunze -- Bot. Zeitung (Berlin) 209 (1848)  
= *Drymoglossum* C.Presl -- Tent. Pterid. 5: 227, t.10(5-6). 1836 \[ante 2 Dec 1836\] , nom. cons; & Abh. Königl. Böhm. Ges. Wiss. ser. 4, 5: 227. 1837; cf.C.Chr., Dansk Bot. Ark. 6(3) (1929)  
= *Galeoglossa* C.Presl -- Epimel. Bot. 132. 1851 \[Oct 1851\]  
= *Gyrosorium* C.Presl -- Epimel. Bot. 139. 1851 \[Oct 1851\]  
= *Neoniphopsis* Nakai -- Bot. Mag. (Tokyo) 42: 217. 1928  
= *Nesoris* Raf. -- New Fl. \[Rafinesque\] 4: 104. 1838 \[dt. 1836; publ. late 1838\]  
= *Niphobolus* Kaulf. -- Enum. Filic. 124. 1824 \[8 Apr-28 May 1824\]  
= *Niphopsis* J.Sm. -- Cult. Ferns 6. 1857  
= *Oetosis* Kuntze -- Revis. Gen. Pl. 2: 817. 1891 \[5 Nov 1891\]  
= *Polycampium* C.Presl -- Epimel. Bot. 135. 1851 \[Oct 1851\]  
= *Polypodium* subgen. Niphidium (Lellinger) Proctor -- R. A. Howard, Fl. Lesser Antilles 2: 343 (1977)  
= *Pteropsis* Desv. -- Mém. Soc. Linn. Paris 6(3): 218. 1827 \[Jul 1827\] ; Prodr. Foug.; Maxon, Contr. U.S. Natl. Herb. 16: 51 (1912).  
= *Saxiglossum* Ching -- Contr. Inst. Bot. Natl. Acad. Peiping 2(1): 5. 1933  
= *Scytopteris* C.Presl -- Epimel. Bot. 133. 1851 \[Oct 1851\] ; ==Abhandlungen der Koniglichen Bohmischen Gesellschaft der Wissenschaften ser. 5, 6 (Oct. 1851) 493  
= *Solenopteris* Wall. -- Tidsskr. f. Naturvid. 1: 259 (1822)  
= *Sphaerostichum* C.Presl -- Epimel. Bot. 134. 1851 \[Oct 1851\]

#### Polypodioideae B.K.Nayar -- Taxon 19: 234. 1970

= Polypodiaceae J. Presl & C. Presl -- Delic. Prag.: 159 (1822)  
= Pleopeltidoideae B.K.Nayar -- Taxon 19: 234. 1970  
= Pleopeltideae V. N. Tu -- Novosti Sist. Vyssh. Rast. 18: 18 (1981)  
= Polypodieae Hook. & Lindl. ex Duby -- Bot. Gall. 1: 537 (1828)  
= Polypodiidae Cronquist, Takht. & Zimmerm. -- Taxon 15: 133 (1966)  
= Polypodiineae Bessey -- Bot. High Schools: 377 (1880)

###### *Pecluma* M.G.Price -- Amer. Fern J. 73(4): 109. 1983 \[29 Dec 1983\]

Distribution: New World tropics to N-Argentina.  
= *Polypodium* subgen. Pectinatum Lellinger -- Amer. Fern J. 71: 93 (1981)

###### *Phlebodium* (R.Br.) J.Sm. -- J. Bot. (Hooker) 4: 58. 1841

Distribution: New World, tropical

###### *Pleopeltis* Alderw. -- Malayan Ferns 568. 1908 , non Humb. & Bonpl.

Distribution: Mostly neotropical, very few in Africa, Pacific and Asia. New circumscription see Smith & Tejero-Diez 2014.  
= *Ampelopteris* Klotzsch -- Linnaea 20: 430 (1847)  
= *Cheilogramme* (Blume) Underw. -- Mem. Torrey Bot. Club 6: 274, 277 (1899), nom. superfl.  
= *Chilogramme* Blume -- Fl. Javae, Fil. 70 (1828)  
= *Cuspidaria* Link -- Handbuch \[Link\] 2: 315. 1831  
= *Dicranoglossum* J.Sm. -- Bot. Voy. Herald \[Seemann\] 6: 232. 1854 \[late 1854 or v. early 1855?\]  
= *Eschatogramme* Trevis. -- Dansk Bot. Ark. 6(3): 34-38. 1929  
= *Heteropteris* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 305 (1899) (nom. superfl.)  
= *Lepicystis* (J. Sm.) J. Sm. -- Lond. J. Bot. 1: 195 (1842)  
= *Marginaria* Bory -- Dict. Class. Hist. Nat. \[Bory\] 6: 587. 1824 ; & 10: 176. 1826  
= *Marginariopsis* C. Chr. -- Dansk Bot. Ark. 6(3): 42 (1929)  
= *Microphlebodium* L.D.Gómez -- Phytologia 59(1): 58. 1985  
= *Neurodium* Fée -- Mem. Soc. Mus. Hist. Nat. Strasbourg 4(1): 201. 1850 , as ‘Nevrodium’  
= *Paltonium* C.Presl -- Epimel. Bot. 156. 1851 \[Oct 1851\]  
= *Pseudocolysis* L.D.Gómez -- Brenesia 10-11: 116. 1977  
= xPleopodium Schelpe & N. C. Anthony -- Bothalia 15(3-4): 557 (1985)

###### *Pleurosoriopsis* Fomin -- Izv. Kievsk. Bot. Sada XI: 8. 1939 ; & Fl. Sib. et. Or. Extr. 5. 215. 1930.

Distribution: E-Asia

###### *Polypodium* L. -- Sp. Pl. 2: 1082. 1753 \[1 May 1753\] ; & Gen. Pl. ed. 5, 485, 1754 as Polypodium sect. Pleopeltis b. Atactosia.

Distribution: Mainly American tropics, few in Old World. Many neotropical species listed will need recombination in other genera.  
= *Catenularia* Botsch. -- Bot. Mater. Gerb. Bot. Inst. Komarova Akad. Nauk S.S.S.R. 18: 101. 1957  
= *Cephalosorium* T. Moore -- Index Filic. (T. Moore) 75 (1857)  
= *Chilopteris* C.Presl -- Tent. Pterid. 208. 1836 , Grammitis se  
= *Clathropeltis* Kuhn -- Decken, Reisen Ost-Afr. 88. Bot. 51 (1879)  
= *Coelopteris* A.Braun -- Abh. Senckenberg. Naturf. Ges. 50. 1856 \[Oct 1856\] ; reprinted as Farngatt. 1(Polypodium): 50, Feb-Mar 1857  
= *Cyrtomiphlebium* Hook. -- Sp. Fil. 6: 15 (1863)  
= *Cystidium* Lindl. -- Veg. Kingd., ed. 2 80. 1847 , (err.)  
= *Diagramma* Blume -- Enum. Pl. Javae 2: 114 (1828)  
= *Dicranopteris* Blume ex Endl. -- Gen. Suppl. 1: 1346 (1841)  
= *Dictyogramma* C. Presl -- Abh. Königl. Böhm. Ges. Wiss. 5(6) (Epim. Bot.): 148 (1851)  
= *Dictyophlebia* Griseb. -- Abh. Ges. Wiss. Gött. 7: 283, 286 (1857)  
= *Eleutherophlebia* Griseb. -- Abh. Ges. Wiss. Gött. 7: 282. 285 (1857)  
= *Goniolepicystis* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 323 (1899)  
= *Lepicystis* J. Sm. -- Lond. J. Bot. 1: 195 (1842)  
= *Leptoselliguea* C. Chr. -- Gard. Bull. Straits Settlem. 7: 309 (1934)  
= *Leptostegia* Zipp. ms. ex Mett. -- Abh. Senckenberg. Naturf. Ges. 2: 50 (1857)  
= *Marginariopsis* T. Moore -- Index 73 (1857)  
= *Micropteris* J. Sm. -- Hist. Fil. 186 (1875), nom. illeg., non Desv.  
= *Phlebiolepicystis* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 321 (1899)  
= *Phlebodiopsis* T. Moore -- Index Filic. (T. Moore) 77 (1857)  
= *Phyllitidis* J. Sm. -- J. Bot. (Hooker) 3: 397 (1841)  
= *Pleurogonium* (C.Presl) Lindl. -- Veg. Kingd. 79. 1846  
= *Pseudovittaria* C. Chr. -- Dansk Bot. Ark. 6, no. 3: 45 (1929)  
= *Trichocalymma* Zenker -- Linnaea 24(2): 251. 1851 \[Jul 1851\]

###### × *Phlebosia* Viane & Pompe -- Fern Gaz. 21(3): 107. 2020 \[15 May 2020\]

Phlebodium x Pyrrosia

#### Serpocauloideae X.C.Zhang & R.Wei -- Taxon 71(2): 301. 2022 \[19 Jan 2022\] \[epublished\]

###### *Serpocaulon* A.R.Sm. -- Taxon 55(4): 924. 2006 \[20 Dec 2006\]

Distribution: Tropical New World. Revision: Sanin et al. (2023)

### Pteridaceae E. D. M. Kirchn. -- Schul-Bot. 109 (1831)

48 genera, ca. 1350 spp. The family has been split extensively in smaller subgroups, but Smith et al. (2006) and PPG-I argue for keeping them together.  
= Actiniopteridaceae Pic.Serm. -- Webbia 17: 5. 1962  
= Adiantaceae Newman -- Hist. Brit. Ferns 5. 1840 \[1-5 Feb 1840\]  
= Anopteraceae Doweld -- Prosyllabus Tracheophytorum LI (2001).  
= Antrophyaceae (Link) Ching -- Acta Phytotax. Sin. 16: 11 (1978)  
= Cheilanthaceae B.K.Nayar -- Taxon 19: 233. 1970  
= Cryptogrammaceae Pic.Serm. -- Webbia 17: 299. 1963  
= Hemionitidaceae Pic.Serm. -- Webbia 21: 487. 1966  
= Negripteridaceae Pic.Serm. -- Nuovo Giorn. Bot. Ital. n.s., 53: 160. 1946 ; preprint issued 25 Nov 1946; issue publ. 24 May 1947  
= Platyzomataceae Nakai -- Bull. Natl. Sci. Mus. Tokyo 29: 4. 1950  
= Pteridaceae Reichenb. -- Handb. Nat. Pflanzensyst. 138 (1837)  
= Taenitidaceae (C.Presl) Pic.Serm. -- Webbia 29: 1. 1974. 1974  
= Vittariaceae Ching -- Sunyatsenia 5: 210, 232. 1940 \[30 Oct 1940\]

#### Adiantoideae Horvát -- Acta Bot. Inst. Bot. Univ. Zagreb. 2: 114 (1927), as ‘Adiantinae’

= Adiantoideae (C. Presl) R. M. Tryon -- Amer. Fern J. 76: 184 (1986)  
= Adianteae Gaudich. -- H. L. C. de Saulces de Freycinet, Voy. Uranie, Bot.: 402 (1829)  
= Adiantinae Pfeiff. -- Nomencl. Bot. 1(1): 46 (1871)

###### *Adiantum* L. -- Sp. Pl. \[Linnaeus\] 2: 1094. 1753 \[1 May 1753\] ; et in Genera Plantarum ed. 5 1754

Distribution: Worldwide, mostly wet areas in mountains, especially Andes. 1 undescribed species in Taiwan to be published 2017 (Knapp, in litt.)  
= *Adiantellum* C. Presl -- Tent. Pterid. 157 (1836)  
= *Apotomia* Fée -- Mém. Foug. 5 (Gen. Filic.): 112 (1852)  
= *Hewardia* J.Sm. -- J. Bot. (Hooker) 3: 432. 1841  
= *Mesopleuria* T. Moore -- Index Filic. (T. Moore) 36 (1857)

#### Cheilanthoideae Horvath -- Acta Bot. Inst. Bot. Univ. Zagreb 2: 114 (1927), as ‘Cheilanthinae’

Cheilanthes s. l. turned out to be polyphyletic (Gastony & Rollo 1998), which leads to exclusion of Notholaena, Aleuritopteris and Paraceterach, but it should include Mildella, which was formerly treated in connection with Pellaea. There are highly conflicting systems.  
= Cheilanthoideae (J. Sm.) W. C. Shieh -- J. Sci. Engin. (Natl. Chung-Hsing Univ.) 10: 211 (1973)  
= Cheilanthoideae W. C. Shieh -- J. Sci. Engin. (Natl. Chung-Hsing Univ.) 10: 211 (1973), nom. superfl.  
= Gymnopteridoideae W.C.Shieh -- J. Sci. Engin. 10: 224. 1973  
= Allosoreae Rouy -- Fl. France \[Rouy & Foucaud\] 14: 388 (1913)  
= Cheilantheae J. Sm. -- Hist. Fil. 277 (1875)  
= Cheilantheae Todaro -- Syn. Pl. Acot. Vasc.: 10 (1866)  
= Hemionitideae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1872 publ. 1873)  
= Notholaeneae Gaudich. -- Freycinet, Voy. Uranie, Bot.: 405 (1828)  
= Cheilanthinae Diels -- Engl. & Prantl, Nat. Pflanzenfam. I, 4: 254, 265 (1899)  
= Gymnopteridinae Engl. -- Syllabus, ed. 6: 70 (1909)

###### *Adiantopsis* Fée -- Mém. Foug., 5. Gen. Filic. 145. 1852

Distribution: American tropics. See especially Schuettpelz et al. (2014)  
= *Actinopteris* J. Sm. -- Bot. Mag. 72 Comp. 20 (1846)  
= *Adiantastrum* Fée -- Mém. Foug. 8 (Icon. Esp. Nouv.): 1151 (1867)

###### *Aleuritopteris* Fée -- Mém. Foug., 5. Gen. Filic. 153. 1852

Distribution: Mostly China, India, Indochina, 3 Africa, 2 neotropics. This is a valid spinoff genus of Cheilanthes s. lat. fide Fraser-Jenkins et al. (2017), and Allosorus remains a synonym because wrongly lectotypified.  
= *Allosorus* Farw. -- Rep. (Annual) Michigan Acad. Sci. 21: 345. 1919 ; & Amer. Midl. Naturalist 12. 284. 1931  
= *Gymnia* Buch.-Ham. -- Prodr. Fl. Nepal. 16. 1825  
= *Leptolepidium* K.H.Shing & S.K.Wu -- Acta Bot. Yunnan. 1(1): 115. 1979 \[Aug 1979\]  
= *Negripteris* Pic.Serm. -- Nuovo Giorn. Bot. Ital. ser. 2, 53: 130, t. 14-16. 1946  
= *Sinopteris* C.Chr. & Ching -- Bull. Fan Mem. Inst. Biol. 4: 359. 1933

###### *Argyrochosma* (J. Sm.) Windham -- Amer. Fern J. 77: 38 (1987)

Distribution: American tropics, S-USA, 1 China  
= *Notholaena* sect. Argyrochosma J. Sm. -- J. Bot. (Hook.) 4: 50 (1841)

###### *Aspidotis* (Nutt. ex Hook.) Copel. -- Gen. Fil. \[Copeland\] 68. 1947

Distribution: North America / Mexico  
= *Hypolepis* sect. Aspidotis Nutt. ex Hook. 1852 -- NA

###### *Astrolepis* D.M.Benham & Windham -- Amer. Fern J. 82(2): 55. 1992

Distribution: Neotropics, S-USA

###### *Baja* Windham & L.O.George -- Syst. Bot. 44(3): 479. 2019 \[6 Aug 2019\] \[epublished\]

Distribution: Baja California

###### *Bommeria* E. Fourn. -- Baillon, Dict. Bot. 1: 448 (1877)

Distribution: SW-USA to Costa Rica  
= *Gymnopteris* subgen. Bommeria (E. Fourn.) Christ -- Farnkr. Erde 67 (1897)

###### *Calciphilopteris* Yesilyurt & H.Schneid. -- Phytotaxa 7: 53 (-54). 2010 \[15 Jul 2010\]

Distribution: Trop. Asia to S-China and N-Australia

###### *Cheilanthes* Sw. -- Syn. Fil. (Swartz) 5: 126. 1806 \[Mar-Apr 1806\]

Distribution: North and tropical America, some tropical Africa, Australia. The new and valid lectotypification of Cheilanthes with C. micropteris Sw. makes Cheilanthes the correct name for this genus, consisting of the C. micropteris group.

###### *Cheilanthes* p. p. -- NA

Distribution: 1 sp. Mexico, Central America, placed here by molecular results outside of Cheilanthes s. str.

###### *Cheilanthes* p. p. (skinneri clade) -- NA

Distribution: Mexico. Based on molecular results, these species need to be removed and belong here in a separate clade (Windham et al. 2009). Possibly some more species belong in this group.  
= × *Hemionanthes* Mickel -- Fl. Novo-Galiciana 17: 286. 1992

###### *Cheilanthes* sensu lato -- NA

Distribution: species not yet distributed within spinoff genera of Cheilanthes  
= *Hypolepidopsis* Hieron. -- Hedwigia 62: 28 (1920)  
= *Neurosoria* Mett. ex Kuhn -- Bot. Zeitung (Berlin) 27: 437. 1869

###### *Cheiloplecton* Fée -- Mém. Foug., 7. Ic. Esp. Nouv. 33. 1857 \[1857 or 1858\]

Distribution: Mexico, Central America

###### *Doryopteris* J. Sm. -- J. Bot. (Hook.) 4: 152 (1841), nom. cons.

Distribution: Tropical America, S-India, Malesia, Africa, Madagascar, Australia, S-Pacific, mostly Brazil. Phylogeny see Yesilyurt et al. 2015.  
= *Cassebeera* Kaulf. -- Enum. Filic. 216. 1824 \[8 Apr-28 May 1824\] , Cassebeeria auctt.  
= *Doryopteridastrum* Fée -- Crypt. Vasc. Brésil 1: 42 (1869)  
= *Tryonella* Pic.Serm. -- Webbia 29: 14. 1974

###### *Doryopteris* p. p. -- NA

Distribution: South Africa, Indian Ocean. Placed outside of Doryopteris s. str. by PCR results (Yesilyurt et al. 2015). Maybe a part of redescribed Pellaeopsis or Hemionitis.

###### *Doryopteris* s. lat. -- NA

Distribution: Several species which are probably not part of Doryopteris s. str. but have no current new position, pending molecular results

###### *Gaga* Pryer, Fay W.Li & Windham -- Syst. Bot. 37(4): 855. 2012 \[26 Oct 2012\]

Distribution: SW-USA, Mexico and Central America. This genus contains the former Cheilanthes marginata-group which is related to Aspidotis.  
= *Othonoloma* Link -- Hort. Berol. \[Link\] 2: 41. 1833 \[Jul-Dec 1833\]

###### *Hemionitis* L. -- Sp. Pl. 2: 1077. 1753 \[1 May 1753\]

Distribution: Tropical America  
= *Ampelogramma* J. Sm. -- Ferns Brit. For. 284 (1866)  
= *Cardinitis* J. Sm. -- Hist. Fil. 151 (1875)  
= *Definitifolium* Hieron. -- Bot. Jahrb. Syst. 84: 479 (1904)  
= *Gymnogramma* Desv. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 5(3): 304. 1811 \[Post Sep ? 1811\]  
= *Gymnopteris* Bernh. -- J. Bot. (Schrader) 1799(1): 297 (1799)  
= *Neurogramma* Link -- Fil. Spec. 138. 1841 \[3-10 Sep 1841\]  
= *Schizogramma* Link -- Fil. Spec. 136. 1841

###### *Lytoneuron* (Klotzsch) Yesilyurt -- Phytotaxa 221(2): 116. 2015 \[30 Jul 2015\] \[epublished\]

Distribution: South America (mostly Brazil). Separation from Doryopteris based on molecular results (Yesilyurt et al. 2015)  
= *Doryopteris* sect. Lytoneuron Klotzsch -- Linnaea 20(3): 343 (1847)

###### *Mickelopteris* Fraser-Jenk. -- Annot. Checkl. Ind. Pterid. 1: 246. 2016 \[2017 publ. 28 Dec 2016\]

Distribution: tropical Asia

###### *Mildella* Trevis. -- Rendiconti Reale Ist. Lombardo Sci. ser. 2, 9(20): 810. 1876

Distribution: Mexico, Central America, Caribbean, subtropical Asia, placed here by molecular results outside of Pellaea s. str.

###### *Mineirella* Ponce & Scataglini -- J. Syst. Evol. 60(2): 274. 2020 \[28 Dec 2020\] \[epublished\]

Distribution: South America

###### *Myriopteris* Fée -- Mém. Foug., 5. Gen. Filic. 148. 1852 \[1850-1852\]

Distribution: North America to Chile, mostly Mexico (34 spp.), 1 sp. South Africa. A spin-off genus from Cheilanthes s. lat.  
= *Eriochosma* J. Sm. -- J. Bot. (Hooker) 4: 50 (1841)  
= *Physapteris* C. Presl -- Tent. Pterid. 160 (1836) \[might be the correct name fide Fraser-Jenkins et al. 2017, because it is typified with M. lendigera\]  
= *Pomatophytum* Jones -- Contr. Western Bot. 16: 12 (1930)

###### *Notholaena* R. Br. -- Prodr. Fl. Nov. Holland. 145 (1810)

Distribution: New World. For the reasons to lectotypify Notholaena with N. trichomanoides and apply the name to New World taxa, see Rothfels et al. (2008). This is resisted by many Old World authors (case not settled yet).  
= *Cheilanthes* sect. Notholaena (R. Br.) W. C. Shieh -- J. Sci. Engin. (Natl. Chung-Hsing Univ.) 10: 213 (1973)  
= *Chrysochosma* Kümmerle -- Magyar Bot. Lapok 13: 39. 1914

###### *Oeosporangium* Vis. -- Atti Reale Ist. Veneto Sci. Lett. Arti III. 12: 663. 1867

Distribution: Old World. This is the correct name for Cheilosoria and one Old World Cheilanthes clade fide Fraser-Jenkins et al. (2017) and after rejection of Allosorus (2019). The current circumscription is probably inhomogenous and needs further refinement.  
= *Parallosorus* Keyserl. -- Polyp. Herb. Bunge 5 (1873)

###### *Ormopteris* J.Sm. -- Hist. Fil. 281. 1875

Distribution: Brazil, Venezuela. Separation from Pellaea based on molecular results (Yesilyurt et al. 2015)

###### *Paragymnopteris* K.H.Shing -- Indian Fern J. 10(1-2): 227. 1994 \[1993 publ. 1994\]

Distribution: Old World. There is widespread confusion over the typification of Notholaena. Currently a majority of experts is treating Notholaena as a New World genus, which leaves the name Paragymnopteris to the marantae-group. Possibly both are the same (case still undecided).  
= *Paraceterach* Copel. -- Gen. Fil. \[Copeland\] 75. 1947  
= *Parahemionitis* Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. Palayamkottai 13. 1991 , without Latin descr. & contrary to Art. 42.1

###### *Pellaea* Link -- Fil. Spec. 59. 1841 \[3–10 Sep 1841\]

Distribution: SW-USA, Mexico, to Galapagos and Haiti, South Africa, few east to India, China and New Zealand, N-Spain, introduced Azores. The genus remains polyphyletic. Holcochlaena and Platyloma might be valid genera.  
= *Choristosoria* Mett. ex Kuhn -- Reisen Ost Afr. \[Decken\] 3(3, Bot.): 13. 1879  
= *Cincinalis* Desv. -- Mag. Neuesten Entdeck. Gesammten Naturk. Ges. Naturf. Freunde Berlin 5: 311. 1811  
= *Crypteris* Nutt. -- Sp. Fil. \[W. J. Hooker\] 2: 149. 1858  
= *Holcochlaena* Baker -- Syn. Fil. (Hook. & Baker) 153 (1867)  
= *Holodanaea* C. Presl -- Suppl. Tent. Pterid. 37 (1845)  
= *Hymenoloma* Davenp. -- Bot. Gaz. 21: 262 (1896)  
= *Pellaeopsis* J.Sm. -- Hist. Fil. 289. 1875  
= *Platyloma* J.Sm. -- J. Bot. (Hooker) 4: 160. 1841  
= *Pteridella* Mett. ex Kuhn -- Reisen Ost Afr. \[Decken\] 3(3, Bot.): 13. 1879  
= *Synochlamys* Fée -- Mem. Soc. Sci. Nat. Strasbourg 5: 35. 1857

###### *Pentagramma* Yatsk., Windham & E.Wollenw. -- Amer. Fern J. 80(1): 13. 1990 \[Jun 1990\]

Distribution: W-USA, SW-Canada, NW-Mexico

###### *Trachypteris* André -- Monogr. Elaphoglossum 150. 1899

Distribution: Madagascar (1 sp.), tropical America (3 spp.)  
= *Heteroglossum* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 334 (1899)  
= *Saffordia* Maxon -- Smithsonian Misc. Collect. 61(4): 1. 1913

#### Cryptogrammoideae S.Linds. -- Edinburgh J. Bot. 66(2): 358. 2009 \[15 Jun 2009\]

3 genera, ca. 30 spp.  
= Cryptogramminae Prantl -- Arbeiten Königl. Bot. Gart. Breslau 1: 33 (1892)

###### *Coniogramme* Fée -- Mém. Foug., 5. Gen. Filic. 167. 1852

Distribution: Mostly China and Indochina, few tropical Africa, Java, Japan, Pacific to Hawaii and Samoa.  
= *Dyctiogramme* C.Presl -- Epimel. Bot. 263. 1851 \[Oct 1851\]  
= *Neurosorus* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 2(2): 168. 1851  
= *Notogramme* C.Presl -- Epimel. Bot. 263. 1851 \[Oct 1851\]  
= *Syngramme* J. Sm. -- Lond. J. Bot. 4: 168 (1845)  
= × *Coniodictyogramme* Nakai -- Bull. Natl. Sci. Mus. Tokyo 27: 22. 1949 , nomen

###### *Cryptogramma* R.Br. -- Narr. Journey Polar Sea \[Franklin\] 767. 1823

Distribution: Mostly Asia and North America, 1 to Europe, 1 South America  
= *Homopteris* Rupr. -- Distr. Crypt. Vasc. Ross. 48 (1845)  
= *Phorolobus* Desv. -- Mém. Soc. Linn. Paris 6(3): 291. 1827 \[Jul 1827\] ; Prodr. Foug.

###### *Llavea* Lag. -- Gen. Sp. Pl. \[Lagasca\] 33. 1816

Distribution: Central America  
= *Botryogramma* Fée -- Mém. Foug. 5 (Gen. Filic.): 166 (1852)  
= *Ceratodactylis* J.Sm. in Hook. -- Gen. Fil. \[Hooker\] t. 36. 1839

#### Parkerioideae Burnett -- Outlines Bot. 324 (1835), as ‘Parkeridae’

2 genera  
= Acrostichoideae Link -- Fil. Sp.: 147 (1841)  
= Ceratopteridoideae R.M.Tryon -- Amer. Fern J. 76(4): 184. 1986  
= Acrosticheae C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 4, 5: 228 (1836)  
= Ceratopterideae J. Sm. -- Hist. Fil. 170 (1875), nom. illeg.  
= Ceratopterideae T. Moore -- Index Fil.: xii (1857-1862)  
= Parkerieae Brongn. -- Enum. Pl. Mus. Paris: 5 (1843)  
= Acrostichinae Payer -- Bot. Crypt.: 197 (1850)

###### *Acrostichum* L. -- Sp. Pl. 2: 1067. 1753 \[1 May 1753\] ; et in Genera Plantarum ed. 5 1754

Distribution: Tropical / warm-temperate worldwide  
= *Chrysodium* Fée -- Mém. Foug., 2. Hist. Acrostich. 22, 97. 1845 \[late 1845\]

###### *Ceratopteris* Brongn. -- Bull. Sci. Soc. Philom. Paris 1821: 186. ; Conf. Benedict, Bull. Torr. Cl. 36. 463-476. 1909

Distribution: Worldwide tropics  
= *Cryptogenis* A.Rich. -- Dict. Class. Hist. Nat. \[Bory\] 3. 350. 1823  
= *Ellobocarpus* Kaulf. -- Enum. Filic. 117. 1824 \[8 Apr-28 May 1824\]  
= *Furcaria* Boiv. ex Baill. -- Étude Euphorb. 56. 1858  
= *Parkeria* Hook. -- Exot. Fl. 2(20): t. 147. 1825 \[Mar 1825\]  
= *Teleozoma* R.Br. -- Narr. Journey Polar Sea \[Franklin\] 767. 1823

#### Pteridoideae Link -- Fil. Sp.: 48 (1841)

= Platyzomatoideae (Nakai) A. F. Tryon -- Amer. J. Bot. 51: 942 (1964)  
= Pteridoideae (Link) J. P. Roux -- Lycopods Ferns Drakensberg Lesotho 161 (2016)  
= Taenitidoideae (C. Presl) R. M. Tryon -- Amer. Fern J. 76: 184 (1986)  
= Taenitidoideae Link -- Fil. Sp.: 140 (1841)  
= Platyzomateae (Nakai) R. M. Tryon & A. F. Tryon -- Rhodora 83(833): 135 (1981)  
= Pterideae J. Sm. -- J. Bot. (Hooker) 3: 403 (1841)  
= Taenitideae C. Presl -- Tent. Pterid. 222 (1836)  
= Jamesoniinae Pfeiff. -- Nomencl. Bot. 1(1): 704 (1873)  
= Pterididae Schmakov -- Turczaninowia 4(1-2): 42 (2001)  
= Pteridinae Payer -- Bot. Crypt.: 199 (1850)  
= Taenitidinae Payer -- Bot. Crypt.: 197 (1850)

###### *Actiniopteris* Link -- Fil. Spec. 73, 79. 1841

Distribution: Africa and adjacent islands, 1 sp. east to Afghanistan, Nepal, India, Sri Lanka

###### *Anogramma* Link -- Fil. Spec. 137. 1841

Distribution: Widespread in subtropics (1 sp.), S-South America (1), Indian subcontinent (1)  
= *Dicranodium* Newman -- Hist. Brit. Ferns, ed. 3 13. 1854  
= *Pityrogramma* subgen. Anogramma (Link) Domin -- Spisy Prir. Fak. Karlovy Univ. 88: 9 (1928)

###### *Austrogramme* E.Fourn. -- Ann. Sci. Nat., Bot. sér. 5, 18: 278. 1873

Distribution: New Caledonia (3 spp.), Moluccas, New Guinea, Vanuatu. Exact taxonomic position within clade still uncertain.  
= *Aspleniopsis* Mett. ex Kuhn -- Chaetopterides 324. 1882

###### *Cerosora* (Baker) Domin -- Acta Bot. Bohem. 8: 3. 1929

Distribution: Tropical Asia and S-China (3 spp.), trop. Africa and Indian Ocean (1 sp.)  
= *Anogramma* Sect. Monosorus Domin -- Biblioth. Bot. (1915)  
= *Gymnogramma* sect. Cerosora Baker -- J. Linn. Soc., Bot. 24: 260 (1887)

###### *Cosentinia* Tod. -- Giorn. Sci. Nat. Econ. Palermo 1: 219 (seors. 14). 1866

Distribution: Mediterranean to India. The placement of this species has changed considerably in the past. It was regularly included in Notholaena (which is neotropical, see there) and Old World Cheilanthes, which are now Paragymnopteris.

###### *Gastoniella* Li Bing Zhang & Liang Zhang -- Molec. Phylogen. Evol. 109: 67. 2016 \[31 Dec 2016\] \[epublished\]

Distribution: Trop. America (2 spp.), Ascension Isl. (1 sp.)

###### *Jamesonia* Hook. & Grev. -- Icon. Filic. t. 178. 1830

Distribution: Tropical Andes (usually on high mountains), locally Mexico, Costa Rica, SE-Brazil, 1 Tristan da Cunha  
= *Eriosorus* Fée -- Mém. Foug., 5. Gen. Filic. 152. 1852 \[1850-52\]  
= *Gymnogramma* sect. Jamesonia (Hook. & Grev.) Klotzsch -- Linnaea 20: 407 (1847)  
= *Nephopteris* Lellinger -- Amer. Fern J. 56: 180. 1966  
= *Psilogramme* Kuhn -- Chaetopterides 12. 1882  
= *Psilogramme* sect. Jamesonia (Hook. & Grev.) Kuhn -- Festschr. 50jähr. Jubiläum Königst. Realschule zu Berlin \[Chaetopt.\] 332 (1882)

###### *Onychium* Kaulf. -- Jahrb. d. Pharmacie 45 (1820)

Distribution: Mostly India, Indochina, Himalaya, China, Malesia, 1 to Australia, 1 NE-Africa and Iran. Very complicated taxonomy due to apomixis.  
= *Cryptogrammopsis* Kümmerle -- Amer. Fern J. 20: 133 (1930)  
= *Leptostegia* D. Don -- Prodr. Fl. Nepal. 14 (1825)

###### *Pityrogramma* Link -- Handbuch \[Link\] 3: 19. 1833 ; & Maxon, Contr. U. S. Nat. Herb. 17: 173 (1913)

Distribution: Mostly American tropics, 1 sp. SW-USA, W-USA, 4-5 spp. Africa/Madagascar. Many invalid names and garden forms (described mostly by Domin) have been omitted. The African species probably belong in other genera.  
= *Argyria* Fée -- Mém. Foug. 5 (Gen. Filic.): 183 (1852)  
= *Calomelanos* C. Presl -- Tent. Pterid. 218 (1836)  
= *Cerogramme* Diels -- Engl. & Prantl, Nat. Pflanzenfam. 1(4): 260 (1899)  
= *Ceropteris* Link -- Fil. Spec. 141. 1841  
= *Chrysodia* Fée -- Mém. Foug. 5 (Gen. Filic.): 183 (1852)  
= *Neurogramma* (C. Presl) Link -- Fil. Spec. 138 (1841)  
= *Oligolepis* Cass. ex DC. -- Prodr. \[A. P. de Candolle\] 5: 370. 1836 \[1-10 Oct 1836\]  
= *Trichophylla* Domin -- Spisy Prir. Fak. Karlovy Univ. 88: 8 (1928)  
= *Trismeria* Fée -- Mém. Foug., 5. Gen. Filic. 164. 1852 \[1850-1852\]  
= × *Pityromeria* L.D.Gómez -- Brenesia 16: 96. 1979

###### *Pteris* L. -- Sp. Pl. 2: 1073 (1753)

Distribution: Worldwide  
= *Afropteris* Alston -- Bol. Soc. Brot. sér. 2, 30: 5. 1956 , err. typogr. Aropteris; vide Crabbe, Journ. Soc. Bibl. Nat. Hist. 3: 397. 1960; Pichi-Sermolli Webbia 17: 305. 1963  
= *Anopteris* (Prantl) Diels -- Nat. Pflanzenfam. \[Engler & Prantl\] 1(4): 288. 1899 \[Oct 1899\]  
= *Campteria* C.Presl -- Tent. Pterid. 146. 1836  
= *Copelandiopteris* B.C.Stone -- Webbia 28: 492. 1973  
= *Hemipteris* Rosenst. -- Repert. Spec. Nov. Regni Veg. 5: 38. 1908  
= *Heterophlebium* Fée -- Mém. Foug., 5. Gen. Filic. 139. 1852 \[1850-1852\]  
= *Heteropteris* C. Presl ex Ettingsh. -- Farnkr. Jetztw. 96 (1864)  
= *Idiopteris* T.G.Walker -- Kew Bull. 12(3): 431, t.1. 1958 \[1957 publ. 17 Jan 1958\]  
= *Lathyropteris* Christ -- Bull. Herb. Boissier II(7): 275. 1907  
= *Lemapteris* Raf. -- J. Phys. Chim. Hist. Nat. Arts 89: 262. 1819  
= *Litobrochia* C.Presl -- Tent. Pterid. 148. 1836  
= *Macropteris* Webb & Berthel. -- Hist. nat. Canar. 39, Phyt 3: 450 (1847)  
= *Monogonia* C.Presl -- Tent. Pterid. 146. 1836  
= *Neurocallis* Fée -- Mém. Foug., 2. Hist. Acrostich. 89. 1845  
= *Ochropteris* J.Sm. -- J. Bot. (Hooker) 4: 158. 1841  
= *Parapteris* Keyserl. -- Polyp. Herb. Bunge 4 (1873)  
= *Peripteris* Raf. -- Anal. Nat. 205. 1815 ; & Amer. Monthly Mag. Crit. Rev. 2: 268. 1818; & J. Phys. Chim. Hist. Nat. Arts 89: 262 (1819)  
= *Phyllitis* Raf. -- Amer. Monthly Mag. & Crit. Rev. 4: 195 (1819) (non Hill, nec Moench)  
= *Platyzoma* R.Br. -- Prodr. Fl. Nov. Holland. 160. 1810 \[27 Mar 1810\]  
= *Pteridium* Raf. -- Princ. Somiol. 26 (1814) (non Gled. ex Scop.)  
= *Pycnodoria* C.Presl -- Epimel. Bot. 100. 1851 \[Oct 1851\]  
= *Schizopteris* Hillebr. -- Syn. Fil. (Hooker & Baker), ed. 2. 475. 1874  
= *Schizostege* Hillebr. -- Fl. Hawaiian Isl. \[Hillebrand\] 631. 1888  
= *Schizostegeopsis* Copel. -- Fern Fl. Philipp. 1: 147. 1958  
= *Spathepteris* C.Presl -- Suppl. Tent. Pterid. 95. 1845  
= *Thelypteris* Adans. -- Fam. Pl. 2: 20 (1763)

###### *Pterozonium* Fée -- Mém. Foug., 5. Gen. Filic. 178. 1852 \[1850-1852\]

Distribution: Mostly S-Venezuela (Tepuis), east to Surinam, SW to Colombia and N-Peru  
= *Syngrammatopsis* Alston -- Mutisia 7: 7. 1952  
= *Trichiogramme* Kuhn -- Chaetopterides 5. 1882

###### *Syngramma* J.Sm. -- London J. Bot. 4: 168. 1845

Distribution: Malaysia to Philippines, New Guinea, east to Fiji and Palau (7 in Borneo). Exact taxonomic position within clade still uncertain.  
= *Callogramme* Fée -- Mém. Foug., 5. Gen. Filic. 169. 1852 \[1850-1852\]  
= *Craspedodictyum* Copel. -- Philipp. J. Sci., C 6: 84. 1911 ; & 38: 147. 1929 (clavis sp.).  
= *Toxopteris* Trevis. -- Atti Reale Ist. Veneto Sci. Lett. Arti 5(3): 590. 1877

###### *Taenitis* Willd. ex Spreng. -- Anleit. Kenntn. Gew. 3: 374. 1804 \[28 Mar 1804\] ; & Schkuhr, Kr. Gew. 1. 21. 1804; Sw. Syn. 3. 1806

Distribution: Tropical Asia, Australia, Pacific  
= *Holttumia* Copel. -- Philipp. J. Sci. 74: 153, t. 1. 1941 , non Lloyd  
= *Holttumiella* Copel. -- Philipp. J. Sci. 75: 360. 1941  
= *Platytaenia* Kuhn -- Chaetopterides 330. 1882  
= *Schizolepton* Fée -- Mem. Soc. Mus. Hist. Nat. Strasbourg 4(1): 201. 1850

###### *Tryonia* Schuettp., J.Prado & A.T.Cochran -- PhytoKeys 35: 35. 2014 \[26 Feb 2014\] \[epublished\]

Distribution: Brazil (4 spp.), Colombia (1 spp.)

#### Vittarioideae Crabbe, Jermy & Mickel -- Fern Gaz. 11: 154. 1975

sequence of genera following Schuettpelz et al. 2016  
= Antrophyoideae Link -- Fil. Spec. 140, 3-10 (1841), subfamily  
= Antrophyeae Pfeiff. -- Nomencl. Bot. 1(1): 224 (1872)  
= Vittarieae C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 4, 5: 164 (1836)  
= Antrophyinae Diels -- Engl. & Prantl, Nat. Pflanzenfam. I, 4: 297, 300 (1899)  
= Vittariinae Diels -- Engl. & Prantl, Nat. Pflanzenfam. I, 4: 297 (1899)

###### *Ananthacorus* Underw. & Maxon -- Contr. U.S. Natl. Herb. 10: 487. 1908

Distribution: Trop. America

###### *Antrophyopsis* (Benedict) Schuettp. -- Taxon 65(4): 717. 2016 \[30 Aug 2016\]

Distribution: Trop. Africa, Indian Ocean. Separate genus from Antrophyum fide Schuettpelz et al. 2016  
= *Antrophyum* subgen. Antrophyopsis Benedict -- Bull. Torrey Bot. Club St. 447 (1907)

###### *Antrophyum* Kaulf. -- Enum. Filic. 197, 282. 1824 \[8 Apr-28 May 1824\]

Distribution: Pantropical, mostly SE-Asia  
= *Bathia* C. Chr. -- Bonap., Notes Ptéridol. 16: 110 (1925)

###### *Haplopteris* C. Presl -- Tent. Pterid. 141 (1836), nom. cons. prop.

Distribution: Trop. Asia and Australia.  
= *Monogramma* Schkuhr -- 24. Kl. Linn. Pfl.-Syst. 1: 82. 1809 ; & Desvaux, Berl. Mag. 5. 302. 1811  
= *Pleurofossa* Nakai ex H.Ito -- J. Jap. Bot. 12(6): 408. 1936 \[25 Jun 1936\]  
= *Pleurogramme* R. Br. -- Horsf., Pl. jav. rar. 4 (1838)  
= *Vittaria* sect. Haplopteris (C. Presl) Ching -- Sinensia 1: 176 (1931)  
= *Vittaria* sect. Schizolomatopsis Zhang -- (1999)  
= *Vittaria* subgen. Haplopteris (C. Presl) C. Chr. -- Index Filic. 46 (1906)

###### *Hecistopteris* J.Sm. -- London J. Bot. 1: 193. 1842

Distribution: Tropical America

###### *Polytaenium* Desv. -- Mém. Soc. Linn. Paris 6: 174. 1827 \[May 1827\] , (218: Polyaetnium); =‘Prodrome’

Distribution: Trop. Americas. Inclusion of Anetium fide Schuettpelz et al. 2016  
= *Acrostichum* sect. Anetium Kunze -- Flora Beibl., 1: 47 (1839)  
= *Anetium* (Kunze) Splitg. -- Tijdschr. Natuurl. Gesch. Physiol. 7: 395. 1840  
= *Antrophyum* subgen. Polytaenium (Desv.) Bened. -- Bull. Torrey Bot. Club 34: 447 (1907)  
= *Pteridanetium* Copel. -- Gen. Fil. \[Copeland\] 224. 1947

###### *Radiovittaria* (Benedict) E. H. Crane -- Syst. Bot. 22: 515 (1997 publ. 1998)

Distribution: Trop. America  
= *Vittaria* subgen. Radiovittaria Benedict -- Bull. Torrey Bot. Club 38: 166 (1911)

###### *Rheopteris* Alston -- Nova Guinea ser. 2, 7: 2. 1956

Distribution: New Guinea. Taxonomic position according to Ruhfel et al. 2008.

###### *Scoliosorus* T. Moore -- Index Filic. (T. Moore) 29 (1857)

Distribution: Trop. America  
= *Antrophyum* subgen. Scoliosorus (T. Moore) Bened. -- Bull. Torrey Bot. Club 34: 447 (1907)

###### *Vaginularia* Fée -- Congr. Sci. France 10(1): 178. 1843 ; & 3 memoire 50. 1851-52

Distribution: Trop. Asia and S-China, 1 to Australia, 1-2 Pacific. A valid genus separate from Monogramma fide Ruhfel et al. (2008) and Schuettpelz et al. (2016).  
= *Diclidopteris* Brack. -- U.S. Expl. Exped., Filic. 16: 135. 1854 ; C. Wilkes Expl. Exped.

###### *Vittaria* Sm. -- Mém. Acad. Roy. Sci. (Turin) 5: 413, t.9(5). 1793

Distribution: New World, only 1 species Africa  
= *Oetosis* Neck. ex Greene -- Pittonia 4: 105 (1900)  
= *Taeniopsis* J.Sm. -- J. Bot. (Hooker) 4: 67. 1841  
= *Taeniopteris* Hook. -- Gen. Fil. \[Hooker\] t. 76 B. 1842

### Pteridryaceae Li Bing Zhang, X.M.Zhou, Liang Zhang & N.T.Lu -- J. Syst. Evol. 56(2): 157. 2018 \[8 Feb 2018\] \[epublished\]

4 genera, ca. 30 spp. The family was accepted as separate from Tectariaceae by PPG-II.

###### *Draconopteris* Li Bing Zhang & Liang Zhang -- Taxon 65(4): 732. 2016 \[30 Aug 2016\]

Distribution: Trop. America

###### *Malaifilix* Li Bing Zhang & Schuettp. -- Taxon 65(4): 733. 2016 \[30 Aug 2016\]

Distribution: Malesia

###### *Polydictyum* C.Presl -- Epimel. Bot. 52. 1851 \[Oct 1851\]

Distribution: Trop. Asia, 1 SW-Pacific. Separate genus from Tectaria fide Dong et al. (2017).

###### *Pteridrys* C.Chr. & Ching -- Bull. Fan Mem. Inst. Biol. Bot. 5: 129. 1934

Distribution: Vietnam (many), India, Sri Lanka, SE-China to Taiwan and New Guinea. Monograph: X. M. Zhou & Li Bing Zhang (2019)

### Rhachidosoraceae X.C.Zhang -- Phytotaxa 19: 16. 2011 \[18 Feb 2011\]

1 genus, 8 spp. Family status confirmed by Rothfels et al. (2012). According to Fraser-Jenkins et al. (2018) it should be included in Woodsiaceae s. lat.  
= Rhachidosoroideae M.L.Wang & Y.T.Hsieh -- Acta Phytotax. Sin. 42(6): 527. 2004 \[Nov 2004\]

###### *Rhachidosorus* Ching -- Acta Phytotax. Sin. 9(1): 73. 1964 \[18 Jan 1964\]

Distribution: E-Asia, tropical Asia

### Saccolomataceae Doweld -- Phytologia 90(3): 417. 2008 \[Dec 2008\]

1-2 genera, 21 spp.

###### *Orthiopteris* Copel. -- Bull. Bernice P. Bishop Mus. 59: 14. 1929 ; & Univ. Calif. Publ. Bot. 16: 79. 1929

Distribution: Tropical Asia and W-Pacific (8), 1 Madagascar. Revision: Luong et al. 2015. Frequently included in Saccoloma s. lat.  
= *Ithycaulon* Copel. -- Univ. Calif. Publ. Bot. 16: 79. 1929  
= *Neuropteris* Desv. -- Mém. Soc. Linn. Paris 6(3): 292. 1827 \[Jul 1827\] ; = ‘Prodrome de la famille Fougères’  
= *Parasaccoloma* Keyserl. -- Polyp. Herb. Bunge 4 (1873)

###### *Saccoloma* Kaulf. -- Berlin. Jahrb. Pharm. Verbundenen Wiss. 21: 51. 1820 ; & Enum. Fil. 224. 1824

Distribution: Neotropical

### Tectariaceae Panigrahi -- J. Orissa Bot. Soc. 8(1): 41. 1986

3 genera, ca. 310 spp.  
= Dictyoxiphiaceae Ching -- Sunyatsenia 5: 218 (1940), nom. nud.  
= Tectariaceae Lellinger -- Amer. Fern J. 77(3): 102 (1987 publ. 1988), isonym  
= Tectarioideae B. K. Nayar -- Taxon 19: 235 (1970), Subfamily  
= Hypoderridinae Hook. -- Sp. Fil. 1: 56, 57 (1844)

###### *Hypoderris* R.Br. -- Pl. Asiat. Rar. (Wallich). 1: 16. 1829 ; & J. Smith in Hook. Gen. Fil. t. 1. 1838

Distribution: Caribbean, Central America, Andes from N-Venezuela to Bolivia

###### *Tectaria* Cav. -- Anales Hist. Nat. 1(2): 115. 1799 \[Dec 1799\] ; & Descripcion d. l. plantas 249. 1802.

Distribution: Pantropical and south-temperate, America (35-40). Inclusion of many previous split genera fide Dong (2014) and Wang et al. (2014). Fraser-Jenkins et al. (2018) argue for keeping at least Heterogonium separate, and Dong et al. (2017) separate Polydictyum again.  
= *Aenigmopteris* Holttum -- Blumea 30(1): 3. 1984  
= *Amphiblestra* C.Presl -- Tent. Pterid. 150. 1836  
= *Aspidium* Sw. -- J. Bot. (Schrader) 1800(2): 29. 1801 \[Oct-Dec 1801\]  
= *Bathmium* (C.Presl) C.Presl ex Link -- Fil. Spec. 99, 114. 1841 \[Sep 1841\]  
= *Camptodium* Fée -- Mém. Foug., 5. Gen. Filic. 298. 1852  
= *Cardiochlaena* Fée -- Mém. Foug., 5. Gen. Filic. 314. 1852 \[1850-1852\]  
= *Chlamydogramme* Holttum -- Gard. Bull. Singapore 39(2): 157. 1987 \[1986 publ. 1987\]  
= *Cionidium* T.Moore -- Gard. Companion Florists’ Guide 143. 1852  
= *Ctenitopsis* Ching ex Tardieu & C.Chr. -- Notul. Syst. (Paris) 7: 86. 1938 \[Oct 1938\] ; et in Ching, Bull. Fan Mem. Inst. Biol. Bot. 8: 304 (Nov 1938)  
= *Depariopsis* Baker -- Ann. Bot. (Oxford) 5: 462 (1891)  
= *Dictyoxiphium* Hook. -- Gen. Fil. \[Hooker\] t.62. 1840  
= *Dryomenis* Fée -- Mém. Foug., 5. Gen. Filic. 225. 1852 \[1850-1852\]  
= *Fadyenia* Endl. -- Gen. Pl. Suppl. \[Endlicher\] 2: 30. 1842 \[Mar-Jun 1842\]  
= *Grammatosorus* Regel -- Index Seminum \[St.Petersburg (Petropolitanus)\] 75. 1866 ; & Gartenflora 15. 335. 1866  
= *Hemigramma* Christ -- Bull. Herb. Boissier II(6): 1006. 1906 , nota; & Phil. Journ. Sci. Bot. 2. 170. 1907  
= *Heterogonium* C.Presl -- Epimel. Bot. 142. 1851 \[Oct 1851\]  
= *Lenda* Koidz. -- Acta Phytotax. Geobot. 5(2): 142. 1936 \[30 May 1936\]  
= *Lobochlaena* Fée -- Mém. Foug. 5 (Gen. Filic.): 315 (1852)  
= *Luerssenia* Kuhn ex Luerss. -- Bot. Centralbl. 3(11): 77. 1882  
= *Melanopteris* J.Sm. -- Index Fil. (T.Moore) 6: cxliv. 1859 \[Jan 1859\]  
= *Microbrochis* C.Presl -- Epimel. Bot. 51. 1851 \[Oct 1851\]  
= *Palma*-Filix Adans. -- (1763)  
= *Patanema* J.Sm. -- Index Fil. (T.Moore) 2: xcviii. 1857  
= *Phlebiogonium* Fée -- Mém. Foug., 5. Gen. Filic. 314. 1852 \[1850-1852\]  
= *Podopeltis* Fée -- Mém. Foug., 5. Gen. Filic. 286. 1852 \[1850-1852\]  
= *Psomiocarpa* C.Presl -- Epimel. Bot. 161. 1851 \[Oct 1851\]  
= *Quercifilix* Copel. -- Philipp. J. Sci. 37: 408. 1928 , Polypodiaceae Gen. 37  
= *Sagenia* C.Presl -- Tent. Pterid. 86. 1836 \[ante 2 Dec 1836\]  
= *Stenosemia* C.Presl -- Tent. Pterid. 237. 1836  
= *Tectaridium* Copel. -- Philipp. J. Sci. 30: 329. 1926  
= *Trichiocarpa* (Hook.) J.Sm. -- Cat. Ferns Kew 7. 1856  
= × *Pleuroderris* Maxon -- J. Wash. Acad. Sci. 24(12): 550. 1934 \[15 Dec 1934\]

###### *Triplophyllum* Holttum -- Kew Bull. 41(2): 239. 1986 \[22 Jul 1986\]

Distribution: Trop. Africa and Madagascar (18), West Indies and N-South America (9)

### Thelypteridaceae Pic.Serm. -- Webbia 24(2): 709. 1970 \[28 Apr 1970\]

5-34 genera (depending on genus concept), 1100-1200 spp. New genus concept adopted here from Fawcett & Smith (2021), based on molecular results.

#### Phegopteridoideae Salino, A.R.Sm. & T.E.Almeida -- J. Syst. Evol. 54(6): 594. 2016 \[14 Feb 2016\] \[epublished\]

= Phegopteridinae Ching -- Acta Phytotax. Sin. 8: 296 (1963), nom. superfl.  
= Phegopteridinae Rouy -- Fl. France \[Rouy & Foucaud\] 14: 397 (1913)

###### *Macrothelypteris* (H. Itô) Ching -- Acta Phytotax. Sin. 8: 308 (1963)

Distribution: Trop/subtrop. Asia, Malesia, Queensland, Pacific, Africa  
= *Thelypteris* sect. Macrothelypteris H. Itô -- Nakai & Honda, Nov. Fl. Jap. 4: 141 (1938)  
= *Thelypteris* sect. Metathelypteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 145 p. (1965)  
= *Thelypteris* subgen. Macrothelypteris (H. Itô) A. R. Sm. -- Phytologia 34: 233 (1976)

###### *Phegopteris* (C. Presl) Fée -- Mém. Foug. 5 (Gen. Filic.): 242 (1852)

Distribution: North-temperate Asia, Europe and North America. Species delimitation see Fujiwara et al. 2021  
= *Lastrella* (H. Itô) Nakai -- J. Jap. Bot. 24: 8 (1949)  
= *Phegopteris* sect. Lastrella H. Itô -- Nakai & Honda, Nov. Fl. Jap. 4: 152 (1939)  
= *Polypodium* subgen. Phegopteris (C. Presl) C. B. Clarke -- Trans. Linn. Soc. London, Bot. 1: 542 (1880)  
= *Polypodium* subgen. Phegopteris C. Presl -- Tent. Pterid. 179 (1836) (p. p.)  
= *Thelypteris* subgen. Phegopteris (C. Presl) Ching -- Bull. Fan Mem. Inst. Biol. Bot. 6: 250 (1936)  
= *Thelypteris* subgen. Phegopteris sect. Lastrella K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31 (1964), 25: 137 (1965)  
= *Thelypteris* subgen. Phegopteris sect. Phegopteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 25 (1964) and sect. Lastrella (p. p.)

###### *Pseudophegopteris* Ching -- Acta Phytotax. Sin. 8(4): 313. 1963 \[18 Oct 1963\]

Distribution: tropical Africa (and St. Helena, Sao Tome), Indian Ocean, S-China and Himalaya, through Malesia to Fiji and Hawaii  
= *Toppingia* O.Deg., I.Deg. & A.R.Sm. ex O.Deg. & I.Deg. -- Fl. Hawaiiensis \[Degener\] 7: fam. 17b. 1968

#### Thelypteroideae C. F. Reed -- Phytologia 17: 254 (1968)

= Leptogrammeae Todaro -- Syn. Pl. Acot. Vasc.: 13 (1866)  
= Meniscieae Pfeiff. -- Nomencl. Bot. 1(1): 628 (1872 publ. 1873)  
= Cyclosorinae Ching -- Acta Phytotax. Sin. 8: 296 (1963)  
= Dictyoclineae Ching -- Acta Phytotax. Sin. 8: 296 (1963)  
= Goniopteridinae Ching -- Acta Phytotax. Sin. 8: 296 (1963)  
= Menisciinae Payer -- Bot. Crypt.: 197 (1850)  
= Pseudocyclosorinae Ching -- Acta Phytotax. Sin. 8: 296 (1963)  
= Thelypteridinae Ching -- Acta Phytotax. Sin. 8: 295 (1963)

###### *Abacopteris* Fée -- Congr. Sci. France 10(1): 178. 1843

Distribution: continental SE-Asia, Malesia, Australia, ?Africa  
= *Cyclosorus* subgen. Abacopteris (Fée) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Dryopteris* sect. Abacopteris C. Chr. -- Gard. Bull. Straits Settlem. 7: 247 (1934)  
= *Thelypteris* subgen. Abacopteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 34 (1964)

###### *Amauropelta* Kunze -- Farnkräuter 1: 86, 109. 1843

Distribution: Neotropics, few Nearctic, Pacific, trop. Africa and Indian Ocean. The validity of the names coined in the thesis of Alvarez-Fuentes (2010) is still heavily disputed because the publication possibly does not count as effectively published.  
= *Amauropelta* subg. Parathelypteris (H. Ito) S. E. Fawc. & A. R. Sm. -- A generic revision of the Thelypteridaceae: 28 (2021)  
= *Oochlamys* Fée -- Mém. Foug., 5. Gen. Filic. 297. 1852 \[1850-1852\]  
= *Parathelypteris* (H. Itô) Ching -- Acta Phytotax. Sin. 8: 300 (1963)  
= *Thelypteris* subgen. Amauropelta (Kunze) A. R. Sm. -- Amer. Fern J. 63: 121 (1973)  
= *Wagneriopteris* Á.Löve & D.Löve -- Taxon 26(2-3): 325. 1977

###### *Amblovenatum* J.P.Roux -- Strelitzia 23: 200 (-201). 2009

Distribution: Trop. Asia and Africa  
= *Amphineuron* Holttum -- Blumea 19(1): 45. 1971 \[15 Nov 1971\]  
= *Thelypteris* subgen. Amphineuron (Holttum) Fraser-Jenk. -- New Species Syndr. Indian Pteridol. 255 (1997)

###### *Ampelopteris* Kunze -- Bot. Zeitung (Berlin) 6: 114. 1848

Distribution: Africa, SE-Asia  
= *Cyclosorus* subgen. Ampelopteris (Kunze) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Meniscium* sect. Ampelopteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 39 (1964)  
= *Thelypteris* sect. Ampelopteris (Kunze) C. F. Reed -- Phytologia 17: 255 (1968)

###### *Chingia* Holttum -- Blumea 19: 31. 1971

Distribution: Malesia, Australia

###### *Christella* H. Lév. -- Fl. du Kouy-tcheou 472 (1915), emend. Holttum (1971)

Distribution: mostly restricted to the Old World tropics and subtropics, from Africa (4) through India and southeast Asia, China, Japan, and Malesia, Melanesia, and Polynesia; 2 neotropics. Some African (etc.) members await transfer into other genera.  
= *Christella* sect. Pelazoneuron Holttum -- J. S. Afr. Bot. 40: 144 (1974)  
= *Thelypteris* sect. Christella (H. Lév.) Fraser-Jenk. -- Taxon. Revis. Indian Subcontinental Pteridophytes 590 (2008)

###### *Coryphopteris* Holttum -- Blumea 19: 33. 1971

Distribution: mostly Malesia, to Melanesia and Polynesia, S-Himalayas, some to S-Russia, one single species in North America  
= *Parathelypteris* sect. Melanostipes Ching -- Acta Phytotax. Sin. 8: 301 (1963) (p. p.)  
= *Thelypteris* subgen. Coryphopteris (Holttum) Fraser-Jenk. -- New Species Syndr. Indian Pteridol. 255 (1997)

###### *Cyclogramma* Tagawa -- Acta Phytotax. Geobot. 7(1): 52. 1938 \[28 Feb 1938\]

Distribution: N-India to S-China, Taiwan, Philippines  
= *Glaphyropteris* sect. Cyclogramma (Tagawa) H. Itô -- Nakai & Honda, Nov. Fl. Jap. 4: 148 (1939)  
= *Thelypteris* subgen. Cyclogramma K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 26 (1964)

###### *Cyclosorus* Link -- Hort. Berol. \[Link\] 2: 128. 1833 \[Jul-Dec 1833\]

Distribution: 1 pan- and subtropical, 1 Africa  
= *Cyclosorus* subgen. Cyclosoriopsis (K. Iwats.) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Dryopteris* subgen. Cyclosorus (Link) C. Chr. -- Index Filic. 21 (1906)  
= *Nephrodium* Schott -- Gen. Fil. t. 10 (1834)  
= *Thelypteris* subgen. Cyclosoriopsis K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 28 (1964)  
= *Thelypteris* subgen. Cyclosorus (Link) C. V. Morton -- Amer. Fern J. 53: 153 (1963)

###### *Glaphyropteridopsis* Ching -- Acta Phytotax. Sin. 8(4): 320. 1963 \[18 Oct 1963\]

Distribution: NE-India, China, Taiwan. The number of Chinese species will most likely be greatly reduced on careful revision.

###### *Goniopteris* C. Presl -- Tent. Pterid. 181 (1836)

Distribution: Neotropics.  
= *Polypodium* subgen. Goniopteris (C. Presl) C. B. Clarke -- Trans. Linn. Soc. London, Bot. 1: 547 (1880)  
= *Thelypteris* sect. Goniopteris (C. Presl) C. F. Reed -- Phytologia 17: 254 (1968)  
= *Thelypteris* subgen. Goniopteris (C. Presl) Duek -- Adansonia n. s. 11: 720 (1971)

###### *Grypothrix* (Holttum) S.E.Fawc. & A.R.Sm. -- Sida, Bot. Misc. 59: 46. 2021 \[11 Oct 2021\] \[epublished\]

Distribution: Indochina, Malesia to S-China and Australia

###### *Hoiokula* S.E.Fawc. & A.R.Sm. -- Sida, Bot. Misc. 59: 48. 2021 \[11 Oct 2021\] \[epublished\]

Distribution: Hawaii

###### *Leptogramma* J. Sm. -- J. Bot. (Hook.) 4: 51 (1841)

Distribution: Mostly Himalayas (S-China) to Japan and Malesia, 1 South Africa, 1 Europe, 2 North America  
= *Craspedosorus* Ching & W.M.Chu -- Acta Phytotax. Sin. 16(4): 24. 1978 \[18 Nov 1978\]  
= *Thelypteris* subgen. Leptogramma (J. Sm.) C. F. Reed -- Phytologia 17: 254 (1968)

###### *Menisciopsis* (Holttum) S. E. Fawc. & A. R. Sm. -- A generic revision of the Thelypteridaceae: 52 (2021)

Distribution: Himalaya, Malesia, Pacific, Hawaii (3)

###### *Meniscium* Schreb. -- Gen. Pl., ed. 8\[a\]. 2: 757. 1791 \[May 1791\]

Distribution: tropical New World  
= *Phegopteris* subgen. Meniscium (Schreb.) Christ -- Farnkr. Erde 269 (1897)  
= *Thelypteris* subgen. Meniscium (Schreb.) C. F. Reed -- Phytologia 17: 254 (1968)

###### *Menisorus* Alston -- Bol. Soc. Brot. sér. 2, 30: 20. 1956

Distribution: tropical Africa

###### *Mesophlebion* Holttum -- Blumea 19: 29. 1971

Distribution: Malesia, S-Indochina  
= *Mesoneuron* Ching -- Acta Phytotax. Sin. 8(4): 325. 1963 \[18 Oct 1963\]  
= *Thelypteris* subgen. Glaphyropteridopsis sect. Mesoneuron K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 30 (1964)

###### *Mesopteris* Ching -- Acta Phytotax. Sin. 16(4): 21. 1978 \[18 Nov 1978\]

Distribution: S-China, N-Indochina

###### *Metathelypteris* (H. Itô) Ching -- Acta Phytotax. Sin. 8: 304 (1963)

Distribution: E-Asia south to Malesia, Solomon Isl., Sri Lanka, Africa, Fernando Póo, São Tomé, South Africa  
= *Thelypteris* sect. Metathelypteris H. Itô in Nakai & Honda -- Nov. Fl. 137 (1939)

###### *Oreopteris* Holub -- Folia Geobot. Phytotax. 4: 46. 1969

Distribution: Asia, Europe  
= *Lastrea* Bory -- Dict. Class. Hist. Nat. \[Bory\] 6: 588. 1824  
= *Nephrodium* subgen. Lastrea Hook. -- Sp. Fil. \[W. J. Hooker\] 4: 5, 84 (1862)  
= *Thelypteris* subgen. Lastrea (Hook.) Alston -- J. Washington Acad. Sci. 48: 232 (1958)

###### *Pakau* S.E.Fawc. & A.R.Sm. -- Sida, Bot. Misc. 59: 61. 2021 \[11 Oct 2021\] \[epublished\]

Distribution: Australia, New Zealand

###### *Pelazoneuron* (Holttum) A. R. Sm. & S. E. Fawc. -- A generic revision of the Thelypteridaceae: 63 (2021)

Distribution: trop. America north to S-USA

###### *Plesioneuron* (Holttum) Holttum -- Blumea 22: 232. 1975 \[10 Mar 1975\]

Distribution: Malesia, Pacific islands to Tahiti  
= *Mesophlebion* subgen. Plesioneuron Holttum -- Blumea 19: 30 (1971)

###### *Pneumatopteris* Nakai -- Bot. Mag. (Tokyo) 47: 179. 1933

Distribution: Malesia, Pacific. Many species need transfer into other genera.  
= *Cyclosorus* subgen. Pneumatopteris (Nakai) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Thelypteris* subgen. Pneumatopteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 33 (1964), excl. sect. Macrocyclosorus

###### *Pronephrium* C.Presl -- Epimel. Bot. 258. 1851 \[Oct 1851\]

Distribution: trop. Asia, few Madagascar, Australia, Pacific  
= *Dimorphopteris* Tagawa & K. Iwats. -- Acta Phytotax. Geobot. 19: 8 (1961)  
= *Haplodictyum* C. Presl -- Abh. Königl. Böhm. Ges. Wiss., ser. 5, 6: 50 (1851)  
= *Nannothelypteris* Holttum -- Blumea 19: 38. 1971  
= *Pronephrium* subgen. Menisciopsis Holttum -- Fl. Males. Ser. 2,1(5): 530 (1982)  
= *Thelypteris* subgen. Dimorphopteris K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 35 (1964)  
= *Thelypteris* subgen. Haplodictyum K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 32 (1964)

###### *Pseudocyclosorus* Ching -- Acta Phytotax. Sin. 8(4): 322. 1963 \[18 Oct 1963\]

Distribution: Tropical Africa (3), India and Himalaya, China, SE-Asia, Philippines. Revision for Himalayas: Li et al. 2019  
= *Cyclosorus* subgen. Pseudocyclosorus (Ching) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Thelypteris* sect. Pseudocyclosorus (Ching) Fraser-Jenk. -- Taxon. Revis. Indian Subcontinental Pteridophytes 590 (2008)

###### *Reholttumia* S.E.Fawc. & A.R.Sm. -- Sida, Bot. Misc. 59: 76. 2021 \[11 Oct 2021\] \[epublished\]

Distribution: Malesia, some Pacific, Australasia, possibly also Africa

###### *Sphaerostephanos* J. Sm. -- Hook. & Baker, Gen. Fil. t. 24 (1839)

Distribution: Tropical Africa, Asia, Pacific Islands.  
= *Cyclosorus* subgen. Sphaerostephanos (J. Sm.) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Mesochlaena* R.Br. -- Pl. Jav. Rar. (Bennett) 1: 5. 1838  
= *Proferea* C.Presl -- Epimel. Bot. 259. 1851 \[Oct 1851\]  
= *Thelypteris* subgen. Glaphyropteridopsis sect. Neocyclosorus K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 30 (1964) (quoad spec. typ.)  
= *Thelypteris* subgen. Pneumatopteris sect. Macrocyclosorus K. Iwats. -- (quoad spec. typ.)  
= *Thelypteris* subgen. Sphaerostephanos K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 32 (1964)

###### *Stegnogramma* Blume -- Enum. Pl. Javae 2: 172. 1828

Distribution: Africa, Europe, Asia, Malesia, 2 spp. New World to Honduras. The genus still contains some doubtful Chinese names.  
= *Dictyocline* T. Moore -- Gard. Chron. 854 (1856)  
= *Gymnogramma* subgen. Stenogramma (Blume) C. B. Clarke -- Trans. Linn. Soc. London, Bot. 1: 569 (1880)  
= *Thelypteris* sect. Stegnogramma (Blume) Fraser-Jenk. -- Taxon. Revis. Indian Subcontinental Pteridophytes 590 (2008)  
= *Thelypteris* subgen. Dictyocline (T. Moore) C. F. Reed -- Phytologia 17: 254 (1968)  
= *Thelypteris* subgen. Stegnogramma (Blume) C. F. Reed -- Phytologia 17: 254 (1968)

###### *Steiropteris* (C. Chr.) Pic. Serm. -- Webbia 28: 449 (1973)

Distribution: Neotropics. Status, position and separation from Thelypteris see Salino et al. (2015)  
= *Dryopteris* subgen. Glaphyropteris (Fée) C. Chr. -- Biol. Arb. tilegn. Eng. Warming 80 (1911)  
= *Glaphyropteris* (Fée) C. Presl -- Abh. Königl. Böhm. Ges. Wiss., Math.-Naturw. Cl. V, 5: 6: 344 (1848), nomen  
= *Glaphyropteris* (Fée) C. Presl ex Fée -- Crypt. Vasc. Brésil 2: 40 (1873)  
= *Glaphyropteris* Fée -- Crypt. Vasc. Brésil 2: 40 (1873)  
= *Phegopteris* subgen. Glaphyropteris Fée -- Hist. Foug. Lycop. Antill. 58 (1866)  
= *Steiropteris* subgen. Glaphyropteris (Fée) A. R. Sm. -- PhytoKeys 57: 44 (2015)  
= *Thelypteris* sect. Glaphyropteris (Fée) C. V. Morton -- Amer. Fern J. 51: 31 (1961)  
= *Thelypteris* subgen. Glaphyropteris (Fée) Alston -- J. Washington Acad. Sci. 48: 234 (1958)  
= *Thelypteris* subgen. Steiropteris (C. Chr.) K. Iwats. -- Mem. Coll. Sci. Univ. Kyoto, B, Biol. 31: 31 (1964)

###### *Strophocaulon* S.E.Fawc. & A.R.Sm. -- Sida, Bot. Misc. 59: 87. 2021 \[11 Oct 2021\] \[epublished\]

Distribution: Indian Ocean, Malesia, N-Australia, Oceania

###### *Thelypteris* Schmidel -- Ic. Pl. (ed. Keller): 3rd page, t. 11, text (1763), nom. cons.

Distribution: 1 sp. north-temperate, 1 sp. south-temperate  
= *Asterochlaena* Garcke -- Bot. Zeitung (Berlin) 8: 666. 1850

###### *Trigonospora* Holttum -- Blumea 19: 29, f.4,4a. 1971 \[15 Nov 1971

Distribution: Sri Lanka, the others India to SE-Asia. There is disagreement about the status of the Sri Lankan endemics.  
= *Cyclosorus* subgen. Trigonospora (Holttum) Panigrahi -- Abstr. & Souv. Nation. Symp. Curr. Trends Pterid. 4-6 October 1991: 13 (1991)  
= *Thelypteris* sect. Trigonospora (Holttum) Fraser-Jenk. -- Taxon. Revis. Indian Subcontinental Pteridophytes 590 (2008)  
= *Thelypteris* subgen. Trigonospora (Holttum) Fraser-Jenk. -- New Species Syndr. Indian Pteridol. 281 (1997)

###### × *Abacopterella* T.E.Almeida & A.R.Field -- Austrobaileya 13: 43. 2023 \[10 May 2023\] \[epublished\]

Abacopteris x Christella

###### × *Chrinephrium* Nakaike -- New Fl. Jap. Pterid. 839. 1992

Christella x Grypothrix (cf.)

###### × *Chrismatopteris* Quansah & D.S.Edwards -- Kew Bull. 41(4): 805. 1986 \[20 Oct 1986\]

Christella x Pneumatopteris

###### × *Christelliopsis* Miles K.Thomas -- Amer. Fern J. 113(3): 215. 2023 \[29 Sep 2023\] \[epublished\]

Distribution: Hawaii

###### × *Glaphyrocyclosorus* Xia Wan & Li Bing Zhang -- Phytotaxa 575(1): 105. 2022 \[6 Dec 2022\] \[epublished\]

Distribution: Taiwan  
= xGlaphypseudosorus Hong M. Liu, Schuettp. & H.Schneid. -- J. Syst. Evol. 58(6): 1000 (2020)

### Woodsiaceae Herter -- Revista Sudamer. Bot. 9: 14. 1949 \[Jun 1949\]

2 genera, ca. 50 spp. Systematics see Lu et al. (2020).  
= Protowoodsioideae Shmakov -- Turczaninowia 4(1-2): 65. 2001  
= Woodsioideae Shmakov -- Turczaninowia 4(1-2): 63. 2001  
= Woodsieae A. Gray -- Man. Bot. ed. 2: 588 (1856)  
= Woodsiinae Hook. -- Sp. Fil. 1: 58 (1844)

###### *Physematium* Kaulf. -- Flora 12(1): 341. 1829

Distribution: North America (subgen. Woodsiopsis), New World and southern Africa/Madagascar (subgen. Physematium), C-Asia to E-Asia (subgen. Cheilanthopsis)  
= *Cheilanthopsis* Hieron. -- Notizbl. Bot. Gart. Berlin-Dahlem 7: 406-409. 1920  
= *Hymenocystis* C.A.Mey. -- Verz. Pfl. Casp. Meer. (C.A. von Meyer). 229. 1831  
= *Physematium* subgen. Cheilanthopsis (Hieron.) Li Bing Zhang, N.T.Lu & X.F.Gao -- Taxon 68(6): 1166 (2020)  
= *Physematium* subgen. Woodsiopsis (Shmakov) Li Bing Zhang, N.T.Lu & X.F.Gao -- Taxon 68(6): 1166 (2020)  
= *Protowoodsia* Ching -- Lingnan Sci. J. 21: 36. 1945  
= *Woodsia* subgen. Cheilanthopsis (Hieron.) X. C. Zhang & R. Wei -- PLoS ONE 13(2): e0136318 (13) (2015)  
= *Woodsiopsis* Shmakov -- Turczaninowia 18(2): 12. 2015

###### *Woodsia* R.Br. -- Prodr. Fl. Nov. Holland. 158. 1810 \[27 Mar 1810\] , in obs.; & Tr. Linn. Soc. 11: 170. 1815

Distribution: North-temperate holarctic, few China and Taiwan (subgen. Eriosorus).  
= *Acrolysis* Nakai -- Bot. Mag. (Tokyo) 89: 176 (1925)  
= *Aizopsis* Grulich -- Preslia 56(1): 35 (1984).  
= *Eriosoriopsis* (Kitag.) Ching & S.H.Wu -- Fern Fam. Gen. China 402. 1991 \[1991\]  
= *Petrinia* Hook. -- Sp. Fil. \[W. J. Hooker\] 1: 62 (1844)  
= *Trichocyclus* N.E.Br. -- Bothalia i. 151 (1923); et in Gard. Chron. 1925, Ser. III. lxxviii. 433. inclavi.  
= *Woodsia* subgen. Eriosorus (Ching) Shmakov -- Pterid. New Millenn. 59 (2003)

###### × *Woodsimatium* Li Bing Zhang, N.T.Lu & X.F.Gao -- Taxon 68(6): 1167. 2020 \[21 Feb 2020\] \[epublished\]

Distribution: North America
