---
title: "World Flora Online"
author: "PPG Coordinating Committee"
toc: true
date: "2025-04-04"
bibliography: references.yaml
---

## About WFO

[World Flora Online (**WFO**)](https://about.worldfloraonline.org/) is a digital flora including all land plants(bryophytes and vascular plants).
It was initiated during the 11th Conference of the Parties to the Convention on Biological Diversity in October 2012 in response to Target 1 ("An online flora of all known plants") of the Global Strategy for Plant Conservation (GSPC) of the U.N. Convention on Biological Diversity.

The WFO is a [collaborative, international project](https://about.worldfloraonline.org/who-we-are) that is supported by multiple institutions, including the Missouri Botanical Garden, the New York Botanical Garden, the Royal Botanic Garden Edinburgh, and the Royal Botanic Gardens, Kew.

WFO data are widely used, including major databases such as [Catalog of Life (CoL)](https://www.catalogueoflife.org/) and the [Global Biodiversity Information Facility (GBIF)](https://www.gbif.org/).

## About TENs

WFO does not take a "top-down" approach to taxonomy.
Rather, the data in WFO are maintained by [Taxonomic Expert Networks, or **TENs**](https://about.worldfloraonline.org/tens).
Each TEN is composed of expert taxonomists for a certain group of plants (for example, [Fabaceae](https://about.worldfloraonline.org/tens/fabaceae)).

[PPG is the TEN for ferns and lycophytes in WFO](https://about.worldfloraonline.org/tens/pteridophyte-phylogeny-group).

## Accessing WFO data

### Public-facing portals

There are two public-facing portals (websites) for accessing WFO data, <https://www.worldfloraonline.org/> and <https://wfoplantlist.org/>.

These two websites show the most recent **snapshot** (version) of the data.
Snapshots are taken twice per year, at the solstices (December and June).

Note that once a snapshot is taken, <https://wfoplantlist.org/> gets updated first; <https://www.worldfloraonline.org/> is also updated, but lags by a few weeks to months[^1].

[^1]: There is no real need to have two websites; this is an historical artifact that arose from the way WFO was developed. Eventually these two will be unified into single site.

### Rhakhis

[Rhakhis](https://list.worldfloraonline.org/rhakhis/ui/index.html) is the online interface to the WFO database.

The key difference between Rhakhis and the public-facing WFO portals is that Rhakhis shows the **current data**, whereas the portals show snapshots of the data.

The primary function of Rhakhis is to edit the WFO taxonomic data; however, you may also use it to browse the current data.

Rhakhis requires a [ORCID](https://orcid.org/) for login.
Anybody may create an OCRID at <https://orcid.org/register>.

Although anybody with an ORCID may login to Rhakhis and browse the data, only authorized users may edit the data.

### PPG and Rhakhis

PPG will use Rhakhis as its database management system.

During [Phase II](guidelines.qmd#phase-two), PPG members will be granted permission to edit names within taxonomic groups of their expertise (typically within a family or genus/genera).

Only members of the coordinating committee will have permission to edit names at higher taxonomic levels (family and above).

This will enable us to maintain names at the species level in an effective manner.

Instructions on how to use Rhakhis for editing will be posted once Phase II begins.